### ISSUE TITLE
Add non-long polling event support

### ISSUE THREAD

**Issue by ckevinhill** [box/box-java-sdk#101]
SDK seems to support Long-polling approach to event collection via EventStream class but I do not see any way of executing a non-polling event query - per example: https://developers.box.com/docs/#events with REST url of: curl https://api.box.com/2.0/events.  Long-polling stream doesn't seem to provide any historical cached events so unable to retrieve prior history events?

**Comment by TLuthra** [comment]
You're right, that is missing from the SDK currently.  One thing you can do is use the alternate constructor for ```EventStream``` to set the long-polling stream's starting position to a prior timestamp.  If you set the ```startingPosition``` to a few days ago you should be able to get all the events from that point onwards.

**Comment by ckevinhill** [comment]
Thanks - may give that a try.  I was working on directly calling events endpoint with:
    	
    	URL url = new URL ( configuration.getUrl() );
    	BoxAPIRequest request = new BoxAPIRequest(apiConnection, url, "GET");
    	BoxJSONResponse response = (BoxJSONResponse)request.send();
    	String json = response.getJSON();

This returns JSON correctly.  Is there an easy way to use the existing BoxEvent (api, json) class to initialize a List<BoxEvent>?  Or something similar to use existing SDK infrastructure?

**Comment by gcurtis** [comment]
The SDK doesn't have a way of parsing the response as a List of events, only as a single event. You can, however, use minimal-json (the SDK's JSON parser) or any other JSON parser to iterate through the entries. The `EventStream` code has a pretty simple example of how to do this here - https://github.com/box/box-java-sdk/blob/master/src/main/java/com/box/sdk/EventStream.java#L191

Your code would probably look something like:

```java
URL url = new URL (configuration.getUrl());
BoxAPIRequest request = new BoxAPIRequest(apiConnection, url, "GET");
BoxJSONResponse response = (BoxJSONResponse) request.send();
String json = response.getJSON();

JsonObject jsonObject = JsonObject.readFrom(json);
JsonArray entriesArray = jsonObject.get("entries").asArray();
List<BoxEvent> events = new ArrayList<BoxEvent>();
for (JsonValue entry : entriesArray) {
    BoxEvent event = new BoxEvent(apiConnection, entry.toString());
    events.add(event);
}
```

**Comment by ckevinhill** [comment]
Hugely helpful thanks!

**Comment by raj-jain** [comment]
I believe this is what we built in the SDK (non-long-polling), captured under issue titled ...
Streaming over Enterprise Events Log -- EventLogStream

**Comment by antusus** [comment]
There is a way of events without polling:
https://github.com/box/box-java-sdk/blob/main/doc/events.md#enterprise-admin-events
You can get current events and historical ones.
