### ISSUE TITLE
Incorrect key fetched from BoxAPIException in BoxAPIRequest.java method isResponseRetryable(int responseCode, BoxAPIException apiException), causing exception when connecting to BOX

### ISSUE THREAD

**Issue by Prabharaja** [box/box-java-sdk#1019]
- [x ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
When connecting to Box using BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(), exception is thrown stating 
{"error":"invalid_grant","error_description":"Current date\/time MUST be before the expiration date\/time listed in the 'exp' claim"}. This occurs due to exp time. In the flow, when the exception occurs and the response code 400, there are retry attempts , where the date advertised by the Box server in the exception is set the current time to synchronize clocks.So the next try will be successful. 
There is error in reading the response body from the exception. 

In the below method addressing the below code, the responseBody will not have key as code , it should be 'error' instead of 'code'. 
Fixing this would solve the following  error. {"error":"invalid_grant","error_description":"Current date\/time MUST be before the expiration date\/time listed in the 'exp' claim"}
if (responseBody.get("code") != null) {
                errorCode = responseBody.get("code").toString();**

 public static boolean isResponseRetryable(int responseCode, BoxAPIException apiException) {
        String response = apiException.getResponse();
        String message = apiException.getMessage();
        String errorCode = "";

        try {
            JsonObject responseBody = Json.parse(response).asObject();
            **if (responseBody.get("code") != null) {
                errorCode = responseBody.get("code").toString();**
            }
        } catch (Exception e) {
        }

        Boolean isClockSkewError = responseCode == 400
            && errorCode.contains("invalid_grant")
            && message.contains("exp");

        return (isClockSkewError
            || responseCode >= 500
            || responseCode == 429);
    }

### Expected Behavior
The retry attempt will connect to BOX as the Time synch with Box server is addressed.
Feb 23, 2022 6:43:33 AM com.box.sdk.BoxLogger warn
WARNING: Retrying authentication request due to transient error status=400 body={"error":"invalid_grant","error_description":"Current date\/time MUST be before the expiration date\/time listed in the 'exp' claim"}
Payload {"iss":"gkyil0451ut5dgkvvbir5s21h5vk9npj","aud":"https://api.box.com/oauth2/token","exp":1645616676,"sub":"xxxxx","box_sub_type":"enterprise","jti":"GDWIOnaB1lWrF5w0bhEMosvN0M6aJ0ZmTzF6FsfiUrNfml0R9sh6yU4hqPGC6apjW0NvszDj_V_0xdEb_FDjxw"}
Connected to BOX 

### Error Message, Including Stack Trace
Feb 23, 2022 6:43:33 AM com.box.sdk.BoxLogger warn
WARNING: Response
POST https://api.box.com/oauth2/token
HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Strict-Transport-Security: max-age=31536000
Cache-Control: no-store
Connection: keep-alive
Set-Cookie: site_preference=desktop; path=/; domain=.box.com; secure, cn=27; expires=Thu, 23-Feb-2023 11:44:05 GMT; Max-Age=31536000; path=/; domain=.app.box.com; secure, bv=OPS-45038; expires=Wed, 02-Mar-2022 11:44:05 GMT; Max-Age=604800; path=/; domain=.app.box.com; secure, box_visitor_id=xxxxx; expires=Thu, 23-Feb-2023 11:44:05 GMT; Max-Age=31536000; path=/; domain=.box.com; secure
Date: Wed, 23 Feb 2022 11:44:05 GMT
Content-Type: application/json

{"error":"invalid_grant","error_description":"Current date\/time MUST be before the expiration date\/time listed in the 'exp' claim"}

### Screenshots
(https://github.com/box/box-java-sdk/blob/main/src/main/java/com/box/sdk/BoxAPIRequest.java) Line 198

### Versions Used
Java SDK:  Java 1.8
Java: Java 1.8

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by mwwoda** [comment]
Hi @Prabharaja 

Nice catch! I'll look into it and keep you posted on any updates.

Thanks,
Mateusz

**Comment by Prabharaja** [comment]
Thanks, when is the next release planned, so I can get the SDK?

**Comment by antusus** [comment]
Hi @Prabharaja,

We will do a bugfix release next week.

**Comment by humanKKA** [comment]
> 你好@Prabharaja，
> 
> Box Java SDK 今天发布，版本 3.1.1 包含您要求的修复。

当我在4.10.0版本中使用debug查看获取连接的时候依然有这个报错
