### ISSUE TITLE
BoxEvent does not seem to initialized SourceInfo pathCollection fully (i.e. missing folder name)

### ISSUE THREAD

**Issue by ckevinhill** [box/box-java-sdk#102]
When executing:
BoxEvent event = new BoxEvent(apiConnection, entry.toString());

on an event that contains path_collection like:
      "path_collection" : {
        "total_count" : 3,
        "entries" : [ {
          "type" : "folder",
          "id" : "0",
          "sequence_id" : null,
          "etag" : null,
          "name" : "All Files"
        }, {
          "type" : "folder",
          "id" : "881169314",
          "sequence_id" : "1",
          "etag" : "1",
          "name" : "eBusiness Platforms Program"
        }, {
          "type" : "folder",
          "id" : "3112112883",
          "sequence_id" : "0",
          "etag" : "0",
          "name" : "Ecosystem"
        } ]
      },

The resulting BoxEvent.getSourceInfo().getPathCollection contains BoxFolder objects that ONLY have an ID (and not the folder name).

This results in having to call folder.getInfo() to return a BoxFolder.Info object via additional API call to get the folder name.

This seems wasteful as the name information is already passed with the path_collection JSON.  Am I doing something incorrectly?

**Comment by gcurtis** [comment]
You're right - this is something that could be improved. Right now `getPathCollection()` returns a List of `BoxFolder` instead of `BoxFolder.Info` which is why you're only able to get the ID.

**Comment by gcurtis** [comment]
I created a bug for this in #105.
