### ISSUE TITLE
Box API : List files inside the trashed folder

### ISSUE THREAD

**Issue by samrajcse** [box/box-java-sdk#1030]
Hi ,

I am using JAVA sdk and i found there is no option to list down the files inside the trashed folder. Box API failing in below scenario,

I did a validation with REST api and same behaviour is observed.
1. I have deleted the folder with name Sam_Test1 which has 2 document. When i hit this url, i can view the folder name. But I used the keywords available in the files inside that folder, query return zero results.

https://api.box.com/2.0/search?query=sam&trash_content=trashed_only

2. Then, I used this api to list down all files and folders inside the trash. 
https://api.box.com/2.0/folders/trash/items
And I got the folder name and ID. I am trying to list the files inside that folder. API is not working. I want to view the files without restoring.

https://api.box.com/2.0/folders/123648402594/trash/ - List's basic info of that folder.
https://api.box.com/2.0/folders/123648402594/trash/items - 403 forbidden error.
https://api.box.com/2.0/folders/123648402594/items- 404 error
https://api.box.com/2.0/folders/123648402594/items/trash/ - 404 error.

Can I know the api and param to list down the option to get the list of files in the trashed folder.

**Comment by mhagmajer** [comment]
Thanks for posting the issue @samrajcse. This looks like a problem with underlying API. I'll check with the API team and get back to you

**Comment by antusus** [comment]
Hi @samrajcse,

what you are observing is how API works. If you remove a folder with an internal structure only parent will be shown in trash. Sadly there is no way of checking what is inside of a trashed folder.
I would advise you to contact our backend team. You can create a ticket at https://support.box.com/hc/en-us/requests/new and ask about this feature.
