### ISSUE TITLE
Improve saving and restoring connections

### ISSUE THREAD

**Issue by gcurtis** [box/box-java-sdk#104]
The process of saving and restoring an API connection is pretty complicated and error-prone. The developer needs to know to save the access token, refresh token, expiration time, and last refresh time in order to effectively restore a connection.

One solution is to provide methods that automatically serialize and deserialize the connection's state to and from JSON. The developer would then only need to worry about saving the JSON string. For example:

```java
public class BoxAPIConnection {
    ...

    // Restore a saved connection.
    public static BoxAPIConnection restore(String state) { ... }

    // Save the connection's state to a JSON string.
    public String save() { ... }
}
```

`BoxAPIConnectionListener` could also be updated to pass the state string via the `onRefresh()` method.

```java
public interface BoxAPIConnectionListener {

    // The state is the connection's new state after the refresh. It can
    // be saved to restore the connection later.
    void onRefresh(String state);
}
```

**Comment by tcharles79** [comment]
i like this idea Greg. But it'll increase the number of database calls.

I understand that, on every BoxAPIConnection request i create i should pass the 'state' instead of access/refresh tokens. Also on every response we should look for the 'state' and store it in database.

**Comment by mikebell90** [comment]
I commented privately. This doesn't work, because it assumes you store the state as an opaque string. Unfortunately, that doesn't work for me (and probably others). We need to store individual token pieces with our correct setup.

**Comment by gcurtis** [comment]
Interesting, that's a good point. Can you elaborate on how you use the individually stored tokens?

**Comment by mikebell90** [comment]
We use them to access (or rather will, I am working on this particular oauth integration right now, we have many others) the oauth request and to refresh. Granted you abstract a lot of that here, but I guarantee there will be weirdisms where having explicit values is good for diagnostics.

**Comment by mikebell90** [comment]
Perhaps a more compelling argument is that any bugs or omissions in your API (by accident of course or just the passage of time) become FATAL (as in unsolvable) unless the user can manually do api calls. And that normally requires knowing all the separate values.

**Comment by gcurtis** [comment]
Would passing in the `BoxAPIConnection` itself as a parameter make it more explicit that it's safe to access? Something like:

```java
public interface BoxAPIConnectionListener {
    void onRefresh(BoxAPIConnection api);
}
```

Then from within the listener you have full access to the tokens or you could call `api.save()` to save the state as an opaque blob (if you don't care about storing the tokens individually).

**Comment by mikebell90** [comment]
Sure.

**Comment by gcurtis** [comment]
Thanks for all of your feedback! The new planned methods for `BoxAPIConnection` and `BoxAPIConnectionListener` are as follows:

```java
public class BoxAPIConnection {
    ...

    // Restore a saved connection.
    public static BoxAPIConnection restore(String state) { ... }

    // Save the connection's state to a JSON string.
    public String save() { ... }
}
```

```java
public interface BoxAPIConnectionListener {
    void onRefresh(BoxAPIConnection api);
    void onError(BoxAPIConnection api, Exception error);
}
```

We expect most developers to save the connection state by calling the `save()` method in the `onRefresh(BoxAPIConnection)` callback and restore it later using the `restore(String)` method.

```java
api.addListener(new BoxAPIConnectionListener() {
    public void onRefresh(BoxAPIConnection api) {
        String state = api.save();
        // Persist the state string somewhere.
    }
});

String connectionState = // Get the persisted state from somewhere
BoxAPIConnection api = BoxAPIConnection.restore(state);
```

However, for more advanced use-cases, the connection's tokens and other state information can still be accessed directly:

```java
api.addListener(new BoxAPIConnectionListener() {
    public void onRefresh(BoxAPIConnection api) {
        String accessToken = api.getAccessToken();
        String refreshToken = api.getRefreshToken();
        // etc.
    }
});
```

It will also be documented that interacting with the connection in the `onRefresh(BoxAPIConnection)` callback is thread-safe.
