### ISSUE TITLE
Cannot Generate a Token Using Auth Code

### ISSUE THREAD

**Issue by Amr-M-Fouad** [box/box-java-sdk#1057]
### Description of the Issue
Cannot authenticate using the auth code constructor with the SDK returning the following exception message **"An invalid token URL indicates a bug in the SDK."**. I believe it is down to the recent base URL refactor change (#1042) and line 224 in BoxAPIConnection should be updated to use the getTokenURL instead.
` public void authenticate(String authCode) {
        URL url;
        try {
            url = new URL(this.tokenURL);
        } catch (MalformedURLException e) {
            assert false : "An invalid token URL indicates a bug in the SDK.";
            throw new RuntimeException("An invalid token URL indicates a bug in the SDK.", e);
        }
`
### Steps to Reproduce
1. Call the constructor **public BoxAPIConnection(String clientID, String clientSecret, String authCode)** with the neccessary arguments.
2. A runtime exception is thrown with the following message **"An invalid token URL indicates a bug in the SDK."**.

### Expected Behavior
Expected to be able to generate a token using the auth code.

### Error Message, Including Stack Trace
`java.lang.RuntimeException: An invalid token URL indicates a bug in the SDK.
	at com.box.sdk.BoxAPIConnection.authenticate(BoxAPIConnection.java:227) ~[box-java-sdk-3.2.0.jar:na]
	at com.box.sdk.BoxAPIConnection.<init>(BoxAPIConnection.java:146) ~[box-java-sdk-3.2.0.jar:na]`

### Versions Used
Java SDK: 3.2.0
Java: 1.8

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by antusus** [comment]
Hi @Amr-M-Fouad ,
thanks for raising this. You are right there is a bug with getting token url. 
I'll create a bugfix release.
