### ISSUE TITLE
Add better documentation and examples for the full OAuth flow

### ISSUE THREAD

**Issue by gcurtis** [box/box-java-sdk#106]
Most of the examples and documentation demonstrate how to use the SDK with a developer token, which isn't practical for a real-world application.

**Comment by debu66er** [comment]
Any progress on this? Looking for a sample for Manual Authentication. Thanks!

**Comment by gcurtis** [comment]
We're still working on this. Some other more high-priority issues came up, but we should have this soon!

**Comment by kpdv** [comment]
Hello.. any updates on this? 
Thanks

**Comment by jtrunick** [comment]
HELPPPP!!!!!!!!

**Comment by basement199** [comment]
I agree. The samples using developer tokens are limited. Would love to see some real world examples.

**Comment by tarrencev** [comment]
Consolidating with #271
