### ISSUE TITLE
Why can't general task created via Box Java SDK?

### ISSUE THREAD

**Issue by gurukashyap** [box/box-java-sdk#1062]
BoxTask only supports 'review' task , why can't we create general task. From  Box UI it is supported.

https://github.com/box/box-java-sdk/blob/main/src/main/java/com/box/sdk/BoxTask.java

**Comment by antusus** [comment]
Hi @gurukashyap ,

You can create general task using API:
https://github.com/box/box-java-sdk/blob/main/doc/tasks.md#add-a-task-to-a-file
I can see that current documentation is a bit outdated. So here is a snippet:
```java
boxFile.addTask(BoxTask.Action.COMPLETE, "General Task created with API", null);
```
The `BoxTask#getAction` only returns `Review` action but as you can see it is deprecated and you should use `BoxTask#getTaskType`.
I hope this answers your question.
