### ISSUE TITLE
Box Folder API, can't page

### ISSUE THREAD

**Issue by Cheney12345** [box/box-java-sdk#1071]
Hi there
Our project have a folder which has more than 100,000 sub-folders. For some reason, we need to get all the sub-folder.
I'm using the Java SDK 3.3.0 this is my code snap:

`       String accessToken = boxUtils.getAccessToken();
        BoxAPIConnection api = new BoxAPIConnection(accessToken);
        BoxFolder folder = new BoxFolder(api, "12345");
        
        // setup ascending sorting by name
        SortParameters sorting = SortParameters.ascending("name");
        // setup paging with offset 0 and limit 100
        long offset = 0;
        long limit = 100;
        PagingParameters paging = PagingParameters.offset(offset, limit);
        Iterable<BoxItem.Info> itemIterator = folder.getChildren(sorting, paging);
        Iterator<BoxItem.Info> iterator = itemIterator.iterator();

        while(iterator.hasNext()){
            BoxFolder.Info folderInfo = (BoxFolder.Info) iterator.next();
            String name = folderInfo.getName();`

The issue is the paging is not working, it returns all the sub-folders once.
Any help please?

**Comment by lukaszsocha2** [comment]
Hi @Cheney12345,
the method you used - `folder.getChildren` always returns all items inside a folder. The `limit` used here `PagingParameters.offset(offset, limit)` determines only how many of the items should be fetched in one API call. Paging is done automatically under the hood. So your code works as follows:
1. It makes API call to fetch first page of 100 elements starting from offset 0
2. Then using iterator it goes through all fetched items
3. When the iterator went through all 100 elements form the first page, it makes another API call to fetch next 100 items starting from offset 100.
4. And it repeats until it will eventually fetch all the items in the folder.

If you want to make a certain action after processing all items from a page, you can create a counter and check if its value is dividable by the limit value:
```
int nrOfProcessedItems = 0;
while(iterator.hasNext()) {
    BoxFolder.Info folderInfo = iterator.next();
    String name = folderInfo.getName();
    nrOfProcessedItems++;

    if(nrOfProcessedItems % limit == 0) {
        // one page was processed
    }
}
```

Alternatively you can use `folder.getChildrenRange` method. It always returns only one page of results and you can handle paging on your own:
```
long offset = 0;
long limit = 100;
Iterable<BoxItem.Info> itemIterator = folder.getChildrenRange(offset, limit);
Iterator<BoxItem.Info> iterator = itemIterator.iterator();

while(iterator.hasNext()) {
    BoxFolder.Info folderInfo = iterator.next();
    String name = folderInfo.getName();
}
// it will exit while loop after iterating all 100 items from the first page
```

Side note:
This line `BoxFolder.Info folderInfo = (BoxFolder.Info) iterator.next();` may throw `ClassCastException` if any item inside folder will be of different type than folder (e.g. file). So I suggest to check type of the item before casting:
```
BoxItem.Info itemInfo = iterator.next();
if(!itemInfo.getType().equals("folder")){
    continue;
}
BoxFolder.Info folderInfo = (BoxFolder.Info) itemInfo;
```


If this answer does not solve your problem let us know.
Best,
@lukaszsocha2

**Comment by Cheney12345** [comment]
Thanks, great helpful.
I think it's better to update the API doc I found there are some place not perfect.
