### ISSUE TITLE
How to sort when use getChildrenRange?

### ISSUE THREAD

**Issue by Cheney12345** [box/box-java-sdk#1074]
Hi there
I'm guided to use getChildrenRange to do the paging when I tired to get over 100,000 sub-folders under my folder.
But one question is how to use the parameters of sort and direction with getChildrenRange? Or there is a default way? If yes, what's it?

**Comment by mwwoda** [comment]
Hi @Cheney12345 
I see that `getChildrenRange()` does not support sorting and direction. You can use `getChildren()` instead.
