### ISSUE TITLE
Remove the BoxAPIConnection(String clientID, String clientSecret) constructor

### ISSUE THREAD

**Issue by gcurtis** [box/box-java-sdk#108]
This constructor isn't really useful and should be removed to simplify the number of ways a `BoxAPIConnection` can be created.

**Comment by TLuthra** [comment]
We actually only use this constructor.  Our application creates an APIConnection before we have any use authentication information, and this was the only constructor that doesn't require either an authentication code or an auth token.

You can still go ahead and remove it, we'll just call the more verbose one: ```new BoxAPIConnection(CLIENT_ID, CLIENT_SECRET, null, null)```, but just wanted to point out a use case.

**Comment by gcurtis** [comment]
That's a good point. If you're looking to authenticate at a later time with the `authenticate()` method, then this is the constructor you'd wanna use.
