### ISSUE TITLE
Under the same permission, different connection methods get different results

### ISSUE THREAD

**Issue by sekiHou** [box/box-java-sdk#1092]
Hi, I have a question about the permission to download and upload files.

Premise:
1. Test under the enterprise box.
2. With the same permission setting, the target files and folders have shared the editing permission with the service account.
3. The file information and folder information can be normally obtained through the following two connection methods.
```
BoxFile boxFile = new BoxFile(BOX_API_CONNECTION, fileId);
BoxFolder boxFolder = new BoxFolder(BOX_API_CONNECTION, folderId);
```

Question:
`BoxAPIConnection api = BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(boxConfig);`
After using the above method to connect, downloading and uploading files will fail. Error Code[403]
```
BoxFile boxFile = new BoxFile(BOX_API_CONNECTION, fileId);
boxFile.download(out);
```
```
BoxFolder boxFolder = new BoxFolder(BOX_API_CONNECTION, folderId);
BoxFile.Info newFileInfo = boxFolder.uploadFile(in, fileName);
```
![image](https://user-images.githubusercontent.com/94027021/187137670-82c724b1-f78e-4f8d-a16e-435501220ce8.png)

However, files can be downloaded and uploaded normally by using the connection method of developer token.
`BoxAPIConnection api = new BoxAPIConnection("Developer Token");`

Before that, I used this connection method under my personal box account, and the app can also download and upload.`BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(boxConfig)` 

App Configuration:
![image](https://user-images.githubusercontent.com/94027021/187138168-5247d34f-49f3-48f3-bb3d-876842665bc8.png)
![image](https://user-images.githubusercontent.com/94027021/187138222-60be4e0d-d621-4b11-adc2-858e1ad3b8e8.png)
![image](https://user-images.githubusercontent.com/94027021/187138289-787f84f2-171d-4285-b29e-71abcc3b1591.png)
![image](https://user-images.githubusercontent.com/94027021/187138332-58697531-0301-461c-9382-60f569350698.png)

**Comment by mhagmajer** [comment]
Thanks! We'll look into it

**Comment by antusus** [comment]
Hi @sekiHou ,

First and foremost: you are changing Application settings and not user settings that is why you can access those file with developer token. You are not operating as application but as a user. The configuration you were showing is for Application access. When you share error response please share them in full as your screenshots do not contain error message and it makes more difficult to diagnose the error.

To summarise:
1. You have crated some files and folders as a user, not a service account.
1. Then you shared this content with service account. Service account is at least `Previewer upload` so it can create new content.
1. You can view information, but downloading, uploading and creating files ot folders fails with 403 error.

I was able to reproduce cannot upload new file it with two scenarios:
1. My application did not have:  "Write all files and folders in Box" permission. Error message: `The request requires higher privileges than provided by the access token.`
1. My application was reauthorised with: "Write all files and folders in Box" permission, but I didn't give Service account proper role (for example `Editor`). Error message: `The API returned an error code [403 | nxou6sh5nsaummgo] access_denied_insufficient_permissions - Access denied - insufficient permission`


I was able to reproduce not being able to download files with two scenarios:
1. Application didn't have read access. Error message: `The request requires higher privileges than provided by the access token.`
1. When shared folder user permission is set to `Previewer` or `Uploader`. Error message: `The API returned an error code [403 | br93qoh5ns7mogmi.0a1709b7f55b2adbece40d09b1d6aff56] access_denied_insufficient_permissions - Access denied - insufficient permission`

So please reauthorise your application to make sure your permissions are applied correctly and review level of share permissions for service account Maybe this will fix the problem.
As far as I can tell SDK works as expected. If you still will have an issue with this you can reach out again or contact our backend team at https://support.box.com/hc/en-us/requests/new
