### ISSUE TITLE
BoxCollaboration.getItem() should return BoxItem.Info not BoxFolder.Info

### ISSUE THREAD

**Issue by BruceBlanchard** [box/box-java-sdk#1101]
BoxCollaboration can happen on a file or folder, so not sure why this method is returning a BoxFolder.info - BoxItem.Info is more appropriate..

**Comment by antusus** [comment]
Hello @BruceBlanchard ,

thank you for spotting that. We will fix that and notify you. We should be able to provide a fix within few days.
