### ISSUE TITLE
BoxFile.Info getTags returning always null ?

### ISSUE THREAD

**Issue by alessandrobenedetti** [box/box-java-sdk#112]
Hi,
is it a known bug that BoxFile.Info getTags() always return null ?
Also if the tags are set for the file , Box side ?

BoxFile.Info info=file.getInfo();
List<String> tags = info.getTags(); //apparently there is a bug Box side

Cheers

**Comment by gcurtis** [comment]
The `tags` field isn't returned by default when calling `getInfo()`. The API only returns a subset of fields when retrieving info unless additional fields are manually specified. You find the API documentation on this here - https://developers.box.com/docs/#fields.

To get the `tags` field, you will need to specify the fields you want with something like:

```java
// This will return ONLY the name, description, size, and tags fields. All other fields
// will be excluded.
BoxFile.Info info = file.getInfo("name", "description", "size", "tags");
```

There's also an `ALL_FIELDS` constant you can use to just grab everything:

```java
// This will return every possible field, but will be slower.
BoxFile.Info info = file.getInfo(BoxFile.ALL_FIELDS);
```

Let me know if this works for you!

**Comment by alessandrobenedetti** [comment]
Thanks ! Perfectly worked !

Cheers
