### ISSUE TITLE
NullPointerException when using prefill in create sign request

### ISSUE THREAD

**Issue by tajujsag** [box/box-java-sdk#1120]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
If you try to prefill a text/checkbox signing tag the SDK throws an exception while creating the sign request.

### Steps to Reproduce
I'm trying to create a sign request (BoxSignRequest.createSignRequest) with a BoxSignRequestCreateParams,prefillTags containing at least one BoxSignRequestPrefillTag, that is not of type Date.
I get a NullPointerException.

### Expected Behavior
The sign request should be sent successfully.

### Error Message, Including Stack Trace
java.lang.NullPointerException: null: java.base/java.util.Calendar.setTime(Calendar.java:1800) java.base/java.text.SimpleDateFormat.format(SimpleDateFormat.java:974) java.base/java.text.SimpleDateFormat.format(SimpleDateFormat.java:967) java.base/java.text.DateFormat.format(DateFormat.java:374) com.box.sdk.BoxDateFormat.formatAsDateOnly(BoxDateFormat.java:88) com.box.sdk.BoxSignRequestPrefillTag.getJSONObject(BoxSignRequestPrefillTag.java:119) com.box.sdk.BoxSignRequestCreateParams.appendParamsAsJson(BoxSignRequestCreateParams.java:322) com.box.sdk.BoxSignRequest.createSignRequest(BoxSignRequest.java:144) com.smartcomms.integration.box.BoxDelivery.signFiles(BoxDelivery.java:144) com.smartcomms.integration.box.BoxDelivery.processCollectedJobResults(BoxDelivery.java:85) com.smartcomms.pi.integration.base.AbstractDelivery.endEnvelope(AbstractDelivery.java:108) com.thunderhead.distributors.outputproc.delivery.custom.CustomDelivery.lambda$endEnvelope$3(CustomDelivery.java:178)

### Versions Used
Java SDK: 3.7.1
Java: jdk-11.0.6

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by lukaszsocha2** [comment]
Hi @tajujsag,
I can confirm that I was able to replicate this error. We will try to fix it and make patch release as soon as possible.
Best,
@lukaszsocha2
