### ISSUE TITLE
How to check of a file id is a File or Folder

### ISSUE THREAD

**Issue by DImuthuUpe** [box/box-java-sdk#1127]
Is there a way in the SDK to provide the information of an id of an entry referring to a folder or a file?

**Comment by antusus** [comment]
Hello @DImuthuUpe ,

it all depends on the API response. Some are returning type: "file" | "folder". How do you get this object ID?
There is no API that returns type of some ID.

**Comment by lukaszsocha2** [comment]
Hi @DImuthuUpe, 
does this response answer your question or do you need anything else?
