### ISSUE TITLE
Refresh token expired 

### ISSUE THREAD

**Issue by misterfifi1** [box/box-java-sdk#114]
HI, 

When I try to refresh my access token, the Refresh token expires, I am using this method api.refresh();

I tried all these use cases:
- Create an access and refresh tokens with the API in PHP 
- Create an access and refresh tokens with postman 
- Refresh the Token with the API in PHP 
- Refresh the Token with postman 
- Use the access token using the Java Box SDK (generated by postman or PHP)

When I use the JAVA box SDK to refresh my token, it expires... WHY ??

**Comment by gcurtis** [comment]
I'm not sure I fully understand your issue. Are you getting a "401 Unauthorized" after calling the refresh method?

The API will always give you a new refresh token after refreshing, and then revoke the previous one. This provides some extra security in case your tokens are ever compromised. You can use a `BoxAPIConnectionListener` to be notified whenever the access/refresh tokens change.

**Comment by misterfifi1** [comment]
Ok, but can I an more information, documentation or example?

**Comment by KDANGER101** [comment]
BOX refresh token expires in 60 days.  Instead of waiting for 60 days to see what happens, can you tell me what Box does when that happens?  Does Box issue a new refresh token?  Does the issuance of the refresh token require any end-user involvement or does Box just validate the old refresh token and then issue a new one.

**Comment by misterfifi1** [comment]
Hi Kdanger101, 
If the refresh token is expired, you have to log in one more time, but in the other case, using api.refresh() (or autorefresh) you will received a new refresh token automatically.
