### ISSUE TITLE
`OAUTH_SUFFIX` gets appended twice to `baseAuthorizationURL`

### ISSUE THREAD

**Issue by deepak-penaganti** [box/box-java-sdk#1147]
https://github.com/box/box-java-sdk/blob/3d29753f1ee6fe390ea4a88bba3e5f65d302db9b/src/main/java/com/box/sdk/BoxAPIConnection.java#L470

https://github.com/box/box-java-sdk/blob/3d29753f1ee6fe390ea4a88bba3e5f65d302db9b/src/main/java/com/box/sdk/BoxAPIConnection.java#L304

* `OAUTH_SUFFIX` gets appended twice to `baseAuthorizationURL` when invoking instance method `getAuthorizationURL` in class `BoxAPIConnection`

**Comment by lukaszsocha2** [comment]
Hi @deepak-penaganti,
thanks for finding a bug and fixing it. We've merged your pr. It will be available in next release.
Best,
@lukaszsocha2
