### ISSUE TITLE
Wrong progress reported to ProgressListener by AbstractBoxMultipartRequest

### ISSUE THREAD

**Issue by ivan-ankov** [box/box-java-sdk#1149]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
The following code is just wrong in AbstractBoxMultipartRequest:

        public void writeTo(BufferedSink bufferedSink) throws IOException {
            byte[] buffer = new byte[BUFFER_SIZE];
            int n = this.inputStream.read(buffer);
            int totalWritten = n;
            while (n != -1) {
                bufferedSink.write(buffer, 0, n);
                if (progressListener != null) {
                    progressListener.onProgressChanged(totalWritten, this.contentLength());
                }
                totalWritten += n;
                n = this.inputStream.read(buffer);
            }
        }

**totalWritten** is initialized with **n** and then incremented with the same **n** in the cycle, before **n** is updated.

### Steps to Reproduce
1. Upload a file larger than 8192 bytes (the upload buffer size) and set a progress listener
2. At some point the listener will receive **onProgressChanged()** with **numBytes** > **totalBytes**

### Expected Behavior
Progress reporting to be correct and to not exceed the size of the uploaded file

**Comment by antusus** [comment]
Hi @ivan-ankov,
Sorry for very late response. You are right. We will look into this and fix this.

**Comment by antusus** [comment]
Hello @ivan-ankov ,

the fix for this is available in 4.0.1 release. Once again thank you for reporting it.
