### ISSUE TITLE
Support for Tasks

### ISSUE THREAD

**Issue by jonjo-manywho** [box/box-java-sdk#115]
Hi - will you be implementing support for the API endpoints for Tasks? I need the functionality in an application I'm building and it's not yet in the SDK!

I can code it and submit a pull request also, if that might be better.

**Comment by gcurtis** [comment]
We are planning on adding support for it, but we'd gladly appreciate help! If you're interested, just let me know what changes you wanna make (for example, new classes, methods, etc.) so we can figure out the design before writing too much code.

**Comment by gcurtis** [comment]
Closed by c9f36df756be9459360001b345f6af0178eb868f.
