### ISSUE TITLE
Add Query Param 'fields' when creating and updating user

### ISSUE THREAD

**Issue by jenniferdobox** [box/box-java-sdk#1154]
Box Public API supports field 'fields' when updating and creating user
https://developer.box.com/reference/post-users/#query-parameters

we would need this to have only 1 HTTP call to Box Public API when creating/updating user because we want to request for non-standard fields.

At the moment, we're doing a workaround by getting user info after creating user. However, as performance plays an important role in our service, we failed to serve client when having 2 HTTP calls.

**Comment by lukaszsocha2** [comment]
Hi @jenniferdobox,
thanks for posting this issue. We will try to add this field soon.
Best,
@lukaszsocha2
