### ISSUE TITLE
Groups aren't handled when parsing the accessible_by field in collaborations

### ISSUE THREAD

**Issue by alessandrobenedetti** [box/box-java-sdk#116]
Hi!

Playing with the Java SDK  I was trying to retrieve the collaborators for a folder:

```java
Collection<BoxCollaboration.Info> collaborations = parentFolder.getCollaborations();
for(BoxCollaboration.Info collaborationInfo:collaborations) {
    BoxCollaboration.Role role = collaborationInfo.getRole();
    if(isReaderRole(role)) {
        BoxCollaborator.Info accessibleBy = collaborationInfo.getAccessibleBy();
        if(accessibleBy instanceof BoxUser.Info)
            permissionType = USER_PERMISSION_TYPE;
        else if(accessibleBy instanceof BoxGroup.Info)
            permissionType = GROUP_PERMISSION_TYPE;
        aclPermissions.add(permissionType+"-"+accessibleBy.getID());
    }
}
```

Apart the simple code snippets, my problem is that even when the collaborator is a group, I get a BoxUser (a strange instance of this object with really few attributes).

I was expecting a BoxGroup there, am I doing anything wrong?

**Comment by gcurtis** [comment]
Thanks for catching this. It looks like this is a bug with parsing the `accessible_by` field.

**Comment by gcurtis** [comment]
It looks like there's a similar issue in `BoxFolder.collaborate(BoxCollaborator, BoxCollaboration.Role)` where we aren't properly handling groups.

**Comment by alessandrobenedetti** [comment]
Thanks Greg!
I will make sure to use the latest fixed version of the sdk as it will be available !
Cheers
