### ISSUE TITLE
problem with creating enterprise user

### ISSUE THREAD

**Issue by pbale** [box/box-java-sdk#1166]
- [ yes] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [yes ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ yes] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ yes] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I am facing a problem in creating an enterprise user. Box API throws bad_request. I am able to change the status of the user from active to inactive and vice versa.

BoxUser.Info created = BoxUser.createEnterpriseUser(api, gad011@illinois.edu, test gad011);

The stack trace is:
com.box.sdk.BoxAPIResponseException: The API returned an error code [400 | rao0zwhdrnxkdnoz.0cbe753ae92a554241979cfda1b6b36d1] bad_request - Bad Request
	at com.box.sdk.BoxAPIResponse.toBoxResponse(BoxAPIResponse.java:148)
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:607)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:383)
	at com.box.sdk.BoxJSONRequest.send(BoxJSONRequest.java:106)
	at com.box.sdk.BoxJSONRequest.send(BoxJSONRequest.java:17)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:350)
	at com.box.sdk.BoxJSONRequest.send(BoxJSONRequest.java:101)
	at com.box.sdk.BoxUser.createEnterpriseUser(BoxUser.java:182)
	at com.box.sdk.BoxUser.createEnterpriseUser(BoxUser.java:127)
	at edu.illinois.techservices.cloudbroker.box.BoxUserAccountLifecycle.create(BoxUserAccountLifecycle.java:55)
	at edu.illinois.techservices.cloudbroker.worker.action.ProvisionAction.executeAction(ProvisionAction.java:17)
	at edu.illinois.techservices.cloudbroker.worker.action.Action.call(Action.java:68)
	at edu.illinois.techservices.cloudbroker.worker.action.Action.call(Action.java:28)
	at edu.illinois.techservices.cloudbroker.worker.CloudWorker.run(CloudWorker.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:831)

### Versions Used
Java SDK: 4.1.0
Java: open JDK 20.0.1

**Comment by congminh1254** [comment]
Hi @pbale,

It seems like this is an error of API side, I will forward this question to the team handling this service and will get back to you as soon as I get any response.

Thanks for your patience.

Best,

Minh

**Comment by congminh1254** [comment]
Hi @pbale,

I got the answer from the team that is responsible for this problem.
So it seems like this domain "illinois.edu" is registered for another enterprise, and you can not use the email from this domain to join another enterprise.

So if you have authorised permission on this domain, you can contact our [Box Support](https://support.box.com/hc/en-us/requests/new), they will try their best to help you.

Best,
Minh

**Comment by pbale** [comment]
Minh,
Thank you for the quick responses. We have been using dev box console (https://dev-uofi.app.box.com) in our test/dev environments and been creating accounts with out any problem. The only difference now is I registered my application with different names to separate it for my (test/dev) environments.  Does this causing the issue?
![Screenshot 2023-05-09 at 5 43 24 PM](https://github.com/box/box-java-sdk/assets/1521151/179937d7-cb36-4833-9c8a-3e409999e6c0)

**Comment by congminh1254** [comment]
Hi @pbale,

So you can check this option in your prod environment, to see if the option of "Auto Enrollment" is Enabled or not? If it's enabled in any enterprise (example prod), so the others enterprise (dev/test) will not able to add user with that domain name.

![Screenshot 2023-05-10 at 10 52 38](https://github.com/box/box-java-sdk/assets/9329079/3a7b700c-1394-49f3-9bb3-1133c90e2bb5)

Beside that, you can try to add the Domain name to the Domain Management segment in your Box Admin, and try again with your dev/test environments.

Bests,
Minh

**Comment by pbale** [comment]
Hello Minh,

I am not able to see the "auto enrollment" status as that frame is unable to load on prod. 

![Screenshot 2023-05-11 at 9 50 32 AM](https://github.com/box/box-java-sdk/assets/1521151/951fed0e-cfea-4c44-bb67-41aed0b19588)

I am worried to add the domains to Domain Management segment on dev box as it might mess up the production env. Even if I want to try adding, it might not be  possible to add because as part of add domain process I need to copy the verification code to the domain host account, to which I don't have any privileges. Also the application is used by tri-campuses here and each has a different domain. 

sorry to bombard you here as I haven't heard back from  Box Support yet and I am on a deadline. Any help would be appreciated. 

Thanks,
Pbale

**Comment by congminh1254** [comment]
Hi @pbale 

As I'm only working on SDK so I'm not sure why the Domain Management is not loading on your prod account. But as I guess, the domain is having "auto enrollment" activated, so you are not able to add user from this domain to any other account.

In this case, for testing on dev environment, I think you are only able to create account with another email extension to make it works.

Best,
Minh
