### ISSUE TITLE
OutOfMemoryError when using uploadLargeFile on Android

### ISSUE THREAD

**Issue by kiyohito-nagano** [box/box-java-sdk#1170]
### Description of the Issue

An OutOfMemoryError occurred when trying to upload a 500MB file using the Java SDK on Android.
It occurred when using BoxFolder.uploadLargeFile.

### Steps to Reproduce
1. Get access token with JWT authentication
2. new BoxAPIConnection(accessToken)
3. Get folder to upload with BoxAPIConnection
4. upload Large File
5. error occur.

terminal: AQUOS wish, Galaxy A20
Android version: 13, 11
Box Java SDK Version: both 3.8.0(same 4.1.1)

The flow this problem occurs seems to be as follows in uploadLargeFile.
1. Execute API for upload_sessions
2. Get part size in response
3. new the file size of part size
4. error occur.

3 is trying to new 33554448 bytes, but depending on the terminal it is not possible to secure that size of memory.
An error occurs in bytesRead = stream.read(bytes, offset, bytesNeeded); of getBytesFromStream.

### Expected Behavior
No OutOfMemoryError and upload large file.

### Error Message, Including Stack Trace
<pre>
java.lang.OutOfMemoryError: Failed to allocate a 33554448 byte allocation with 25165824 free bytes and 28MB until OOM, target footprint 264195968, growth limit 268435456
  at com.box.sdk.LargeFileUpload.getBytesFromStream(LargeFileUpload.java:64)
  at com.box.sdk.LargeFileUpload.uploadParts(LargeFileUpload.java:262)
  at com.box.sdk.LargeFileUpload.uploadHelper(LargeFileUpload.java:198)
  at com.box.sdk.LargeFileUpload.upload(LargeFileUpload.java:124)
  at com.box.sdk.BoxFolder.uploadLargeFile(BoxFolder.java:1191)
</pre>

### Versions Used
Java SDK: 3.8.0, 4.4.1

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by lukaszsocha2** [comment]
Hi @kiyohito-nagano ,
currently the size of the chunk of data to upload is internally determined by the upload service inside Box. API does not allow to specify maximum size of the chunk. In your case, the chunk size was determined by the upload service to 33554448 bytes, as the optimal value, and SDK cannot do anything to change that. 
So in your case I would try to somehow increase available space to over 35MB - not sure if 28MB limit is somehow set in your app settings or it is your device limit. In the meantime I'll reach the team responsible for service to propose  feature, that will allow to specify max chunk size in an API call, but I wouldn't expect that this feature will be introduced soon.
If you have any additional questions, don't hesitate to ask.
Regards,
@lukaszsocha2

**Comment by kiyohito-nagano** [comment]
Hi @lukaszsocha2 Thank you for the reply.
Android AQUOS wish can use 256MB of apps. (This value can be obtained with ActivityManager#getLargeMemoryClass.)
And just before calling uploaduploadLargeFile in the app, it used about 60MB.
After calling uploadLargeFile it goes to 372MB and OutOfMemory just before it crashes.
uploadLargeFile seems to use a large memory (for Android) before allocating the upload data.
It seems that an OutOfMemoryError has occurred in order to allocate a large memory for uploading in that state.

I have one question, if the chunk size is set to 33554448 bytes by the API, will the Box API work correctly if the amount of memory that can be allocated by the application (eg 10MB) is sent?
Or, if 33554448 bytes are required, does it not work well unless 33554448 bytes of data are sent?
Will it work if I reduce the size of BoxFileUploadSession#uploadPart and send it?

**Comment by lukaszsocha2** [comment]
Hi @kiyohito-nagano,
the size of a part has to be exactly the same as one specified by the API. See [documentation of uploadPart endpoint](https://developer.box.com/reference/put-files-upload-sessions-id/#param-content-range):
```Each part’s size must be exactly equal in size to the part size specified in the upload session that you created. One exception is the last part of the file, as this can be smaller.``` So sending smaller parts won't work.
Best,
@lukaszsocha2

**Comment by lukaszsocha2** [comment]
Hi,
the default number od connection (greater than 1) is set to increase speed of upload. There is no way for SDK to check if it will cause OutOfMemoryError before actually executing command. In most cases the error doesn't occur. So in your case I'd suggest to always set nParallelConnections to 1, what will solve your issue, but by default SDK will still use greater value to enhance upload speed.
Best,
@lukaszsocha2

**Comment by kiyohito-nagano** [comment]
Setting nParallelConnections to 100 is likely to cause an OutOfMemoryError when uploading large files(several GB).
Ideally, when an OutOfMemoryError occurs, it should be handled appropriately within the SDK.
As another supplementary information, the problem occurred even in an environment where Android’ｓ ActivityManager#getLargeMemoryClass can handle 512MBalloc.
(if nParallelConnections is default)
In this case, I was able to avoid it by setting android:largeHeap="true" in the Android Manifest.
This matter will be closed. thank you very much.
