### ISSUE TITLE
Cannot programmatically create the Box Custome URL.

### ISSUE THREAD

**Issue by northwizard** [box/box-java-sdk#118]
We are doing migration from Lotus note to Box. There is link on Lotus note document to it's internal files which we plan to move to Box. for the Lotus note document, we convert to be PDF and sent to Box as well. The problem how to create the link in such PDF file to Box. Is there the way that we can set the custome url via some box API such as Java. Then we can use some precise algorithm to set Box Custom URL and also use such in our PDF file.

**Comment by gcurtis** [comment]
Unfortunately, setting a custom shared link URL currently isn't possible with the Box API, therefore we're unable to add this functionality to the SDK.
