### ISSUE TITLE
A JSON parse error occurred for the response of the token acquisition API

### ISSUE THREAD

**Issue by ngctst123** [box/box-java-sdk#1196]
It seems that JSON parsing is being performed for the response of the token acquisition API, 
but an exception has occurred in the parsing process.

Here is the log.
――――――――――――――――――――――――――――
com.eclipsesource.json.ParseException:Expected value at 1:0
com.eclipsesource.json.JsonParser.error(JsonParser.java:371) 
com.eclipsesource.json.JsonParser.expected (JsonParser.java:364)
com .eclipsesource.json.JsonParser.readValue(JsonParser.java:97)
com.eclipsesource.json.JsonParser.parse(JsonParser.java:62)
com.eclipsesource.json.JsonValue.readFrom(JsonValue.java:105)
com.eclipsesource.json.JsonObject.readFrom(JsonObject.java:138)
com.box.sdk.BoxJSONResponse.getJSON (BoxJSONResponse.java:83)
com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:331)
――――――――――――――――――――――――――――

I got the following reply from BOX support.
――――――――――――――――――――――――――――
We checked the server-side log, but since no errors were found, it seems that the error occurred in BOX SDK itself.
If the event recurs, could you please contact us on Github?
――――――――――――――――――――――――――――

Could you please fix it so that the JSON parse error does not occur?

**Comment by lukaszsocha2** [comment]
Hi @ngctst123,
the response of the token acquisition API returns json response, so parsing it is the right behaviour. Can you share your code, which causes this exception? Does this error happen all the time or just from time to time?
Best, 
@lukaszsocha2

**Comment by ngctst123** [comment]
Hi @lukaszsocha2 
It's happening in the SDK and we can't get the code.
It happened on 2023/07/11 02:21（JST）and  2023/07/11 17:35（JST）. Not all the time.
Best regards,

**Comment by lukaszsocha2** [comment]
Hi,
so if it is not happening all the time, then the service behind must have sent invalid json. If this was SDK issue it wouldn't work all the time. Can you please share the part your code, which uses Java SDK causing the exception?
Best, @lukaszsocha2

**Comment by ngctst123** [comment]
Hi,
"★" is the point where the exception is occurred.

~~~~
    BoxDeveloperEditionAPIConnection conn = null;
    if(cache) {
       conn = this.getCachedConnection(key);
       if(conn != null) {
          return conn;
       }
    }
    BoxConfig conf = this.getConfig();
    conn = (BoxDeveloperEditionAPIConnection)this.setProxy(new BoxDeveloperEditionAPIConnection(boxUsrId,     
    DeveloperEditionEntityType.USER, conf, (IAccessTokenCache)null));
    conn.authenticate();  ★
    return !cache?conn:this.setConnection(key, conn);
~~~~~~

**Comment by mwwoda** [comment]
Hello,
For the time being, we have decided to improve the logging of json parsing in case of failure, as we suspect that this problem is caused by the API itself. I have created a task in our backlog to address this (SDK-3313). I will let you know in case of any updates.

**Comment by congminh1254** [comment]
Hi @ngctst123,

Can you let us know which version of Java SDK you are using? From version 3.7.1, with this PR #1106, we added some logging mechanism to better debug this issue.

If you are using older version than this, can you upgrade and when the issue happen again, let us know together with the output log.

Regards,
Minh

**Comment by ngctst123** [comment]
We are using SDK of version 2.23.1, so we try to upgrade the version and watch if the issue happen again.
Thank you.
