### ISSUE TITLE
upgrade bouncy castle

### ISSUE THREAD

**Issue by pjfanning** [box/box-java-sdk#1216]
### Is your feature request related to a problem? Please describe.

https://mvnrepository.com/artifact/com.box/box-java-sdk/4.6.1 has a dependency on bcprov/bcpkix 1.57. This version is very outdated and this is an important security lib to try to keep up to date. 

### Describe the solution you'd like
Ideally bcprov-jdk18on 1.77 would be used (and bcpkix equivalent). bcprov-jdk15on is supported up to v1.70.

**Comment by pjfanning** [comment]
closing due to https://github.com/box/box-java-sdk#fips-140-2-compliance

**Comment by dbielik** [comment]
org.bouncycastle:bc-fips:1.0.2.**4** is out, is there any particular reason sticking to 2.5-years old version?
