### ISSUE TITLE
Find File for Shared Link using BoxDeveloperEditionAPIConnection

### ISSUE THREAD

**Issue by hmousaiti** [box/box-java-sdk#1229]
- [ x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I am using the below code to Find File for Shared Link. The api is an instance of BoxDeveloperEditionAPIConnection. 
However, it is getting me a 404 error. The same code works fine if the api is an instance of box user connection not an app user connection
String sharedLink = "https://app.box.com/s/abcdefghijklmnopqrstuvwxyz123456";
BoxItem.Info itemInfo = BoxItem.getSharedItem(api, sharedLink);

### Expected Behavior
I can get the file info

### Versions Used
Java SDK: 3.3.0
Java: 

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by mwwoda** [comment]
Hello,

First, please try to update Java SDK used, as the major version used by you was released more than two years ago and is no longer supported - see https://github.com/box/box-java-sdk?tab=readme-ov-file#version-schedule

This looks like some kind of permissions/access problem. With what permissions was the shared link created? Also check the enterprise settings for the shared link, as they may affect the shared link itself.

Could you provide a reproducible sample so we can try to reproduce it on our side? Of course, don't provide any personal information or credentials.
