### ISSUE TITLE
Event Stream default stream position value is incorrect

### ISSUE THREAD

**Issue by 6abe** [box/box-java-sdk#123]
Shouldn't the EventStream.java STREAM_POSITION_NOW be set to 0 and not -1 per Box documentation?

https://developers.box.com/docs/#events

**Comment by gcurtis** [comment]
Hey @6abe,

The code around this is a little unintuitive. The -1 value is only used by the SDK as an indicator that "now" should be sent for the stream position (you can this in the code [here](https://github.com/box/box-java-sdk/blob/8351d5743e4a5317459c09c4a2001947636b300f/src/main/java/com/box/sdk/EventStream.java#L96-L97)).

The API also treats 0 differently from "now" and will return different events:

> If you send *now* then you will get exactly zero events, and the latest *stream_position*. If you do not send in a *stream_position*, we default to 0, so you will get a list of all the events that we have in our event cache for your account.

**Comment by 6abe** [comment]
I see. Thanks for the clarification Greg!
