### ISSUE TITLE
After the version upgrade, I am getting a NullPointerException when trying to read an empty file.

### ISSUE THREAD

**Issue by balram0694** [box/box-java-sdk#1230]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).

### Description of the Issue
When I upgraded to the latest Box SDK version 4.7.0, the BoxFile(BoxAPIConnection api, String id).download(OutputStream output) method is throwing a NullPointerException when reading an empty file or a zero-byte file. However, the same file, when read with Box SDK version 3.8.2 or a previous version, worked as expected.

### Steps to Reproduce

1.Copy the code below and paste it into your IDE.

      String accessToken = "********************";
        BoxAPIConnection api = new BoxAPIConnection(accessToken);
        String fileId = " ************ ";
        String path = "/tmp/boxread.txt";
        try {
           
            BoxFile.Info boxFileInfo = new BoxFile(api, fileId).getInfo();

            // Create an output stream to save the file locally
            try (OutputStream stream = new FileOutputStream(path)) {
                boxFileInfo.getResource().download(stream);

                System.out.println("File downloaded successfully.");
            }
        } catch (IOException | BoxAPIException e) {
            e.printStackTrace();
        }

2.Replace **accessToken**, **fileId** (select a file that is empty or 0 bytes), and **path** with their original values.
3.First, use box-java-sdk version 3.8.0 or a previous version. When running the above code, it reads an empty file and does not throw any exceptions.
4. Use the box-java-sdk version 4.7.0, run the above code; it throws a NullPointerException (NPE).

**Note:** This issue is occurring only when we read an empty file. When we read a file that contains any data, it is working as expected.

### Expected Behavior
It reads an empty file as it did in the previous version 3.8.0 or earlier.

### Error Message, Including Stack Trace

Exception in thread "main" java.lang.NullPointerException
	at com.box.sdk.BinaryBodyUtils.writeStreamTo(BinaryBodyUtils.java:67)
	at com.box.sdk.BinaryBodyUtils.writeStream(BinaryBodyUtils.java:43)
	at com.box.sdk.BoxFile.download(BoxFile.java:311)
	at com.box.sdk.BoxFile.download(BoxFile.java:298)
	at com.example.demo11.BoxReader.main(BoxReader.java:23)

### Screenshots

![Screenshot from 2024-01-31 13-17-13](https://github.com/box/box-java-sdk/assets/60089832/d2b6cc9c-3a0d-43ba-8764-a2de89e59eb3)

### Versions Used
Java SDK: 4.7.0
Java: 11.0.21

**Comment by mwwoda** [comment]
Thanks for reporting the issue. Fix should be included in the next release.

**Comment by balram0694** [comment]
Thank you for your prompt response.
