### ISSUE TITLE
Box Resend Functionality - 411 Content Length Error

### ISSUE THREAD

**Issue by spatnaik-pwc** [box/box-java-sdk#1264]
![image](https://github.com/user-attachments/assets/e48aa1bd-055a-40c9-bced-f0fc792a6399)

**Comment by spatnaik-pwc** [comment]
The image links mayn't have been inserted successfully. PFB the images for headers:

Postman Auto generated headers:
![image](https://github.com/user-attachments/assets/9dacbc62-06bd-4da2-880f-e931bacc13f8)

Box SDK headers through Guidewire:
![image](https://github.com/user-attachments/assets/48c94cdf-3ed6-4a4e-82dd-7fd801c557a6)

In case of SDK generated headers content-length and few others headers are missing. Please advise.

**Comment by spatnaik-pwc** [comment]
Session with box 

[Support from Box needed - eSign Resend is not working-20240827_123410-Meeting Recording.mp4](https://txfbinsurance.sharepoint.com/:v:/t/PolicyAdminSystemReview2/EVu3SoVb6e1LoUguf8gwDggBIxd25RxZUisIE8_gnBhtTw?e=4cbNwE&xsdata=MDV8MDJ8fDYxMmVkMDA1MzY1NDRkMDgyZjM3MDhkY2M2YzFhNTg5fDUxMzI5NGEwM2UyMDQxYjJhOTcwNmQzMGJmMTU0NmZhfDB8MHw2Mzg2MDM3ODIxODc5ODY3NDN8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPamt5TnpKak5UazVMV016T1dRdE5EVTRPQzFoWWpFM0xUWm1ZbUV6TW1NMFl6azNNbDlqTURNMFpETTNOUzFqWTJabExUUTVOemN0T1dJell5MDBPRGRrTlRWaE5HUXpNbU5BZFc1eExtZGliQzV6Y0dGalpYTXZiV1Z6YzJGblpYTXZNVGN5TkRjNE1UUXhPRFEyT0E9PXxmYjA0YzZlMTRiMjE0ZWFhMmYzNzA4ZGNjNmMxYTU4OXwxYjg1MGJiZDdhZTg0MTNlOWEzNGMyZTRlMDkyOTU2MQ%3D%3D&sdata=a3VDLzFJelVhSGNVNUVWS1ZvL01USE1pRStJeXFvb3E0c08zSE05MmZ4WT0%3D&ovuser=513294a0-3e20-41b2-a970-6d30bf1546fa%2Csatyabrata.patnaik%40pwc.com)

**Comment by congminh1254** [comment]
Hi @spatnaik-pwc 

We can reproduce this issue in SDK version 3.8.2, but it was fixed from version 4.0.0. So please consider upgrading the SDK to have the latest bug fixes and features.

If you have any difficulty during the upgrade process, let us know. 

Bests,
Minh

**Comment by spatnaik-pwc** [comment]
I am currently working on upgrading the SDK. Will keep you posted once we have done the testing on our side.

**Comment by congminh1254** [comment]
Happy to hear that, we are looking forward to hearing from you.

**Comment by spatnaik-pwc** [comment]
@congminh1254 this has been resolved. Thank you for your assistance on this matter.
