### ISSUE TITLE
BOX API

### ISSUE THREAD

**Issue by arpithahmlexisnexis** [box/box-java-sdk#127]
Hi,

Iam trying to implement cloud delivery using BOX API's. For supporting this i have downloaded box-java-sdk-1.0.0 and trying to use API's of this jar. But you have no where explained how to use this SDK. you have created your own java classes and using same in example. Can you please help me out doing it.

Thanks,
Arpitha H M

**Comment by gcurtis** [comment]
You can find the documentation on [our website](http://opensource.box.com/box-java-sdk/) as well as in the `doc` directory.
