### ISSUE TITLE
Allow to modify the underlying okHttpClient from the BoxDeveloperEditionAPIConnection when using factory method

### ISSUE THREAD

**Issue by davigotxi** [box/box-java-sdk#1271]
The BoxApiConnection class has a protected method [modifyHttpClientBuilder](https://github.com/box/box-java-sdk/blob/main/src/main/java/com/box/sdk/BoxAPIConnection.java#L253) that allows to modify the underlying okHttpClient by overriding the method from a subclass. This is useful for a variety of reasons (i.e. on our particular case to add some logging interceptors to debug what is going on at different stages of an http request).

When trying to extend the [BoxDeveloperEditionAPIConnection](https://github.com/box/box-java-sdk/blob/main/src/main/java/com/box/sdk/BoxDeveloperEditionAPIConnection.java) subclass to preserve behavior we want to use one of the getAppEnterpriseConnection methods that internally using a private method tryRestoreUsingAccessTokenCache. However we cannot call this method unless using reflection.

A nicer solution would be to have that method as public or protected.

**Comment by congminh1254** [comment]
Hi @davigotxi 

Have you tried something like this:

```
public class ModifiedBoxDeveloperEditionAPIConnection extends BoxDeveloperEditionAPIConnection {

    // Initialize class

    /**
     * {@inheritDoc}
     */
    @Override
    protected OkHttpClient.Builder modifyHttpClientBuilder(OkHttpClient.Builder httpClientBuilder) {
        return super.modifyHttpClientBuilder(httpClientBuilder);
    }
}
```

Bests,
Minh

**Comment by davigotxi** [comment]
> Hi @davigotxi
> 
> Have you tried something like this:
> 
> ```
> public class ModifiedBoxDeveloperEditionAPIConnection extends BoxDeveloperEditionAPIConnection {
> 
>     // Initialize class
> 
>     /**
>      * {@inheritDoc}
>      */
>     @Override
>     protected OkHttpClient.Builder modifyHttpClientBuilder(OkHttpClient.Builder httpClientBuilder) {
>         return super.modifyHttpClientBuilder(httpClientBuilder);
>     }
> }
> ```
> 
> Bests, Minh

Hi Minh,
thanks for that. Actually you are right, overriding the modifyHttpClientBuilder works; it is another private method we are having an issue with:
```
public class DxrBoxApiConnection extends BoxDeveloperEditionAPIConnection {

  public DxrBoxApiConnection(String entityId, DeveloperEditionEntityType entityType, String clientID,
      String clientSecret,
      JWTEncryptionPreferences encryptionPref, IAccessTokenCache accessTokenCache) {
    super(entityId, entityType, clientID, clientSecret, encryptionPref, accessTokenCache);
  }

  public static DxrBoxApiConnection getAppEnterpriseConnection(
      String enterpriseId,
      String clientId,
      String clientSecret,
      JWTEncryptionPreferences encryptionPref,
      IAccessTokenCache accessTokenCache
  ) {
    var connection = new DxrBoxApiConnection(enterpriseId,
        DeveloperEditionEntityType.ENTERPRISE, clientId, clientSecret, encryptionPref, accessTokenCache);
    connection.tryRestoreUsingAccessTokenCache();
    return connection;
  }

  @Override
  protected OkHttpClient.Builder modifyHttpClientBuilder(OkHttpClient.Builder httpClientBuilder) {
    var builder = super.modifyHttpClientBuilder(httpClientBuilder);
    builder.addInterceptor(c -> {
      //do something
      return c.proceed(c.request());
    });
    return builder;
  }

}
```
the actual problem is with tryRestoreUsingAccessTokenCache that is private.

Silly me I was submitting this at last hour of my day and and got it backwards.

Let me re-do the issue

**Comment by congminh1254** [comment]
Hi @davigotxi 

Do you need anything else other than Interceptor? We already provided a method named `api.setRequestInterceptor` for this purpose.

Can you take a look and reuse this function?

**Comment by davigotxi** [comment]
hi @congminh1254 
thanks for your answer, the setRequestInterceptor indeed is useful:
```
Sets a RequestInterceptor that can intercept requests and manipulate them before they're sent to the Box API.
Params:
interceptor – the RequestInterceptor.
```
however it is limited on its scope. Even though I gave the example of a logging interceptor, I'm also interested on [network interceptors](https://square.github.io/okhttp/features/interceptors/#choosing-between-application-and-network-interceptors) and application responses

**Comment by congminh1254** [comment]
Hi @davigotxi 

I merged your changes to the main branch, and it should be included in the next Java SDK release.

Bests,
Minh

**Comment by davigotxi** [comment]
Thanks! Should we close this?

**Comment by congminh1254** [comment]
This ticket can be closed for now, we will let you know when the new version released.
