### ISSUE TITLE
Add setter for tags

### ISSUE THREAD

**Issue by gcurtis** [box/box-java-sdk#129]
A setter should be added to `BoxItem.Info` so that tags can be updated.

**Comment by raj-jain** [comment]
This will be helpful. I've had to do the following outside the SDK:

* add tag(s)
* update tag(s)
* remove tag(s)

It'll be nice to support all CRUD operations on tags (the 'R' using getTags() works just fine).

**Comment by gcurtis** [comment]
We may not end up adding this to the SDK since the API will be deprecating the tags field in the near future. You should be able to use metadata instead, which provides a much more powerful way of tagging content.

**Comment by raj-jain** [comment]
Ok. I guess the metadata capability will then be made available to "business" level accounts. I tried to use metadata first, but then realized it is only available for "enterprise" level accounts, so I had to resort to tags. I'd like my app to be usable by both "business" and "enterprise" level accounts.

**Comment by pflory** [comment]
Hi @raj-jain, could you kindly share the code for adding/updating/removing tags? It's not clear from the SDK docs, samples, test cases.  

@gcurtis, I am working with an enterprise client that _heavily_ relies upon tags for their site and mobile app. Do you have more info about the deprecation (timelines, etc.) and migration strategies to replace them?

**Comment by raj-jain** [comment]
I basically used BoxAPIRequest and BoxAPIResponse objects. I've extracted some snippets of code from my app. Below is a mix of some actual and pseudo code with some instructions. Hope this helps.	
		
1. Create a URL object for the file. Below is a utility function. You input the file id of the file for which tags are being manipulated.
		
import java.net.MalformedURLException;
import java.net.URL;
...
public static URL createFileUrl(String fileId)
{
	// Hard-coded the URL in the example below, but a production 
	// implementation should make this configurable.
	StringBuilder fileUrlBuilder = new StringBuilder(
		"https://api.box.com/2.0/files");
	fileUrlBuilder.append(fileId);

	URL fileUrl = null;
	try {
		fileUrl = new URL(fileUrlBuilder.toString());
	}
	catch (MalformedURLException excObj) {
		// Handle the exception
	}
	return fileUrl;
}
		
URL fileUrl = YourClassName.createFileUrl(file.getId());

		
2. Create an authenticated BoxAPIRequest object using the following constructor:
		
BoxAPIRequest(BoxAPIConnection api, URL url, String method)
			
// Create API request object
BoxAPIRequest request = new BoxAPIRequest(
                yourApiConnObj, // you got this when you created BoxAPIConnection
                fileUrl,
                "PUT");
			
3. Create the JSON request body. The request is created as a string here but you could use minimal-json's JSON creation facilities.

// Example file tags update JSON request --
// {"tags":"a, b, c, d"}
StringBuilder jsonStrBuilder = new StringBuilder("{\"tags\": \"");
			
// A list of tags is populated in tagsList. Note that if you are adding a tag to a list of existing tags or 
// deleting an existing tag you'll retrieve the file's current tags first and create tagsList accordingly.

for (String tag : tagsList) {
	jsonStrBuilder.append(tag).append(", ");
}
jsonStrBuilder.deleteCharAt(jsonStrBuilder.length() - 1);
jsonStrBuilder.append("\"}");
			
4. Populate the JSON payload in the request object. Send the request.

request.setBody(jsonStrBuilder.toString());
BoxAPIResponse response = request.send();	

// Handle the response. Handle exception if there is an error.
...
response.disconnect();

**Comment by pflory** [comment]
Thanks for the quick feedback, raj-jain!

Our team also received similar info from Box Support, shown below. I haven't had time to try any of these ideas out, but have confidence now that it will work.

From Support:
________________
As far as using the SDK to make the calls, you should be able to accomplish this by using the BoxAPIRequest object with your own parameters.
https://github.com/box/box-java-sdk/blob/1b22f8cdb851128d10a40ace7332aac75e8d0ac6/src/main/java/com/box/sdk/BoxJSONRequest.java
It would look something like this (consider this pseudo code, as I have not been able to test the request currently)
BoxAPIConnection api = new BoxAPIConnection("DEV_TOKEN");

URL url = new URL("https://api.box.com/2.0/files/FILE_ID")
String update = "{\"tags\":[\"test\",\"test2\",\"test3\"]}"

BoxAPIRequest request = new BoxAPIRequest(api, url, "PUT"); 
request.setBody(update);

BoxJSONResponse response = (BoxJSONResponse) request.send();

**Comment by dayasagar** [comment]
Abe to set the tags for documents in box with above code. @pflory Thanks for simple example.

**Comment by tarrencev** [comment]
Closing since tags are being deprecated.Going forward Metadata should be used instead.
