### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by gcurtis** [box/box-java-sdk#13]
Add a new search method that takes a `SearchOptions` object that allows for setting all the advanced query parameters accepted by the API.

**Comment by jdgiotta** [comment]
@gcurtis in the integration tests, what is the collaboratorID and how do I obtain it?

**Comment by jdgiotta** [comment]
I've committed a search overload to allow for content_type options, but I can't seem to get integration tests to function. My only form of validation was through additional calls made in the example program.

**Comment by gcurtis** [comment]
@jdgiotta collaboratorID is the ID of another user that will be used when testing collaborations. A user's ID can be found in [their profile settings](https://cloud.app.box.com/settings/profile).

Unfortunately, integration tests are pretty difficult to run because:

1. an enterprise account is required to run all of the tests.
2. you need to manually provide an access and refresh token before each test run.

We're working toward increasing pure unit test coverage by using request interceptors to assert that the correct HTTP requests are being sent. These should be easier to run instead of integration tests.

**Comment by jdgiotta** [comment]
@gcurtis yeah, I just discovered the problem with tokens. Luckily I can obtain new ones fairly easily, Also, I do have an enterprise account and I was able to get most of the tests to run/pass with the exception of download tests, but I think it's a matter of resource configuration on my local project. I'll see if I can't get new integration tests in place before a pull request.

**Comment by jdgiotta** [comment]
Based on my tests, I'm assuming search indexing is delayed.

**Comment by TLuthra** [comment]
Yup, according to Box support, search indexing is a little bit delayed.

https://support.box.com/hc/en-us/articles/202857256-Search-Overview-and-FAQs#search_hdsiw

**Comment by jdgiotta** [comment]
Thanks, @TLuthra Makes for a difficult integration test. I could isolate the test and sleep for 10 minutes LOL

**Comment by jdgiotta** [comment]
Writing an integration test for search is problematic. I can see why one was left out originally.

I isolated my test with a 6 minute sleep, but I took liberty of adding a new task to the Gradle tasks and creating an "IsolatedIntegrationTest" category. I'd hate to fork too greatly in this area.

**Comment by jdgiotta** [comment]
I did not include my tests in this pull requests. I felt the 6 to 10 minute pause would lead to an unwanted experience. If requested, I will include them.

**Comment by gcurtis** [comment]
Yeah, that integration test would take way too long to run and probably be really flakey. I think that we can unit test this though using a `RequestInterceptor`. There's an example of how to use one in the [`createEnterpriseUserSendsJSONWithLoginAndName`](https://github.com/box/box-java-sdk/blob/46b1291e5b64c9ea4747c1ba979a192f9b71cd5b/src/test/java/com/box/sdk/BoxUserTest.java#L67) test.

We can assert that the correct query parameters are set within the `onJSONRequest` callback

**Comment by tarrencev** [comment]
Closed by#239
