### ISSUE TITLE
Search pagination

### ISSUE THREAD

**Issue by itaisoudry** [box/box-java-sdk#130]
If I search on the root folder, using rootFolder.search(), I get only maximum 200 results, while with the REST api I get much more...
I use the query for example "0 1 2 3 4 5 6 7 8 9" to search for the file id's that contains one of these numbers (supposedly most of them ), and I get 200 results while in the REST I get around 400+-.

**Comment by tarrencev** [comment]
Hi @itaisoudry, please see the new advanced search functionality, documented in this example https://github.com/box/box-java-sdk/blob/master/src/example/java/com/box/sdk/example/SearchExamplesAsAppUser.java
