### ISSUE TITLE
Unable to pull enterprise events

### ISSUE THREAD

**Issue by sumalkar** [box/box-java-sdk#131]
created_after is beyond one year in the past, API only supports time range starting from one year in the past from now.

Getting the above error irrespective of whatever dates I entered. Even tried with current date as start and end dates, still the same error.

Here's the sample code that I am trying-

        TimeZone tz = TimeZone.getTimeZone("UTC");
        Calendar start = Calendar.getInstance(tz);
        start.add(Calendar.MONTH, -1); // retrieve events for last one month
        Calendar end = Calendar.getInstance(tz);

        try {
            EventLog el = EventLog.getEnterpriseEvents(api, start.getTime(), end.getTime(), BoxEvent.Type.values());
            System.out.println("Total- " + el.getSize());
            for (Iterator<BoxEvent> iterator = el.iterator(); iterator.hasNext();) {
                System.out.println(iterator.next().toString());
            }
        } catch (BoxAPIException ex) {
            ex.printStackTrace();
            System.out.println(ex.getResponse());
        }

And the actual error that I am getting-

{"type":"error","status":400,"code":"bad_request","help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"created_after is beyond one year in the past, API only supports time range starting from one year in the past from now","request_id":"310879445579d0cc0fd33"}

**Comment by itsmanishagarwal** [comment]
I also hit this issue today. And it is happening because the SDK does not encode the formatted date. So, whenever there is a '+' in the formatted date it fails with above mentioned error. And all Timezones which are ahead of UTC including UTC has sign as "+".

The fix should be simple, the code should encode the formatted dates before making the API call.

**Comment by tarrencev** [comment]
Closing in lieu of #198
