### ISSUE TITLE
Support for Enterprise/Admin Events

### ISSUE THREAD

**Issue by raj-jain** [box/box-java-sdk#134]
The EventStream class is currently documented as that it supports Enterprise events:

"..This class handles long polling the Box events endpoint in order to receive real-time user or enterprise events..."

However, there are a few differences between User and Enterprise events and my testing shows that this class does not necessarily support Enterprise events currently.

Unlike User events, Enterprise events use an integer for stream_position not a string. The magic string value of "now" for this URI parameter is not supported for Enterprise events. The stream_type needs to be set as "admin_logs. The JSON GET response for Enterprise events contains next_stream_position as an integer so, the following line (line #100) in EventStream fails:

initialPosition = jsonObject.get("next_stream_position").asLong();

![image](https://cloud.githubusercontent.com/assets/12472659/8266937/b4625688-1716-11e5-92f1-389a75ebc5ce.png)

Could I be missing something? Otherwise, if we agree upon this current limitation, perhaps we can discuss what's the best way to introduce Enterprise events functionality to this class (or to a separate derivative class).

**Comment by gcurtis** [comment]
Yeah, this is an issue with the documentation. The API currently doesn't offer long polling of enterprise events, so they aren't supported via `EventStream`.

You can still retrieve enterprise events via [`EventLog`](http://opensource.box.com/box-java-sdk/javadoc/com/box/sdk/EventLog.html#getEnterpriseEvents(com.box.sdk.BoxAPIConnection,%20java.util.Date,%20java.util.Date,%20com.box.sdk.BoxEvent.Type...)) - just not in real-time.

**Comment by raj-jain** [comment]
Thanks. Yes, EventLog class SDK works just fine for its purpose (fetching historical events). However, unfortunately, the Box Content API response for such requests does not return the current stream position (in the example below, the created_before time is the current time and the created_after time is one second less than that):

https://api.box.com/2.0/events?limit=500&stream_type=admin_logs&created_after=2015-06-19T12:47:25-06:00&created_before=2015-06-19T12:47:26-06:00

{"chunk_size":0,"next_stream_position":"0","entries":[]}

The next_stream_position is returned as "0", which means that we can't use that value and start long-polling of enterprise event based on the current stream position.

Could you pls. clarify that you meant that the Box Content API currently does not offer long-polling of Enterprise events? And, thus lack of that functionality in EventStream class (i.e. it doesn't make sense to develop this in the SDK if the underlying API doesn't support it)? 

The Content-API documentation mentions the following example for Enterprise events where the response comes back with the proper next_stream_position:

https://api.box.com/2.0/events?stream_type=admin_logs&limit=3&stream_position=28893260

{
    "chunk_size": 3,
    "next_stream_position": "28893355",
...

So, if one knew the stream_position which is equivalent to "now" (of User events), then one can start long-polling for enterprise events, right?

Any ideas how we can get the current stream_position for Enterprise events?

**Comment by raj-jain** [comment]
Ok. I've confirmation from Box support that long-polling and "now" semantics (i.e. getting stream_position corresponding to the current time) are not supported for Enterprise events.

I've implemented an EventLogStream class which basically gives me EventStream behavior on top of EventLog. I'll describe its implementation in a separate thread.
