### ISSUE TITLE
Add ability to set non-global proxy

### ISSUE THREAD

**Issue by gcurtis** [box/box-java-sdk#136]
Right now, the only way to set a proxy with the SDK is via the `https.proxyHost` and `https.proxyPort` system properties. This is problematic for applications that can't or don't want to use a proxy for all HTTP requests.

Instead, we can use the [`URL.openConection(Proxy)`](http://docs.oracle.com/javase/7/docs/api/java/net/URL.html#openConnection(java.net.Proxy)) method to allow for a proxy to be set only for HTTP requests sent from the SDK.

Getters and setters should be added to `BoxAPIConnection` which allow for the proxy to be configured.

```java
public class BoxAPIConnection {
    // ...

    // Sets a proxy to use when making requests to the API.
    public void setProxy(Proxy proxy) { ... }

    // Sets an authenticated proxy to use when making requests to the API.
    public void setProxy(Proxy proxy, String username, String password) { ... }

    // Gets the proxy that will be used when making requests to the API.
    public Proxy getProxy() { ... }
}
```

**Comment by pflory** [comment]
+1 !

You beat me to it. An enterprise client I am working with has the same requirement, and I was about to submit an issue/feature request just now. As a short-term fix to get it working we did following, but support in the API would be greatly welcomed!

In the class that is using the Box SDK/API, we have:

						Authenticator authenticator = new Authenticator() {
							public PasswordAuthentication getPasswordAuthentication() {
								return (new PasswordAuthentication(user, pass.toCharArray()));
							}
						};
						Authenticator.setDefault(authenticator);

In BoxAPIRequest we slightly tweaked to check if proxy is set at System level:

            String proxyHost = System.getProperty("http.proxyHost");
            String proxyPort = System.getProperty("http.proxyPort");
            if ((proxyHost != null)  && (proxyPort !=null)){
            	Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, Integer.parseInt(proxyPort)));
                connection = (HttpURLConnection) this.url.openConnection(proxy);
            } else {
            	connection = (HttpURLConnection) this.url.openConnection();
            }
