### ISSUE TITLE
Streaming over Enterprise Events Log -- EventLogStream

### ISSUE THREAD

**Issue by raj-jain** [box/box-java-sdk#137]
We needed a mechanism for asynchronous event reception for Enterprise events. We realized that long-polling is not supported for Enterprise events. We also needed "now" magic string semantics and the ability to be notified of enterprise events asynchronously.

We've built this in the SDK. One could argue that it could have been built in the app, but we figured it belonged in the SDK. 

We created an EventLogStream class which is derived from EventStream. The class basically spawns a poller thread and pulls events down periodically using EventLog class. The event callback mechanism works as before. The polling frequency is passed in as a constructor argument. The stream_position is derived automatically giving us the "now" semantics.

Does this capability make sense in the SDK? I'd be happy to contribute this code if there is interest.

**Comment by jgoldhammer** [comment]
I would be very happy to see this in the SDK. Can you share code?

**Comment by carycheng** [comment]
Hey @jgoldhammer, 

Enterprise Events Log is on our roadmap for this quarter. We will let you know as soon as this feature is ready. 

Thank you!

**Comment by antusus** [comment]
Hello @raj-jain ,

we have added some new ways of getting Events, you can read about them [here](https://github.com/box/box-java-sdk/blob/v3.0.0/doc/events.md).

We would love to hear your ideas, and you can share code by submitting pull requests.

I'm closing the issue for now.
