### ISSUE TITLE
Any exception thrown in BoxAPIConnectionListener will keep 'refreshLock.writeLock()' locked

### ISSUE THREAD

**Issue by marco-primiceri** [box/box-java-sdk#140]
Issue discovered with @JordanBright.
When [notifying an error](https://github.com/box/box-java-sdk/blob/142c574787ea2e8a3c10303190b2684b815bd975/src/main/java/com/box/sdk/BoxAPIConnection.java#L446) or [notifying a refresh](https://github.com/box/box-java-sdk/blob/142c574787ea2e8a3c10303190b2684b815bd975/src/main/java/com/box/sdk/BoxAPIConnection.java#L457) in the OAuth refresh method if a listener throws an exception then it will prevent the execution of `this.refreshLock.writeLock().unlock()` leaving the writeLock locked indefinitely.

**Comment by JordanBright** [comment]
Wait, just noticed https://github.com/box/box-java-sdk/blob/142c574787ea2e8a3c10303190b2684b815bd975/src/main/java/com/box/sdk/BoxAPIConnection.java#L254

In that case aren't all the locks and unlocks in `refresh()` unnecessary?

**Comment by mattwiller** [comment]
Thanks for the investigate @marco-primiceri and @JordanBright!  Yeah, it looks like this is taken care of by the `finally` after `refresh()`.  The unlocks are somewhat unnecessary in that case — I've added an item to our backlog to clean this up in the future.
