### ISSUE TITLE
RFE: Add getLogin() method to BoxCollaborator.Info

### ISSUE THREAD

**Issue by luyseyal** [box/box-java-sdk#146]
According to the [API documentation](https://developers.box.com/docs/#collaborations-retrieve-a-collaboration), the following fields are available in `accessible_by` returned by the collaboration service:
```
"accessible_by": {
        "type": "user",
        "id": "18203124",
        "name": "sean",
        "login": "sean+test@box.com"
    },
```

The `getName()` method already exists in BoxCollaborator.Info. This is to request adding `getLogin()`.

If there is a workaround for this, I'd love to hear about it.

Thank you,

Stephen Olander-Waters
Enterprise Applications Architect
St. Edward's University
stephenw@stedwards.edu

**Comment by gcurtis** [comment]
Hey @luyseyal, the `getAccessibleBy()` method returns a `BoxCollaborator.Info` which can be either a user info or a group info. Since only BoxUsers have a login field, you'll need to check the info's type and cast it. For example:

```java
BoxCollaborator.Info info = myCollabInfo.getAccessibleBy();
if (info instanceof BoxUser.Info) {
    BoxUser.Info userInfo = (BoxUser.Info) info;
    String login = userInfo.getLogin();
}
```

**Comment by luyseyal** [comment]
Gotcha. Thanks. Are collisions possible between the Group and User IDs? (I.e., must I always check the instanceof if I'm only comparing getID() to getID()?)

**Comment by gcurtis** [comment]
Collisions are indeed possible. IDs are only guaranteed to be unique within the scope of their type.
