### ISSUE TITLE
Support "Move User's Folder" functionality

### ISSUE THREAD

**Issue by mcmilwj** [box/box-java-sdk#156]
I needed the functionality described here:

https://box-content.readme.io/reference#move-folder-into-another-users-folder

And the v1.0.0 jar of this SDK I was using did not include support for it, so I added it. I would like to contribute this change back to the project for potential inclusion in a future release. Its just a single method implementation about 12 lines long, and one additional static field for the corresponding `URLTemplate`.

Please advise.

**Comment by gcurtis** [comment]
That sounds good to me! Make a pull request and I'll take a look.
