### ISSUE TITLE
New release planned?

### ISSUE THREAD

**Issue by timvossen-rec** [box/box-java-sdk#166]
Are there any plans (or an ETA) for a new release?
Specifically, the support for tasks (#115) is of interest to us.

**Comment by luyseyal** [comment]
We are highly interested in the AppAuth/AppUsers code being officially released.

**Comment by gcurtis** [comment]
Sorry, but we don't have a precise release date for the next release. We still want to do some cleanup/improvements around AppAuth before officially release it.

In the mean time, there is a snapshot release which you can grab here - https://oss.sonatype.org/content/repositories/snapshots/com/box/box-java-sdk/1.2.0-SNAPSHOT/

**Comment by daveqr** [comment]
I am also interested in AppAuth/AppUsers.
