### ISSUE TITLE
Can't delete a version

### ISSUE THREAD

**Issue by jcable** [box/box-java-sdk#167]
Using 1.1.0 with a developer token:

``` java
List<BoxFileVersion> vs = new ArrayList<BoxFileVersion>(f.getVersions());
for (int i = vs.size()-1; i>2; i--) {
    BoxFileVersion v = vs.get(i);
    System.out.format("file %d created at %s\n", i, v.getCreatedAt());
    v.delete();
}
```

prints:

```
file 232 created at Wed Jun 24 14:49:02 UTC 2015
com.box.sdk.BoxAPIException: The API returned an error code: 400
        at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:69)
        at com.box.sdk.BoxJSONResponse.<init>(BoxJSONResponse.java:30)
        at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:414)
        at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:200)
        at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:175)
        at com.box.sdk.BoxFileVersion.delete(BoxFileVersion.java:139)
        at App$1.run(App.java:56)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by gcurtis** [comment]
This sounds like it might be a bug. Can you do me a favor and paste the contents of [`exception.getResponse()`][1]?

[1]: http://opensource.box.com/box-java-sdk/javadoc/com/box/sdk/BoxAPIException.html#getResponse()

**Comment by jcable** [comment]
This is one:

    {"type":"error","status":400,"code":"bad_request","context_info":{"errors":[{"reason":"invalid_parameter","name":"file_version_id","message":"Invalid value '31466138243'."}]},"help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"Bad Request","request_id":"53375886564aeb9683c3b"}

This is the code:

            public void run() {
                BoxFile f = new BoxFile(api, fileid);
                int n = 0;
                try {
                    List<BoxFileVersion> vs = new ArrayList<BoxFileVersion>(f.getVersions());
                    for (int i = vs.size()-1; i>2; i--) {
                        BoxFileVersion v = vs.get(i);
                        System.out.format("file %d created at %s\n", i, v.getCreatedAt());
                        System.out.format("delete\n");
                        v.delete();
                    }
                } catch (BoxAPIException e) {
                    e.printStackTrace();
                    System.out.println(e.getResponse());
                }
            }
