### ISSUE TITLE
Retention Management capabilities

### ISSUE THREAD

**Issue by tcharles79** [box/box-java-sdk#170]
Provide options to create Retention Policies and Retention Policy assignments through SDK. Thanks.

**Comment by tcharles79** [comment]
I wrote the code for Retention Capabilities. Checkout the attached code.

[sdk.zip](https://github.com/box/box-java-sdk/files/99807/sdk.zip)

**Comment by tarrencev** [comment]
Hi @tcharles79, thanks for the ticket, we do plan on adding this functionality in the near-term.

If you would like to contribute your implementation, please open a Pull Request :) Thanks!
