### ISSUE TITLE
java.lang.UnsupportedOperationException when parsing created_by of enterprise event

### ISSUE THREAD

**Issue by danielandefors** [box/box-java-sdk#189]
The error occurs when parsing the `created_by` member, if the event creator is unknown. (Not sure why it would be unknown, but that's a different story.) 

When the `created_by` object looks like:

```
 {"type":"user","id":null,"name":"Unknown User","login":null}
```

The code throws the exception:

```
java.lang.UnsupportedOperationException: Not a string: null
	at com.eclipsesource.json.JsonValue.asString(JsonValue.java:365)
	at com.box.sdk.BoxResource.parseInfo(BoxResource.java:27)
	at com.box.sdk.BoxEvent.parseJsonMember(BoxEvent.java:182)
	at com.box.sdk.BoxEvent.<init>(BoxEvent.java:41)
	at com.box.sdk.EventLog.<init>(EventLog.java:44)
	at com.box.sdk.EventLog.getEnterpriseEvents(EventLog.java:104)
```

**Comment by danielandefors** [comment]
I'm not sure what the best way to fix the issue is. The easiest way is probably to change the parsing logic in `BoxResource.parseInfo` to check if `id` is null and treat it accordingly. What I don't know is if that will cause any unwanted side effects elsewhere, e.g., because the `id` is null.

**Comment by gcurtis** [comment]
Thanks @danielandefors. This looks like it might be an API issue. It seems weird to have a user object with a null ID instead of just setting the `created_by` field itself to null.

What was the ID of the event that generated this exception? Do you also remember the approximate time that the API request was made? That might help us track down where this happened.

**Comment by danielandefors** [comment]
Hey. I made the API request today while I was testing some functionality of an integration that I'm building. I tested against my own developer account when I ran into the issue. It is a download event from a couple months ago. The file that was downloaded is in a folder with collaborators, and I assume it was one of them that downloaded the file, but that's just a guess.

Here's the event data:

```
{
   "source":{
      "item_type":"file",
      "item_id":"38059389242",
      "item_name":"setup.pkg.zip",
      "parent":{
         "type":"folder",
         "name":"Ai Plugin CC 2015",
         "id":"4656300138"
      }
   },
   "created_by":{
      "type":"user",
      "id":null,
      "name":"Unknown User",
      "login":null
   },
   "created_at":"2015-09-22T09:43:46-07:00",
   "event_id":"e769a522-bbab-4863-8959-13b6bb88edee_847736803",
   "event_type":"DOWNLOAD",
   "ip_address":"xxx.xxx.xxx.xxx",
   "type":"event",
   "session_id":null,
   "additional_details":{
      "version_id":"37812767014"
   }
}
```
(IP address redacted.)

**Comment by danielandefors** [comment]
Additionally, I tested some code about two weeks ago that gets the `version_id` from `additional_details`. At that time the type of `version_id` was integer, but now the API returns a string. While it might not be related to above, it shows, along with the change of the `next_stream_position` field (#185), that the API has changed recently in ways that break existing functionality.

**Comment by danielandefors** [comment]
Since it appears that the information provided in enterprise events is a bit different compared to regular user events, would it make more sense update `BoxEvent` , or to provide a separate representation of enterprise events in the SDK? E.g., the content and structure of the `source` information in enterprise events is different (`item_id` instead of `id`, etc), and the `BoxEvent` class cannot make sense of it currently.

I would prefer if the structure of enterprise events was consistent with user events. Speaking of, the current JSON returned for `source` by the API doesn't match the example provided in the [documentation](https://developers.box.com/docs/#events-get-events-in-an-enterprise) (the example is more in line with user events). Please feel free to redirect me to a different forum, but, is there anywhere I can get a spec of what's supposed to be returned by the API? (Asking because I might need to provide my own implementation to meet my current deadlines.)

**Comment by tarrencev** [comment]
Fixed on the API side
