### ISSUE TITLE
BoxFile.getInfo(BoxFile.All_Fields) returns error if preview is not supported

### ISSUE THREAD

**Issue by timsteen** [box/box-java-sdk#196]
For several mime types we get an BoxApiException "The API returned an error code: 415" when calling BoxFile.getInfo(BoxFile.All_Fields). 
The detailed message states: "Previews for 'png' files are not yet supported."
The same is true for boxnotes, tiff, 7z, zip, jpeg.

The expectation is that the info for these files can be retrieved even if a preview is not supported.

This was introduced with box-java-sdk 2.0.0.

**Comment by cburnette** [comment]
@gcurtis this is happening because preview_link is a field now but not all files support preview yet. I guess we need to remove it from the all fields array. I can fix this and then I'd like to push 2.1.0

**Comment by cburnette** [comment]
@timsteen as a work around you can remove preview_link from the fields array before you make the call.

**Comment by timsteen** [comment]
Thanks for the quick answer. But there is no "preview_link" in the fields array. There is only a "shared_link" (as in 1.1.0) field and a new expiring_embed_link".

**Comment by cburnette** [comment]
Sorry, it's the expiring_embed_link. I was not near my computer when I wrote that.

**Comment by timsteen** [comment]
Thanks, that helped!
