### ISSUE TITLE
Fails to get enterprise events if no events returned for the given interval

### ISSUE THREAD

**Issue by danielandefors** [box/box-java-sdk#200]
A call to EventLog.getEnterpriseEvents fails when you don't provide a stream position, and the event log is empty for the given time interval. It fails because `next_stream_position` is a zero in this case. If the call is successful, i.e., because it found events in the given interval, `next_stream_position` will be a string. The exception is:

```
java.lang.UnsupportedOperationException: Not a string: 0
    at com.eclipsesource.json.JsonValue.asString(JsonValue.java:365)
    at com.box.sdk.EventLog.<init>(EventLog.java:38)
    at com.box.sdk.EventLog.getEnterpriseEvents(EventLog.java:104)
```

**Comment by danielandefors** [comment]
The response JSON:

```json
{
   "chunk_size": 0,
   "next_stream_position": 0,
   "entries": []
}
```

**Comment by gcurtis** [comment]
Thanks for the fix. I've contacted our API team to see if we can get a fix on the server-side of things. The `next_stream_position` field should always be a string.

**Comment by danielandefors** [comment]
Yes, it would be much cleaner if it always was a string. Thanks!

**Comment by gcurtis** [comment]
This should now be fixed server side. Please let me know if you're still running into issues.
