### ISSUE TITLE
Is there anyway to other way to get an access token besides redirect_uri?

### ISSUE THREAD

**Issue by cheyrico2** [box/box-java-sdk#208]

**Comment by cburnette** [comment]
Hey, have a look at this documentation about an entirely different way to build apps on the Box Platform.  It doesn’t use OAuth2 three legged scenario.

https://box-content.readme.io/docs/box-platform <https://box-content.readme.io/docs/box-platform>


Box is also coming out with persistent server tokens in the not too distant future.  

Chad

**Comment by cheyrico2** [comment]
Chad,
I've been following the link above but I'm running into some trouble. I'm trying to create an application where the expected user type is a Standard Box Users. The example says i should select "App Users".

Is there any example for a Standard Box Users using the JSON Web Token?

**Comment by cburnette** [comment]
No, currently JSON web tokens only work with our App User (Box Platform) model.  We will be releasing in the near future another new token type that will work with ‘normal’ users but leverage JSON web tokens.
