### ISSUE TITLE
Issues with new Box Java SDK

### ISSUE THREAD

**Issue by Syed-SnapLogic** [box/box-java-sdk#209]
Earlier, we used the following SDK:  
            groupId: net.box
            artifactId: boxjavalibv2
            version: 2.1.20

Now, I am using the latest SDK:
            groupId: com.box
            artifactId: box-java-sdk
            version: 2.0.0

I am simply browsing the root folder to display all the contents including sub-folders.  Surprisingly the new code is about 5 times slower than the old code.  Also, old code is displaying about 2500 objects while the new code is displaying about 3000 objects.  This is very strange.  I double-checked to ensure the extra objects listed in new code results are not available in old code results.

Can someone explain why the new code is slow and why old code is not displaying all the objects?

**Comment by Syed-SnapLogic** [comment]
**Old Code:**
private static void readFolderData(BoxClient client, String parentID,
            String folderName) throws Exception {
        Map<String, Object> folderTree;
        BoxFolder parent = client.getFoldersManager().getFolder(parentID, null);
        List<BoxTypedObject> folderContents = parent.getItemCollection().getEntries();
        for (int i = 0; i < folderContents.size(); i++) {
            folderTree = new HashMap<String, Object>();
            BoxTypedObject boxObject = folderContents.get(i);
            Object objectType = boxObject.getValue("name");
            if (boxObject.getType().equalsIgnoreCase("Folder")) {
                // display folder attributes(name, id, etc) and then browse its contents
                readFolderData(client, boxObject.getId(), objectType.toString());
            } else {
                // display file attributes and return
            }
        }
    }

**New Code:**
private static void readFolderData(BoxFolder folder) {
        Map<String, Object> folderTree;
        for (BoxItem.Info info : folder) {
            folderTree = new HashMap<String, Object>();
            if (info instanceof BoxFolder.Info) {
                // display folder's attributes (id, name, etc) and keep browsing its contents
                readFolderData(new BoxFolder(connection, info.getID()));
            } else {
                // display file attributes and return
            }
        }
    }
    
    protected static BoxFolder getReferenceToFolder(String parentID) {
        return new BoxFolder(connection, parentID);
    }

To make my message simple, I suppressed the statements for printing the attributes. 
Can you now explain one more time why the afore-mentioned problems are occurring?

**Comment by gcurtis** [comment]
It looks like the code with the old SDK has a bug and wasn't actually retrieving all the items in the folder. `parent.getItemCollection()` will only return the first page of items. If a folder has more items than the default page size, then you won't see all of them. The [API docs](https://box-content.readme.io/reference#pagination) give more of an explanation on how pagination works.

The new SDK automatically does the paging for you. `BoxFolder`'s iterator will retrieve the next page of items to ensure that you actually iterate over all the children. However, this also means it's making additional HTTP requests, which is why the code is now slower.

Hope that helps!

**Comment by tarrencev** [comment]
Closing since it seems this is resolved, feel free to reopen if that's not the case
