### ISSUE TITLE
What is the maximum file size that can be transferred per HTTP Request?

### ISSUE THREAD

**Issue by cheyrico2** [box/box-java-sdk#212]
Reading you new documentation for [Upload File](https://box-content.readme.io/reference#upload-a-file) which described that your API uses a [multipart post](http://hc.apache.org/httpclient-3.x/methods/multipartpost.html). I have the following question: What is the maximum file size that can be transferred per HTTP Request?

**Comment by cburnette** [comment]
Box defaults to a 5GB file size limit for enterprise account, but that varies by account type. It’s smaller for personal accounts, for example.  You can make an api call to get a user’s info, and the returned data includes a field called max_upload_size.  That will tell you, for the current user, how big a file you can upload.

https://box-content.readme.io/reference#users <https://box-content.readme.io/reference#users>
