### ISSUE TITLE
BoxUser.moveFolderToUser() throws exception

### ISSUE THREAD

**Issue by robertrlandry** [box/box-java-sdk#216]
Hello,

I updated to v2.1.1 to make use of the moveFolderToUser() method. However, I receive this exception message: "Couldn't finish closing the connection to the Box API due to a network error or because the stream was already closed"

My wrapper method using the REST request directly still works fine.

thx, r

**Comment by mattwiller** [comment]
Hi @robertrlandry — this issue was fixed in #485 and the latest version of the SDK (v2.9.0) includes the fix.
