### ISSUE TITLE
Available fields of a BoxGroup

### ISSUE THREAD

**Issue by maurercw** [box/box-java-sdk#219]
Is there direct access to getting/setting fields on a BoxGroup?  Specifically interested in these mentioned in the rest api (https://box-content.readme.io/reference#group-object):
provenance
external_sync_identifier
invitability_level
member_viewability_level

**Comment by tarrencev** [comment]
Hi @maurercw, sorry for the delayed response. The functionality to update those fields has not been implemented yet. It's on our todo list though. I'll update this thread once it has been added.

**Comment by maurercw** [comment]
Thanks for the followup, @tarrencev.  I might try to take a stab at this unless you think it'll be addressed very soon.

**Comment by tarrencev** [comment]
@maurercw we are working on getting the Java SDK to full API coverage over the next couple months, and this would be done as part of that. So relatively soon but you're more than welcome to take a stab!

**Comment by maurercw** [comment]
Ok.  I made a quick attempt and think I have stuff working.  Our main need is setting some of those values on group creation, so this may cover what we need, at least in the short term.  I'll try to get it cleaned up and get a pr out this week.
