### ISSUE TITLE
Unable to use the proxy with BoxDeveloperEditionAPIConnection static methods

### ISSUE THREAD

**Issue by LFT** [box/box-java-sdk#221]
Both `getAppUserConnection` and `getAppEnterpriseConnection` are static method that create a connection then try to authenticate.
It's impossible to specify a proxy for the authentication request without doing it manually (i.e. creating the connection, adding the proxy and then authenticating) thus losing all the logic in `tryRestoreUsingAccessTokenCache`.

I'm seeing some way to address the problem:
1/ adding a method who takes the current arguments + proxy/username/password (but the method starts having a lot of arguments) and who does the proxy assignation internally.
2/ making `tryRestoreUsingAccessTokenCache` a public method to allow developers to do a proper connection process by themselves.

**Comment by garywilliamstrp** [comment]
I have the same issue, need to be able to set Proxy information for BoxDeveloperEditionAPIConnection

**Comment by riteshmaddala** [comment]
Hi Team,

Is this issue resolved? 

We are using BOX URL behind Proxy and need to configure the Proxy Settings to use BoxDeveloperEditionAPIConnection. 

Please let me know.

Thanks
Ritesh

**Comment by mangelo123** [comment]
I am having an issue with the above methods as well, but I am not sure what is causing the error. See code below:

```
	public static void main(String[] args) {

		BoxAPITest test = new BoxAPITest();
		try {
			Reader reader = new FileReader(test.getFileName("box-config.json"));
			BoxConfig boxConfig = BoxConfig.readFrom(reader);
			
			// Set cache info
			int MAX_CACHE_ENTRIES = 100;
			IAccessTokenCache accessTokenCache = new 
			  InMemoryLRUAccessTokenCache(MAX_CACHE_ENTRIES);

			// Create new app enterprise connection object
			BoxDeveloperEditionAPIConnection client = 
			  BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(boxConfig, accessTokenCache);

			// PERFORM ACTIONS WITH CLIENT
		}
		catch (Exception e) {
			System.out.println(e);
		}
	}

```

After this code runs I simply get: "java.lang.NullPointerException"

**Comment by mattwiller** [comment]
@mangelo123 Do you have the stack trace of the `NullPointerException`?

**Comment by meredithjohnssg** [comment]
Did anyone solve NullPointerException for the above code? Please help let me know. Thanks.

**Comment by jeevajj** [comment]
I'm also facing the same issue. Anyone has solution for this issue?

**Comment by carycheng** [comment]
Hey @jeevajj, 

The static methods are convenience methods, if you would like a richer suite of functionality you should creating an instance of BoxDeveloperEditionAPIConnection and setting the proxy on that object:

```java
		BoxDeveloperEditionAPIConnection api =  new BoxDeveloperEditionAPIConnection(ENTEPRISE_ID, DeveloperEditionEntityType.ENTERPRISE, boxConfig, getAccessTokenCache() );

		Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("127.0.0.1", 1080));

		api.setProxy(proxy);
//		api.setProxyUsername("USERNAME");
//		api.setProxyPassword("PASSWORD");

		Authenticator authenticator = new Authenticator() {
	        public PasswordAuthentication getPasswordAuthentication() {

	            return (new PasswordAuthentication("username",
	                    "password".toCharArray()));
	        }
	    };

	    Authenticator.setDefault(authenticator);		
```

Let us know if this works, thanks!

**Comment by jeevajj** [comment]
Hi @carycheng, 
I have tried your solution, now I'm able to connect but I didn't get the access token.
Following the code snippet I used,
`int MAX_CACHE_ENTRIES = 100;`
 `IAccessTokenCache accessTokenCache = new`
              `InMemoryLRUAccessTokenCache(MAX_CACHE_ENTRIES);`

 `BoxDeveloperEditionAPIConnection client = new` `BoxDeveloperEditionAPIConnection(boxConfig.getEnterpriseId(),` 
`DeveloperEditionEntityType.ENTERPRISE, boxConfig, accessTokenCache ); `
`Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("127.0.0.1", 80)); `
 `client.setProxy(proxy);`
Please advise

**Comment by carycheng** [comment]
Hey @jeevajj,

Apologies! You will also need to call `api.authenticate` after you set the proxy. I updated the code snippet above.

Thanks!

**Comment by jeevajj** [comment]
Hi @carycheng,
    From the above code to we were able to communicate via proxy network. we can able to create folder and get files from box. But when it comes to file upload it throwing 502 bad gateway.

**Comment by jeevajj** [comment]
Hi @carycheng 
Thanks. Its working fine.

**Comment by carycheng** [comment]
@jeevajj, thanks for letting us know! Let us know if other issues arise, thanks!

**Comment by hallosushant** [comment]
I was facing the same issue and what I did is to create a new Connection class extending the BoxDeveloperEditionApiConnection, its working fine and with tokens:

`
import com.box.sdk.BoxConfig;
import com.box.sdk.BoxDeveloperEditionAPIConnection;
import com.box.sdk.DeveloperEditionEntityType;
import com.box.sdk.IAccessTokenCache;
import com.eclipsesource.json.JsonObject;

import java.net.Proxy;

public class MyBoxAPIConnection extends BoxDeveloperEditionAPIConnection {

    private IAccessTokenCache accessTokenCache;
    private String entityID;
    private DeveloperEditionEntityType entityType;

    public MyBoxAPIConnection(BoxConfig boxConfig, IAccessTokenCache accessTokenCache, Proxy proxy) {
        this(boxConfig.getEnterpriseId(), DeveloperEditionEntityType.ENTERPRISE, boxConfig, accessTokenCache);
        this.setProxy(proxy);
        this.tryRestoreUsingAccessTokenCache();
    }

    public MyBoxAPIConnection(String entityId, DeveloperEditionEntityType entityType, BoxConfig boxConfig,
            IAccessTokenCache accessTokenCache) {
        super(entityId, entityType, boxConfig, accessTokenCache);
    }

    private void tryRestoreUsingAccessTokenCache() {
        if (this.accessTokenCache == null) {
            // no cache specified so force authentication
            this.authenticate();
        } else {
            String cachedTokenInfo = this.accessTokenCache.get(this.getAccessTokenCacheKey());
            if (cachedTokenInfo == null) {
                // not found; probably first time for this client config so authenticate; info will then be cached
                this.authenticate();
            } else {
                // pull access token cache info; authentication will occur as needed (if token is expired)
                JsonObject json = JsonObject.readFrom(cachedTokenInfo);
                this.setAccessToken(json.get("accessToken").asString());
                this.setLastRefresh(json.get("lastRefresh").asLong());
                this.setExpires(json.get("expires").asLong());
            }
        }
    }

    private String getAccessTokenCacheKey() {
        return String.format("/%s/%s/%s/%s", this.getUserAgent(), this.getClientID(), this.entityType.toString(),
                this.entityID);
    }

}

`

**Comment by praxnet** [comment]
@hallosushant Can you point me to a complete example of how can i use MyBoxAPIConnection class, and what to do when i get "com.box.sdk.BoxAPIException: Couldn't connect to the Box API due to a network error.", in such cases how to refresh connection.
