### ISSUE TITLE
Searching recently created folder not available in search result

### ISSUE THREAD

**Issue by cheyrico2** [box/box-java-sdk#224]
I'm writing an application that will upload files to BOX. As I'm using the search method: 

    Iterable<BoxItem.Info> results = folder.search(keyword);
    for (BoxItem.Info result : results) {
        if (result instanceof BoxFolder.Info) {
            out.println("found: "+ result.getName() 
            + " with ID: " + result.getID());
            continue;
        }
        out.println(result.getName());
    }

I'm noticing that it takes long time before the item is available but it is immediately available if I simply iterate over the folder.

I'm using box-java-sdk 2.1.1.

**Comment by aamave** [comment]
Can you clarify what you mean by iterate over the folder?

Search in our API is bound by the same constraints as search in our product. As outlined here, https://community.box.com/t5/Managing-Your-Content/Search-Overview-and-FAQs/ta-p/354#search_hdsiw, 
_"Search Availability: Just as it takes Google time to crawl content on the web when new content is added, it takes up to 10 minutes for items to be fully indexed by the Box search engine. You can expect that as you add files, they will be available via search in less than 10 minutes."_

**Comment by cheyrico2** [comment]
I''m concern about the searching folder for my application. I'm noticing that a newly created folder is not immediately available in the result from the `folder.search(keyword);` but i can find it, if try to get item from the folder

    BoxFolder folder = new BoxFolder(api, "id");
    for (BoxItem.Info itemInfo : folder) {
        if (itemInfo instanceof BoxFile.Info) {
            BoxFile.Info fileInfo = (BoxFile.Info) itemInfo;
            // Do something with the file.
        } else if (itemInfo instanceof BoxFolder.Info) {
            BoxFolder.Info folderInfo = (BoxFolder.Info) itemInfo;
            // Do something with the folder.
        }
    }

it essentially becomes an issue if i create a folder from one device and immidiately try to search for it on an another.

**Comment by cheyrico2** [comment]
Thank you @aamave but I was hoping to get solution that would expedite the process
