### ISSUE TITLE
Tags don't seem to return? 

### ISSUE THREAD

**Issue by nddipiazza** [box/box-java-sdk#229]
I've got tags on my object yet BoxInfo.getTags() seems to always be null.

Am I missing something?

**Comment by gcurtis** [comment]
Tags are only returned if you specify them as a fields parameter. Try calling [`getInfo()`](http://opensource.box.com/box-java-sdk/javadoc/com/box/sdk/BoxItem.html#getInfo(java.lang.String...)) with `BoxItem.ALL_FIELDS`.

The [API docs](https://box-content.readme.io/reference#fields) describe this in more detail.
