### ISSUE TITLE
BoxFile.Info update date fields not working

### ISSUE THREAD

**Issue by amjoesph** [box/box-java-sdk#242]
After file creation.  Updating its file information isn't working for few fields. 

updating description works. 
fileInfo.setDescription("desc")

updating "content_created_at" , "content_modified_at" is not working. 
fileInfo.getContentCreatedAt().setTime(1462819930632)

boxFile.updateInfo(fileInfo);

**Comment by gcurtis** [comment]
Hi @amjoesph, I don't believe the API supports updating the `content_modified_at` field. It can only be set when the file is initially uploaded.

You can do this using the [`BoxFolder.uploadFile(FileUploadParams)`][1] method and calling [`setCreatedAt(Date)`][2] on the `FileUploadParams`.

[1]: http://opensource.box.com/box-java-sdk/javadoc/com/box/sdk/BoxFolder.html#uploadFile(com.box.sdk.FileUploadParams)
[2]: http://opensource.box.com/box-java-sdk/javadoc/com/box/sdk/FileUploadParams.html#setCreated(java.util.Date)

**Comment by amjoesph** [comment]
FileUploadParams doesn't have setDescription.  It's part of initial file metadata. Is there anyway those methods can be added?

Just to set  description i have to make two extra calls.

**Comment by amjoesph** [comment]
FileUploadParams  api for updating date is NOT working correctly

`
FileUploadParams fileParams = new FileUploadParams();
			fileParams.setContent(inputStream);
			fileParams.setName(fileName);
			
			Date creationDate = new Date(Long.parseLong(fileProps.get("content_created_at")));
			
			log.debug("Millisec:" + fileProps.get("content_created_at") + ":date:" + creationDate.toLocaleString());
			
			if (StringUtils.isNotBlank(fileProps.get("content_created_at"))) {
				fileParams.setCreated(creationDate);
			}
			
			if (StringUtils.isNotBlank(fileProps.get("content_modified_at"))) {
				fileParams.setCreated(new Date(Long.parseLong(fileProps.get("content_modified_at"))));
			}
			
			fileInfo = boxFolder.uploadFile(fileParams);
`

log statements display 
Millisec:1462819930632:date:May 9, 2016 2:52:10 PM

in box ui. its displayed as Jun 1, 2012

**Comment by gcurtis** [comment]
The API only lets you set the name, created_at, and modified_at fields when uploading a file. The API docs for uploading a file [can be found here][1]. You'll need to make two API calls to set the description.

It looks like you're setting the created date to `fileProps.get("content_modified_at")` in your second if statement. This might be why you're getting an unexpected result.

Here's some sample code that I've verified for setting the created date:

```java
BoxAPIConnection api = new BoxAPIConnection("my-token");
BoxFolder rootFolder = BoxFolder.getRootFolder(api);
File file = new File("test.txt");
try {
    FileInputStream fis = new FileInputStream(file);
    FileUploadParams fileParams = new FileUploadParams();
    fileParams.setContent(fis);
    fileParams.setName("test.txt");

    Date creationDate = new Date(1462057200000l);
    fileParams.setCreated(creationDate);

    rootFolder.uploadFile(fileParams);
} catch (Exception e) {
    e.printStackTrace();
}
```

[1]: https://box-content.readme.io/reference#upload-a-file

**Comment by amjoesph** [comment]
Ok.

**Comment by amjoesph** [comment]
Ok.
