### ISSUE TITLE
BoxFolder.Info update date fields

### ISSUE THREAD

**Issue by amjoesph** [box/box-java-sdk#243]
is there an api to update the update and created dates on BoxFolder. 

BoxFolder
    public void updateInfo(BoxFolder.Info info) {...}

this method doesn't update dates.

**Comment by gcurtis** [comment]
The Box REST API does not support changing the `created_at` or `modified_at` dates.

**Comment by amjoesph** [comment]
weird...  It's supported on files and not on folders.
will this be added on the future..
