### ISSUE TITLE
com.box.sdk.BackoffCounter

### ISSUE THREAD

**Issue by amjoesph** [box/box-java-sdk#244]
Below message was thrown, when trying to upload files by parallel process. 

com.box.sdk.BackoffCounter -     waitBackoff() : Backing off for 2 seconds before retrying 2 more times.

Is the max attempt request on BoxApiConnection is 3?.  Trying to figure out, how many parallel process can be instantiated?

**Comment by makarchus** [comment]
Having the same issue, hope somebody can respond to this thread with some solution

**Comment by gcurtis** [comment]
Hey @amjoesph. The SDK defaults to 3 attempts, but you can configure it using [`BoxAPIConnection.setMaxRequestAttempts()`][1]. How many parallel requests are you making? You might be getting rate limited if you're making too many requests too quickly.

[1]: http://opensource.box.com/box-java-sdk/javadoc/com/box/sdk/BoxAPIConnection.html#setMaxRequestAttempts(int)
