### ISSUE TITLE
Listing Bookmarks in Folder

### ISSUE THREAD

**Issue by Syed-SnapLogic** [box/box-java-sdk#245]
In one of my Box folders, I have some bookmarks saved.  When I browse this folder, bookmarks are not being listed.  I am using Box Java SDK.  Any help on how to retrieve bookmarks?  I am attaching image next that shows the bookmarks but they are not getting listed in my application thru Box SDK.

https://plus.google.com/u/0/photos/albums/pc55vro0ptofrguuf1cl69jb7fndkfeto?pid=6285944057981770146&oid=109879195909390357070

**Comment by Syed-SnapLogic** [comment]
Guys, can anyone please help me with the answer.  This is needed ASAP.

**Comment by gcurtis** [comment]
Hi @Syed-SnapLogic. The SDK doesn't have bookmark support yet. This was a feature added to the Box API after the SDK was originally written.

If you need bookmark support, you will need to make a custom request to our REST API. The SDK [has some classes][1] that you might find helpful for doing this. The API docs for bookmarks (aka WebLinks) can be found [here][2]. 

We are, of course, also accepting any pull requests to help add bookmarks support. Hope this helps!

[1]: https://github.com/box/box-java-sdk/blob/master/doc/overview.md#requests-and-responses
[2]: https://box-content.readme.io/reference#get-the-tasks-for-a-file

**Comment by tarrencev** [comment]
Issue ticket to add this functionality exists here #124
