### ISSUE TITLE
Can't upload file as appuser

### ISSUE THREAD

**Issue by tsendeemts** [box/box-java-sdk#251]
Trying to upload a file to folder of an appuser as follows:

```
val boxApi = BoxDeveloperEditionAPIConnection.getAppUserConnection(userId, CLIENT_ID,
      CLIENT_SECRET, encryptionPref, accessTokenCache)
val folder = new BoxFolder(boxApi,folderId)
folder.canUpload("fileToUpload", 30) //here I get 403
val inputStream = fileUtil.getInputStream(filename)
val fileInfo = folder.uploadFile(inputStream,filename) // here also I get 403
```

The user has all the permissions, I can see it from the file info.

I am sorry if creating an issue for an obvious question, but I really appropriate your input.

Thanks!

**Comment by amjoesph** [comment]
Does the appuser have permissions on the folder, you are trying to upload?

**Comment by tsendeemts** [comment]
Yes, the app user has the following permissions I can get it from the file info:
CAN_DOWNLOAD, CAN_UPLOAD, CAN_RENAME, CAN_DELETE, CAN_SHARE, CAN_INVITE_COLLABORATOR, CAN_SET_SHARE_ACCESS

Basically the permission field contains them.

**Comment by adilakshmis** [comment]
![issue](https://cloud.githubusercontent.com/assets/17335748/17724537/8df48438-6460-11e6-83ee-419d0da083eb.png)

You should allocate some memory to newly created app_user as shown in picture

**Comment by gcurtis** [comment]
Hi @tsendeemts, are you still running into this issue? Please reopen this ticket if it's still unresolved.
