### ISSUE TITLE
How to do you log http request and response for box-java-sdk?

### ISSUE THREAD

**Issue by cheyrico2** [box/box-java-sdk#252]
I'm troubleshooting an issue where the code seems to provide an error when ran on a different machine. I've tried setting the following but I do not see log output.

`BasicConfigurator.configure();`
`Logger.getLogger("com.box.sdk").setLevel(Level.FINEST);`

I'm really interested in seeing the request and response to compare.

**Comment by gcurtis** [comment]
Hi @cheyrico2, can you try this code snippet?

```java
Logger logger = Logger.getLogger("com.box.sdk");
logger.setLevel(Level.FINE);

Handler handler = new ConsoleHandler();
handler.setLevel(Level.FINE);
logger.addHandler(handler);
```

This sounds like something that we should add to the documentation.
