### ISSUE TITLE
Can we upload file with tags to box ?

### ISSUE THREAD

**Issue by tranquang9a1** [box/box-java-sdk#259]
Hello

I use Box SDK to upload file to Box server. But I want to set tag for this file.
Can I use SDK to do it or must do manually on UI?

Regards,
Quang

**Comment by tarrencev** [comment]
Hi @tranquang9a1,

It's not possible to upload files with tags. However, it is possible to set tags on a file after it has been uploaded, using the method discussed [here](https://github.com/box/box-java-sdk/issues/129). 

I would like to note that Tags are in the process of being deprecated. I'd encourage you to explore whether Metadata would be a suitable alternative to accomplish your use case.

**Comment by tranquang9a1** [comment]
Hello @tarrencev ,

Thank you for your support. I will try to use Metadata when needed ;)

**Comment by IamNaN** [comment]
@tarrencev What you suggest requires two round-trips to the server. That doubles the API calls and halves the performance. This seems like an arbitrary restriction and puts an undue burden on developers. Besides making a poor end-user experience, it causes us to bump against your API call throttling more often, puts more burden on your servers, and costs us more.

Please consider changing this from "question" to "feature request".

**Comment by tarrencev** [comment]
@IamNaN I completely agree with you, but that is more of a feature request for the API itself than this particular SDK. I think it might be more appropriate to escalate it through the [developer support site](https://docs.box.com/page/support). Sorry for the inconvenience.

**Comment by IamNaN** [comment]
Oh you're right. I was thinking in the wrong context. Apologies.
