### ISSUE TITLE
BoxSearch in box-java-sdk-2.2.1-20160613.174312-1.jar is not working

### ISSUE THREAD

**Issue by amjoesph** [box/box-java-sdk#260]
BoxSearch
=========

BoxSearch search = new BoxSearch(boxCon);
     
     BoxSearchParameters searchParms = new BoxSearchParameters();
     searchParms.setType("file");
     List<String> ancIds = new ArrayList<String>();
     ancIds.add(prod_Stand_id);
     searchParms.setAncestorFolderIds(ancIds);
     searchParms.setKeyword("test");
     
     PartialCollection<BoxItem.Info> parItemInfo = null;
     
     try {
       parItemInfo = search.searchRange(10,10,searchParms);
     } catch (BoxAPIException e) {
       log.error(e.getResponse(),e);
     }

It throws below exception 
{"type":"error","status":400,"code":"bad_request","context_info":{"errors":[{"reason":"missing_parameter","name":"to_search","message":"'to_search' is required"}]},"help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"Bad Request","request_id":"13294361075762dcc1b8329"}

While looking at the BoxSearchParameters.getQueryParameters(). ->  is not generating to_search.  keyword field value is also not translated. 

Martin

**Comment by tarrencev** [comment]
Hi @amjoesph, as far as I can tell, the `keyword` field is not valid for search. I'm not sure why the getter and setter are exposed. Is your intention to use "test" as a query string? If so, you should use `setQuery()`.

If you are trying to do a keywordless/queryless search, a metadata filter must be supplied

**Comment by tarrencev** [comment]
Hi @amjoesph, I've merged #264 to enforce that either a search query or metadata template is set when performing a search and have removed the keywork setter/getter. Please let me know if you encounter any other issues
