### ISSUE TITLE
Box Platform Error 400 - Invalid Request

### ISSUE THREAD

**Issue by Croissong** [box/box-java-sdk#268]
I set up my platform application via [docs.box.com](https://docs.box.com/docs/getting-started-box-platform) and followed the examples in [CreateAppUser](https://github.com/box/box-java-sdk/blob/master/src/example/java/com/box/sdk/example/CreateAppUser.java) and [AccessAsAppUser](https://github.com/box/box-java-sdk/blob/master/src/example/java/com/box/sdk/example/AccessAsAppUser.java).
Creating the AppUser works fine but in `BoxDeveloperEditionAPIConnection.getAppUserConnection` I receive the error 
`{"error":"invalid_request","error_description":"Cannot obtain user token based on the enterprise configuration for your app"}`.

**Comment by tarrencev** [comment]
Hi @Croissong, are you attempting to call `getAppUserConnection` with for the user generated in the `CreateAppUser` example? 

I believe with the default configuration it is not possible to create an app-user connection for a non-app-user account, i.e. an account created through the box signup flow, and in that case it would return the error you are seeing.

**Comment by Croissong** [comment]
Yes, all I did was created the User with the CreateAppUser example and pasted the User ID into the AccessAsAppUser example. What i find weird is that when i create an AppUser both with the SDK or following the curl example, and explicitly set `IsPlatformAccessOnly `to true, for the created user it returns false.
 I am using a normal, free developer account.

**Comment by Croissong** [comment]
This is unrelated to the [As-User](https://docs.box.com/reference#as-user-1) feature, which seems to require authorization of a box admin, right?

**Comment by tarrencev** [comment]
Has your application been authorized by the enterprise to manage app users? You can see this on the Admin Console -> Settings -> [Apps page](https://app.box.com/master/settings/openbox) under `Custom Applications`

**Comment by tarrencev** [comment]
Yes, As-User feature is unrelated to App Users, which is designed to allow Admins to masquerade as a managed user

**Comment by Croissong** [comment]
Yes, and the only available option for Access is `Only App Users of this App`

**Comment by tarrencev** [comment]
@Croissong, I've been informed that this is actually an issue on our end that has been affecting all apps created after Tuesday last week. Sorry for the inconvenience, I'll post an update to this issue once it has been resolved

**Comment by tarrencev** [comment]
@Croissong I'm told this issue should be resolved now, feel free to reopen if not. Sorry for the inconvenience!
