### ISSUE TITLE
Support for Metadata Templates

### ISSUE THREAD

**Issue by abelsromero** [box/box-java-sdk#270]
Hi,

Are metadata templates available in the SDK?
I don't see any reference in the documentation and the only mention I have found in the issues is about plain metadata, not templates.

Thanks,

**Comment by tarrencev** [comment]
Hi @abelsromero, the sdk does support file metadata templates, unfortunately the functionality is not documented right now. You can see the [get metadata template](https://docs.box.com/reference#get-metadata-schema) implementation [here](https://github.com/box/box-java-sdk/blob/master/src/main/java/com/box/sdk/BoxFile.java#L683). That returns a `Metadata` object that can be operated on and then persisted using the [updateMetadata](https://github.com/box/box-java-sdk/blob/master/src/main/java/com/box/sdk/BoxFile.java#L695) method. 

Hope that clears things up a bit, and sorry for the inconvenience, we are actively working on improving our documentation. Let me know if you have any other questions!

**Comment by abelsromero** [comment]
Yes, you are right, I could run some test and I get it working :+1:
