### ISSUE TITLE
Add missing Special endpoint coverage

### ISSUE THREAD

**Issue by tarrencev** [box/box-java-sdk#273]
Retention Policies
- [ ] Create Retention Policy
- [ ] Create Retention Policy Assignment
- [ ] Get File Version Retention
- [ ] Get File Version Retentions
- [ ] Get Retention Policies
- [ ] Get Retention Policy
- [ ] Get Retention Policy Assignment
- [ ] Get Retention Policy Assignments
- [ ] Update Retention Policy

Devices
- [ ] Delete Device Pin
- [ ] Get Device Pin
- [ ] Get Enterprise Device Pins

**Comment by gcurtis** [comment]
These will be broken out into separate issues for v2.2.0.
