### ISSUE TITLE
Add missing Core Platform endpoint coverage

### ISSUE THREAD

**Issue by tarrencev** [box/box-java-sdk#275]
Web Links
- [x] Create Web Link
- [x] Delete Web Link
- [x] Get Web Link
- [x] Update Web Link

Metadata
- [ ] Create Metadata on Folder
- [ ] Delete Metadata on Folder
- [ ] Get all Metadata on File
- [ ] Get all Metadata on Folder
- [ ] Get Enterprise Metadata
- [ ] Get Metadata on Folder
- [ ] Get Metadata Template
- [ ] Update Metadata on Folder

Collections
- [ ] Create or Delete
- [ ] Get Collection Items
- [ ] Get Collections

Comments
- [ ] Update Comment

**Comment by gcurtis** [comment]
The remaining work will be tracked in separate issues.
