### ISSUE TITLE
Invalid class cast in RealtimeServerConnection

### ISSUE THREAD

**Issue by codyebberson** [box/box-java-sdk#280]
```
java.lang.ClassCastException: com.box.sdk.BoxAPIResponse cannot be cast to com.box.sdk.BoxJSONResponse
    at com.box.sdk.RealtimeServerConnection.<init>(RealtimeServerConnection.java:22) ~[classes/:na]
    at com.box.sdk.EventStream$Poller.run(EventStream.java:183) ~[classes/:na]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_71]
```

I have only experienced this intermittently.  I do not have a consistent repro case.

Cursory review of BoxAPIRequest.java suggests that the events API did not return Content-Type="application/json".

https://github.com/box/box-java-sdk/blob/master/src/main/java/com/box/sdk/BoxAPIRequest.java#L418-L426

**Comment by gcurtis** [comment]
I agree, it looks like this is happening because the API isn't returning a response with `application/json`. I wonder if there's an error page being returned as HTML or something.
