### ISSUE TITLE
checkstyleExample FAILED

### ISSUE THREAD

**Issue by changbaishan** [box/box-java-sdk#283]
Download from github.
 gradle build
:compileJava
Download https://repo1.maven.org/maven2/com/eclipsesource/minimal-json/minimal-json/0.9.1/minimal-json-0.9.1.pom
Download https://repo1.maven.org/maven2/org/bitbucket/b_c/jose4j/0.4.4/jose4j-0.4.4.pom
Download https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.52/bcprov-jdk15on-1.52.pom
Download https://repo1.maven.org/maven2/org/bouncycastle/bcpkix-jdk15on/1.52/bcpkix-jdk15on-1.52.pom
Download https://repo1.maven.org/maven2/com/eclipsesource/minimal-json/minimal-json/0.9.1/minimal-json-0.9.1.jar
Download https://repo1.maven.org/maven2/org/bitbucket/b_c/jose4j/0.4.4/jose4j-0.4.4.jar
Download https://repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.52/bcprov-jdk15on-1.52.jar
Download https://repo1.maven.org/maven2/org/bouncycastle/bcpkix-jdk15on/1.52/bcpkix-jdk15on-1.52.jar
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
:processResources UP-TO-DATE
:classes
:jar
:javadoc
:javadocJar
:sourcesJar
:signArchives SKIPPED
:assemble
:compileExampleJava
warning: [options] bootstrap class path not set in conjunction with -source 1.6
1 warning
:processExampleResources UP-TO-DATE
:exampleClasses
:checkstyleExample
Download https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/5.9/checkstyle-5.9.pom
Download https://repo1.maven.org/maven2/com/google/guava/guava-jdk5/14.0.1/guava-jdk5-14.0.1.pom
Download https://repo1.maven.org/maven2/com/google/guava/guava-parent-jdk5/14.0.1/guava-parent-jdk5-14.0.1.pom
Download https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/5.9/checkstyle-5.9.jar
Download https://repo1.maven.org/maven2/com/google/guava/guava-jdk5/14.0.1/guava-jdk5-14.0.1.jar
[ant:checkstyle] D:\downloads\java\restfb-master\box-java-sdk-master\box-java-sdk-master\src\example\java\com\box\sdk\example\AccessAsAppUser.java:0: File does not end with a newline.
[ant:checkstyle] D:\downloads\java\restfb-master\box-java-sdk-master\box-java-sdk-master\src\example\java\com\box\sdk\example\CreateAppUser.java:0: File does not end with a newline.
[ant:checkstyle] D:\downloads\java\restfb-master\box-java-sdk-master\box-java-sdk-master\src\example\java\com\box\sdk\example\Main.java:0: File does not end with a newline.
[ant:checkstyle] D:\downloads\java\restfb-master\box-java-sdk-master\box-java-sdk-master\src\example\java\com\box\sdk\example\SearchExamplesAsAppUser.java:0: File does not end with a newline.
:checkstyleExample FAILED

FAILURE: Build failed with an exception.

**Comment by gcurtis** [comment]
This should be fixed now. Please reopen this issue still persists.
