### ISSUE TITLE
BoxMetadataFilter.addFilter returns 404

### ISSUE THREAD

**Issue by adilakshmis** [box/box-java-sdk#285]
In my case I added the metadat while uploading the file DeviceName = Device3
When am searching the file based on metadata the api returning the 404 or 400
        BoxMetadataFilter bmf = new BoxMetadataFilter();
        bmf.setScope("enterprise");
        bmf.setTemplateKey("DeviceName");

```
   bmf.addFilter("DeviceName", "Device3");
```

Can any tell me, how to search the file using custom metadata.

```
Caused by: com.box.sdk.BoxAPIException: The API returned an error code: 404 	at
com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:69) 	at
com.box.sdk.BoxJSONResponse.<init>(BoxJSONResponse.java:30) 	at
com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:423) 	at
com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:209) 	at
com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:184) 	at
com.box.sdk.BoxSearch.searchRange(BoxSearch.java:41)
```

**Comment by mattwiller** [comment]
Hi @adilakshmis — here's a working example for how to search based on metadata:

```java
BoxSearch boxSearch = new BoxSearch(api);
BoxSearchParameters searchParams = new BoxSearchParameters();

BoxMetadataFilter metadataFilter = new BoxMetadataFilter();
metadataFilter.setScope("enterprise");
metadataFilter.setTemplateKey("myTemplate");
metadataFilter.addFilter("myField", "fieldValue");
searchParams.setMetadataFilter(metadataFilter);

PartialCollection<BoxItem.Info> searchResults = boxSearch.searchRange(0, 100, searchParams);
```

This searches for all items with instances of the "myTemplate" metadata template, where the metadata field "myField" from that template has the value "fieldValue".

In your case, a 404 could indicate that it could not find the metadata template you were looking for.  Are you sure that `"DeviceName"` is the correct `templateKey` of the metadata template you want to search against?  I notice that your example used that string for both the template key and the field name — could one of those values be incorrect?
