### ISSUE TITLE
How can i create membership between group and user id using java SDK

### ISSUE THREAD

**Issue by mekhatri1** [box/box-java-sdk#289]

**Comment by carycheng77** [comment]
Hey @mekhatri1, very late to the game, apologies!

But this should do what you're looking for: 
`BoxGroup group = new BoxGroup(api, "groupID");
BoxUser user = new BoxUser(api, "userID");
BoxGroupMembership.Info groupMembershipInfo = group.addMembership(user);`

Please let me know if you have any other issues, replies will be a lot more timely going forward. 

Happy Holidays!
