### ISSUE TITLE
BoxSearch

### ISSUE THREAD

**Issue by OsvaldoOrtega** [box/box-java-sdk#300]
In maven repository BoxSearch not exists the class, but exist in this repository if exist, Which is the different? i can use the class or not?

**Comment by amjoesph** [comment]
Box maven repository is too old.  I have been using code from git request.

**Comment by gcurtis** [comment]
Hi @OsvaldoOrtega, the new `BoxSearch` class will be included in the v2.2.0 release which should be going out by next Friday.
