### ISSUE TITLE
BoxSearch with BoxMetadataFilter is not working

### ISSUE THREAD

**Issue by amjoesph** [box/box-java-sdk#301]
`
BoxSearch search = new BoxSearch(boxCon);
BoxSearchParameters searchParms = new BoxSearchParameters();
searchParms.setType("file");

```
         List<String> ancIds = new ArrayList<String>();
         ancIds.add(prod_Stand_id);

         BoxMetadataFilter metadataFilter = new BoxMetadataFilter();
         metadataFilter.addFilter("group", "2200");
         metadataFilter.addFilter("source", "Grouper");

         metadataFilter.setScope("global");

         searchParms.setAncestorFolderIds(ancIds);
```

//           searchParms.setQuery("P2200_Opera");

```
         searchParms.setMetadataFilter(metadataFilter);

         parItemInfo = search.searchRange(0,10,searchParms);`
```

The above code works if I comment this code `searchParms.setMetadataFilter(metadataFilter);`

It's not working with metadataFilter.  Below error message is thrown.
{"type":"error","status":400,"code":"bad_request","help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"Bad Request","request_id":"156750733257f40743d9cae"}

**Comment by cburnette** [comment]
If you search using metadata filter you are not permitted to also set a query value.  You either search by query text, or you search using metadata filters.

Chad

**Comment by amjoesph** [comment]
Chad, 

Search was only by metadata and it failed.  

{"type":"error","status":400,"code":"bad_request","help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"Bad Request","request_id":"156750733257f40743d9cae"}

On the above code, setQuery is commented.

**Comment by cburnette** [comment]
ah, i believe now that you cannot search against the global scope.  Try creating a metadata template, create those two fields, and then change your query to set scope to enterprise and set the template name.

**Comment by amjoesph** [comment]
currently, we have populated quite a few documents with metadata on global scope.  
when can we expect a fix to search against "global" scope.

**Comment by cburnette** [comment]
@amjoesph  We verified that it is possible to search using the global scope (apologies).  Can you try again and surround your code Try/Catch and catch a BoxAPIException?  You might see more detail in the exception object.

**Comment by amjoesph** [comment]
chad, 

Great.  Did you try the metadata search on box-jdk?  Exception thrown by BoxAPIException is posted on the earlier email.
Can you try these against box-jdk and let me know.

**Comment by amjoesph** [comment]
Rest api for metadata search didn't work too

before url encode
 https://api.box.com/2.0/search?ancestor_folder_ids=7787596853&mdfilters=["scope":"global", "filters":{"doctype_file": "xls"}}]

url encoded
$ curl -H "Authorization: Bearer ........." https://api.box.com/2.0/search?ancestor_folder_ids=7787596853&mdfilters=%5B%22scope%22%3A%22global%22%2C+%22filters%22%3A%7B%22doctype_file%22%3A+%22xls%22%7D%7D%5D
[1] 32700
[manthoni@JETDAV20 ~]$ {"type":"error","status":400,"code":"bad_request","context_info":{"errors":[{"reason":"missing_parameter","name":"to_search","message":"'to_search' is required"}]},"help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"Bad Request","request_id":"18765817065807b7e1e1873"}

Is there a timeline for this fix?

**Comment by mattwiller** [comment]
This appears to be an issue with the way that the metadata filter is being set up — you need to set both a scope AND a template in order to search by metadata.

Something like this should work:

```java
List<String> ancIds = new ArrayList<String>();
ancIds.add(prod_Stand_id);

BoxMetadataFilter metadataFilter = new BoxMetadataFilter();
metadataFilter.addFilter("group", "2200");
metadataFilter.addFilter("source", "Grouper");

metadataFilter.setScope("global");
metadataFilter.setTemplate("properties"); // You need to set a template!

BoxSearchParameters searchParams = new BoxSearchParameters();
searchParams.setAncestorFolderIds(ancIds);
searchParams.setMetadataFilter(metadataFilter);

BoxSearch search = new BoxSearch(api);
parItemInfo = search.searchRange(0, 10, searchParams);
```
See the [metadata templates documentation](https://developer.box.com/v2.0/reference#metadata-templates) for more information.

Also, the reason why the manual curl call posted above failed is due to a formatting error; `mdfilters` takes an array of objects, e.g. `[{"scope":"global","template":"properties","filters":{"doctype_file": "xls"}}]` — the given example was missing an opening brace.
