### ISSUE TITLE
Info classes (subclasses of BoxJSONObject) are not de-serializable

### ISSUE THREAD

**Issue by dorfire** [box/box-java-sdk#302]
They don't have public default constructors, and are encapsulated within another class, and thus **cannot be deserialized** with `com.fasterxml.jackson` and its likes.

**Comment by gcurtis** [comment]
Hi @dorfire, thanks for the feedback. I have some questions about this issue.

1. Do you know of a way to fix this without making any breaking changes? If not, we can still investigate moving the inner classes out (or making them static) for the next major release.
2. If we move the classes out, they still need a reference to their `BoxResource` type, as is returned by `BoxUser.getResource()`, for example. It sounds like we would need to provide and empty constructor and just return null for that getter. Is that correct?
3. Are there specific areas where the default JSON deserialization logic is inadequate? Perhaps we could improve that to compensate for not being able to use Jackson.
