### ISSUE TITLE
How to disable the email notofication feature in Collaboration

### ISSUE THREAD

**Issue by joshpawan** [box/box-java-sdk#303]
Hi,
We want to disable the email notification feature when we collaborate any folder with user.
We have been told that we can set 'notifyUser' parameter to false to achieve this functionality.
But we don't see any such property to be set in collaboration api in box sdk.
Can you please let us the know, how can we achieve this?

**Comment by gcurtis** [comment]
Hi @joshpawan, this currently isn't implemented in the SDK. I've created #337 to track it.
