### ISSUE TITLE
Adding multiple Metadata key/values to a file ...documentation?

### ISSUE THREAD

**Issue by dprosper** [box/box-java-sdk#304]
```
BoxFile file = new BoxFile(api, fileInfo.getID());
//First one works
file.createMetadata(new Metadata().add("/foo1", "bar1"));
//Second one fails with 409
file.createMetadata(new Metadata().add("/foo2", "bar2"));
```

Trying to understand how to do the above, documentation is not very clear on that.  Also seem to be lacking docs on using the templates feature

**Comment by gcurtis** [comment]
Hey @dprosper, metadata support is kind of spotty right now because it was never updated after the beta release. We'll be working on improving it in the two weeks and adding better documentation.
