### ISSUE TITLE
'Box-Notifications' header is not controllable

### ISSUE THREAD

**Issue by dorfire** [box/box-java-sdk#327]

**Comment by mattwiller** [comment]
@dorfire Unfortunately, there isn't an easy way to do this right now, but I think this workaround using a request interceptor should do the trick:

```java
api.setRequestInterceptor(new RequestInterceptor() {
    @Override
    public BoxAPIResponse onRequest(BoxAPIRequest request) {
        request.addHeader("Box-Notifications", "off");
        return null;
    }
});
```

Then, to remove the header:

```java
api.setRequestInterceptor(null);
```

Can you give this a try and let me know if it solves your issue?

**Comment by mattwiller** [comment]
@dorfire We just introduced a convenience method to set this header on the `BoxAPIConnection` in v2.16.0 of the SDK — see the [documentation](https://github.com/box/box-java-sdk/blob/master/doc/overview.md#suppressing-notifications) for more information.
