### ISSUE TITLE
BoxFolder.getCollaborations only returns the first 100 results

### ISSUE THREAD

**Issue by dorfire** [box/box-java-sdk#330]
`BoxFolder.getCollaborations()` doesn't return the correct result set if there are more than 1000 collaborations.

The HTTP reference states the maximum per-page limit is 1000; but `BoxFolder.getCollaborations()` doesn't even specify it (**so the default of 100 is used**) and doesn't paginate the results with a JSONIterator.

**Comment by mattwiller** [comment]
Hey @dorfire — here's the current API behavior that I'm seeing on a folder with 284 collaborations on it:

* When no limit parameter is specified, all 284 collaborations are returned
* When `?limit=100` is specified, all 284 collaborations are returned

It appears that this API endpoint doesn't respect the limit anyway, and just returns the entire result set.  I don't have a folder with over 1,000 collaborations on hand to test with, can you confirm what you're seeing on your end for me?  How many results are returned for such a folder?
