### ISSUE TITLE
How to determine types of user using java sdk

### ISSUE THREAD

**Issue by shuson** [box/box-java-sdk#333]
Forgive my recklessness.

Since Box provides Personal plan and Business Plan, and inside Personal plan, there are two types of account, besides, in Business plan, there are three types of account.

Is there an API indicating which type a user is? I mean, how to tell a user is a Starter type in Business plan?

It seems the API's model User and Group don't have a clear mapping with types of account in different plans.

Thanks for anyone's help in advance.

**Comment by gcurtis** [comment]
Hey @shuson, unfortunately I don't think there's a way to get this information using the API. You can also try asking in the [Box Developer Forums](https://community.box.com/t5/Developer-Forum/bd-p/DeveloperForum) which might be more helpful with questions related to the REST API.
