### ISSUE TITLE
Multipart Request needs ending "--" when going through Layer7

### ISSUE THREAD

**Issue by Kalrock** [box/box-java-sdk#334]
When sending an upload a file to Box, I need to go through Layer7 as part of our policies. Layer7 expects a "--" after the last boundary. After looking through other self generate multipart request, the "--" after the last boundary seems like an accepted behavior. Adding this will not break the request when going to Box.

**Comment by gcurtis** [comment]
This makes sense to me. We can probably include this in the next release if you're interested in submitting a pull request.
