### ISSUE TITLE
Current date/time MUST be before the expiration date/time listed in the 'exp'

### ISSUE THREAD

**Issue by kendomen** [box/box-java-sdk#380]
I started getting a 400 error and i found that if I set the below to 0f, it works.  I would like to create a pull request.

private String constructJWTAssertion() {
        JwtClaims claims = new JwtClaims();
        claims.setIssuer(this.getClientID());
        claims.setAudience(JWT_AUDIENCE);
        claims.setExpirationTimeMinutesInTheFuture(1.0f);  // this was the error

**Comment by shashijais789** [comment]
The solution was
https://community.box.com/t5/Developer-Forum/Current-date-time-MUST-be-before-the-expiration-date-time-listed/td-p/17871
