### ISSUE TITLE
Setting expiration date on a folder

### ISSUE THREAD

**Issue by alefloch** [box/box-java-sdk#381]
Need a Java API to set the expiration date on folders.

**Comment by gcurtis** [comment]
Hi @alefloch, the Box API doesn't support setting expiration dates on folders. Are you referring to setting the expiration date on a shared link to a folder?

**Comment by alefloch** [comment]
Hello @gcurtis, I am referring to regular folders in Box, I would like a java API to set the expiration date instead of having to write code to delete folders. Thank you for looking at my requirement.
