### ISSUE TITLE
Unreadable BoxAPIException message for HTTP 400 errors

### ISSUE THREAD

**Issue by zqian** [box/box-java-sdk#383]
From time to time, I would get BoxAPIException for either upload file or add folder calls. 

The detailMessage is "detailMessage	"The API returned an error code: 400" (id=898)	", with unreadable response message as following. The response code is "400"

�E��n�0�_�PW�6�kx+:e�ҎE�c���r��軗�ҍ�q����P�
s���Ŕ�ո��FYrU��s4�}�����,ł�"����&*�51R��!R|N��r	/ﯧS�ʠu���Zג�u��%�����ǌ�	�7j:�V�V�w���d�`���D��k�܌!����\Ju�;�7�0s{�{ki�Y��Ӄ��O2�\+�I������sEd'��p���ñ���4�ֹa�S�`�4Q

Has anyone see similar problem?

**Comment by gcurtis** [comment]
Hi @zqian, do you know what API call or method is returning this error message?
