### ISSUE TITLE
Missing enum from BoxEvent causing UNKNOWN event type to return

### ISSUE THREAD

**Issue by kylefernandadams** [box/box-java-sdk#389]
Missing enum for CONTENT_WORKFLOW_UPLOAD_POLICY_VIOLATION events are returning as UNKNOWN.

**Comment by dmaynard** [comment]
Thank you for reporting this.   This fix will be in the next release 2.3.1 (scheduled for Monday February 13.
In the meantime there is a getSourceJSON() method on an event which can use to do custom parsing.
