### ISSUE TITLE
missing webhook in maven jar

### ISSUE THREAD

**Issue by umesh-babu** [box/box-java-sdk#392]
H,

as i was working with box sdk found that Webhooks is not integrated to maven jar[box-java-sdk-2.1.1]. the same exist in the source code. can you please check and let us know by when this can be integrated to maven jar.

**Comment by mattwiller** [comment]
I just checked the current jar on Maven (v2.8.2) and it does seem to include the BoxWebHook class.  I'm going to close this since it seems like it's correctly built now.  If you're having a problem with the newer version, please go ahead and open a new issue!
