### ISSUE TITLE
Box Java SDK - EventLog.java Line 38 failing

### ISSUE THREAD

**Issue by mylimaye** [box/box-java-sdk#393]
While using the Java SDK for Box, I used the EventLog.getEnterpriseEvents() interface. It failed later while instantiating EventLog.

    this.nextStreamPosition = json.get("next_stream_position").asString();
On debugging the problem, it turned out that, json.get("next_stream_position") returns JsonNumber, so calling asString() results into UnsupportedOperationException().

Also, I noticed that - the SDK doesn't provide any API to get the User Events, so some interface like EventLog.getEnterpriseEvents() would be useful.

**Comment by gcurtis** [comment]
Hey @mylimaye, it looks like you might be running an older version of the SDK (pre v2.0.0). There was a breaking change on the API side which changed the `next_stream_position` field from a long to a string. Can you try upgrading to the latest version of the SDK?

For the user events, are you asking for a method that returns events for a specific stream position?

**Comment by mylimaye** [comment]
@gcurtis - I am seeing this UnsupportedOperationException in 2.1.1 version, which I got via maven (com.box:box-java-sdk:2.1.1). 

cksum lib/box-java-sdk-2.1.1.jar
1800762032 169016 lib/box-java-sdk-2.1.1.jar

And about the second query, I meant that - for an individual Box user, not associated with any enterprise, I didn't find any API to get file Events. Our app likes to show recently modified files, so that's why we are interested in individual User events.

I ended up creating a BoxAPIRequest, similar to EventLog.getEnterpriseEvents() - but without "stream_type=admin_logs" and fetched the User Events. Even though this works, if there is any change in the REST APIs in future, we will have to keep monitoring the REST API/box-java-sdk and make appropriate changes.

Thanks!

**Comment by mattwiller** [comment]
@mylimaye I think the [Event Stream](https://github.com/box/box-java-sdk/blob/master/doc/events.md#listening-to-the-eventstream) will handle your use case (listening for user events instead of enterprise events).  I'm going to close this issue since it seems resolved, but if you're having further trouble, please feel free to open a new issue!
