### ISSUE TITLE
Box Java SDK Doc Errors for Box Folder

### ISSUE THREAD

**Issue by shenqinb** [box/box-java-sdk#398]
https://github.com/box/box-java-sdk/blob/master/doc/folders.md

Metadata is not available on Box Folder, but in the API Doc https://github.com/box/box-java-sdk/blob/master/doc/folders.md,  there has Metadata methods for Box Folder. it really confused me, please help to check.

**Comment by KarthikShanmugasundaram** [comment]
@shenqinb I could see the methods specified in https://github.com/box/box-java-sdk/blob/master/doc/folders.md are available in the BoxFolder.java
https://github.com/box/box-java-sdk/blob/master/src/main/java/com/box/sdk/BoxFolder.java

Could you please clarify? Thank you.
