### ISSUE TITLE
Can't get folder pending collaboration user info

### ISSUE THREAD

**Issue by ursaca** [box/box-java-sdk#412]
When obtaining the list of collaborations on a folder (folder.getCollaborations()), the pending collaborations are also retrieved (ID and some other fields), but there's no user information in it. 
I've also checked with REST call (https://api.box.com/2.0/folders/<folder_id>/collaborations) and it's the same, "accessible_by" field is null. I've even tried to obtain Collaboration info by it's ID, but again "accessible_by" field is null.
However in the GUI I see the user name and email on folder collaborators.
Any suggestions how to retrieve pending collaborators info (on a folder)? Thanks.

**Comment by carycheng77** [comment]
Hey @ursaca, 
This should do the trick:
`Collection<BoxCollaboration.Info> pendingCollaborations =`
`BoxCollaboration.getPendingCollaborations(api);`

Let us know if that works, thank you!

**Comment by kalew8** [comment]
@carycheng That doesn't get information for pending collaborators.

**Comment by mattwiller** [comment]
@ursaca @kalew8 Unfortunately, the API does not support viewing the information for a pending collaborator.  This is a known feature gap between the API and the webapp, and boils down to security concerns with showing you the information of a user who has not accepted the invite to collaborate with you.  I'll file a ticket with the team who owns that API endpoint, but for now there isn't a way to get that information via the API.
