### ISSUE TITLE
Search API documentation

### ISSUE THREAD

**Issue by gunicsba** [box/box-java-sdk#415]
Hello,

we recently noticed that the old search feature got deprecated in the latest build, and there is no documentation for the new search API.

The other problem we have is how can we achieve real-time search in box. I.e. locate a file under a folder by name. It seems that search indexing is async so we can't locate the file(s) by name.

Regards,
  Balazs

**Comment by carycheng77** [comment]
Hey @gunicsba, we've updated the readme documentation here #506. 

As for the other question, search generally takes ~10 minutes to index before you can search for it.  

Let me know if there are any other questions I can help with and apologies for the delayed response!
