### ISSUE TITLE
Can not set a limit when requesting admin events with EventLog.getEnterpriseEvents()

### ISSUE THREAD

**Issue by diegogutierrez** [box/box-java-sdk#419]
I can't find a way to specify a limit when retrieving admin events with this method `getEnterpriseEvents(BoxAPIConnection api, Date after, Date before, BoxEvent.Type... types)`. Is there another way to set a event batch size?

**Comment by carycheng77** [comment]
Hey @diegogutierrez, apologies for the late reply, we have a patch out for this, thanks! 

#507

**Comment by mattwiller** [comment]
@diegogutierrez This functionality was just released in v2.9.0 of the Java SDK!  See the bottom of https://github.com/box/box-java-sdk/blob/master/doc/events.md#enterprise-admin-events for more information about how to set the limit.
