### ISSUE TITLE
Space in file name gets converted to '+' when uploading the file

### ISSUE THREAD

**Issue by itsmanishagarwal** [box/box-java-sdk#420]
I uploaded a file with name "NAME WITH SPACE.docx" but in box I get a file with name "NAME+WITH+SPACE.docx". I looked into the 2.3.0 code and see that in file "BoxMultipartRequest" we are URL encoding the form data
`for(int i = 0; i < formData.length; ++i) {`
   `   this.writeOutput("; ");`
 `     this.writeOutput(formData[i][0]);`
  `    this.writeOutput("=\"");`
   `   this.writeOutput(URLEncoder.encode(formData[i][1], "UTF-8"));`
  `    this.writeOutput("\"");`
`    }`

**Comment by luyseyal** [comment]
I can't replicate this with 2.5.0 on Linux. How are you passing the filename to Box Java SDK?
