### ISSUE TITLE
Box file upload hangs on socketWrite0

### ISSUE THREAD

**Issue by gunicsba** [box/box-java-sdk#421]
Hello,

Our process sometimes hangs with no network or CPU activity. Based on the thread dump there should be some sort of timeout implemented in box-java-sdk.

Here's the thread dump:
```
java.net.SocketOutputStream.socketWrite0(java.io.FileDescriptor, byte[ ], int, int)
java.net.SocketOutputStream.socketWrite(byte[ ], int, int)
java.net.SocketOutputStream.write(byte[ ], int, int)
sun.security.ssl.OutputRecord.writeBuffer(java.io.OutputStream, byte[ ], int, int, int)
sun.security.ssl.OutputRecord.write(java.io.OutputStream, boolean, java.io.ByteArrayOutputStream)
sun.security.ssl.SSLSocketImpl.writeRecordInternal(sun.security.ssl.OutputRecord, boolean)
sun.security.ssl.SSLSocketImpl.writeRecord(sun.security.ssl.OutputRecord, boolean)
sun.security.ssl.AppOutputStream.write(byte[ ], int, int)
java.io.BufferedOutputStream.flushBuffer()
java.io.BufferedOutputStream.flush()
java.io.PrintStream.flush()
sun.net.www.http.ChunkedOutputStream.flush(boolean)
sun.net.www.http.ChunkedOutputStream.write(byte[ ], int, int)
sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(byte[ ], int, int)
com.box.sdk.BoxMultipartRequest.writeBody(java.net.HttpURLConnection, com.box.sdk.ProgressListener) (line: 143)
com.box.sdk.BoxAPIRequest.trySend(com.box.sdk.ProgressListener) (line: 389)
com.box.sdk.BoxAPIRequest.send(com.box.sdk.ProgressListener) (line: 209)
com.box.sdk.BoxAPIRequest.send() (line: 184)
com.box.sdk.BoxFolder.uploadFile(com.box.sdk.FileUploadParams) (line: 387)
com.box.sdk.BoxFolder.uploadFile(java.io.InputStream, java.lang.String) (line: 334)
```

I'm not sure how should I continue. This seems to be because of some sort of network issue. When starting the process it runs fine (shows network activity) but after 20-30 seconds it just hangs completely.

Network utilization:
![image](https://cloud.githubusercontent.com/assets/3919203/25269750/4531af2e-267e-11e7-9aa4-1f655dc5d739.png)

**Comment by mattwiller** [comment]
@gunicsba Thanks for the detailed report!  This looks similar to #205 — in both cases we may need to set some sort of long inactivity timeout to catch this sort of case and turn it into a conclusive error.

**Comment by gunicsba** [comment]
@mattwiller we ended up doing that, the bigger the file the more timeout we set. Once it times out, the next try uploads it without any problems. So the base API call works in 99.999% of the cases, and our workaround kicks in for th rest.

**Comment by mattwiller** [comment]
@gunicsba Good to hear that you have a workaround — would you mind sharing the code you're using for that?
