### ISSUE TITLE
Missing CONTENT_ACCESS enum from BoxEvent causing UNKNOWN event returned

### ISSUE THREAD

**Issue by diegogutierrez** [box/box-java-sdk#425]
Hello, I'm trying to catch events when a file tag is changed. Using curl I saw that the event type is CONTENT_ACCESS, but that event is not listed in the BoxEvent enum.

**Comment by mattwiller** [comment]
I added all the missing documented event types to the enum.  Note that per https://developer.box.com/docs/api-changelog#section-2017-10-25-removing-content_access-event-from-the-user-events-endpoint the CONTENT_ACCESS event type is now deprecated, so it was not added.
