### ISSUE TITLE
Should not allow 2+ As-User headers

### ISSUE THREAD

**Issue by nddipiazza** [box/box-java-sdk#429]
Should create an error or just ignore when a request tries to add 2+ `As-User` headers to a Box api request.

Because often times when I'm trying to re-use api connections I use the setRequestInterceptor and `headers.add` to the headers but I have no way to know if I already added the header yet. 

I can't prove it but I don't really think my code is actually adding 2 as-user headers... it might be something to do with how the set request interceptor method works. But either way, would be nice to just prevent the possibility of that.

**Comment by iamharish** [comment]
Fixed in https://github.com/box/box-java-sdk/pull/450
