### ISSUE TITLE
Confusion about inconsistency of BoxSearch.java document and API references

### ISSUE THREAD

**Issue by shuson** [box/box-java-sdk#433]
In file BoxSearch.java, line 31, the doc says 1000 as max number.
But in https://developer.box.com/v2.0/reference#searching-for-content, the max number of limit is 200.

I know Java SDK is also using "https://api.box.com/2.0/". 

So which one is correct reference?

**Comment by iamharish** [comment]
Thanks for pointing it out. I would go with the latest documentation [https://developer.box.com/v2.0/reference#searching-for-content](https://developer.box.com/v2.0/reference#searching-for-content) 
Things might have changed from the time the SDK was written
