### ISSUE TITLE
Box Platform Error 400 : Cannot obtain user token based.. 

### ISSUE THREAD

**Issue by herat007** [box/box-java-sdk#439]
I am using java sdk to create an app user.. I have the JWT all setup and works when i do 

`BoxDeveloperEditionAPIConnection api1 = BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection() `

but doesnt work when i do 

`api = BoxDeveloperEditionAPIConnection.getAppUserConnection()`

it gives me 400 error with this

`{"error":"invalid_request","error_description":"Cannot obtain user token based on the enterprise configuration for your app"}`

I am trying to do exactly whats given here https://github.com/kendomen/BoxJavaJWTExamples/blob/master/src/com/nike/box/GetAppUsersItems.java 
My App Config is as follows:
- Application Access: Enterprise (even tried that with Application)
- Advanced features : Generate User Access Tokens is turned on. 
- My private and public key both are generated. 

I am using box version 2.4.0

Am i doing something wrong here... ??

**Comment by herat007** [comment]
Sorry closed this by mistake.. Any help on this would be greatly appreciated.

**Comment by iamharish** [comment]
For security reasons apps have to configured in the enterprise, before they can request tokens. Please follow the guide
[Getting Started with Box Platform](https://developer.box.com/v2.0/docs/getting-started-box-platform)

**Comment by mguinness** [comment]
I had the same issue, but had already configured the app in the enterprise.  The trick was to select "Reauthorize app" which then allowed it to work.
