### ISSUE TITLE
Update javadocs for query parameter in BoxFolder.search(String)

### ISSUE THREAD

**Issue by gcurtis** [box/box-java-sdk#44]
It isn't very clear that the `query` parameter for `BoxFolder.search(String)` is supposed to be the query field and not a URL query string.

**Comment by jdgiotta** [comment]
This is pretty low priority change. I think the parameter name lines up with the platform documentation. Adding better copy for the description is what I think you're aiming for.

**Comment by pmeister** [comment]
How about some examples? It's not clear what the format is supposed to be.

**Comment by tarrencev** [comment]
Closing since this functionality is being deprecated. Please see the advanced search implementation, there best documentation is [this example](https://github.com/box/box-java-sdk/blob/master/src/example/java/com/box/sdk/example/SearchExamplesAsAppUser.java) until we get around to adding docs.
