### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/box/sdk/BoxAPIConnection

### ISSUE THREAD

**Issue by harshalyelpale** [box/box-java-sdk#445]
I have downloaded this sdk and trying to run "Main.java" file, but it gives exception in "BoxAPIConnection" class. 
See below exception:

Exception in thread "main" java.lang.NoClassDefFoundError: com/box/sdk/BoxAPIConnection

Caused by: java.lang.ClassNotFoundException: com.box.sdk.BoxAPIConnection at java.net.URLClassLoader$1.run(URLClassLoader.java:366)

**Comment by KarthikShanmugasundaram** [comment]
@harshalyelpale it is a classpath issue. Are you using gradle or maven. Please share the snippet. We like to see the SDK version you are trying to use.
Please share the IDE you are using for the development.

**Comment by harshalyelpale** [comment]
I'm using "box-java-sdk-2.4.0" (Maven Dependancy) version with ready JAR files (pre-compiled).

See below screenshot for IDE and error:
![java-sdk-boxerror](https://user-images.githubusercontent.com/29271510/27270718-d1f4aee2-54dd-11e7-9b98-f9dfb656565c.PNG)

**Comment by KarthikShanmugasundaram** [comment]
Box java SDK depends on the following. Please make sure these are included in your runtime classpath.

compile 'com.eclipsesource.minimal-json:minimal-json:0.9.1'
compile 'org.bitbucket.b_c:jose4j:0.4.4'
compile 'org.bouncycastle:bcprov-jdk15on:1.52'
compile 'org.bouncycastle:bcpkix-jdk15on:1.52'

**Comment by harshalyelpale** [comment]
@KarthikShanmugasundaram yes, you are right. And these packages included in compile time but not in runtime thats the reason of exception.
Thanks a lot :)
