### ISSUE TITLE
Where's the JWT Support?

### ISSUE THREAD

**Issue by MCalder423** [box/box-java-sdk#446]
I would like to do JWT authentication using the SDK, and it would be extremely helpful if there were some features that helped me generate the required JWT using the box-specific parameters such as box_sub_type, the correct iss value, and most importantly, support for RS256 keys.

Right now, I'm wallowing in a swamp of code trying to get this thing working with JWT and I *know* that this would not be happening if there were proper support for this in the SDK.

**Comment by iamharish** [comment]
@MCalder423 JWT based authentication is provided using `BoxDeveloperEditionAPIConnection`. Token generation can be further simplified by using a _generated_ config file for the app, which can be downloaded from developer console

Refer
[Examples](https://github.com/box/box-java-sdk#other-projects)

and example project
[CreateAppUser](https://github.com/box/box-java-sdk/blob/master/src/example/java/com/box/sdk/example/CreateAppUser.java)

**Comment by MCalder423** [comment]
Thank you iamharish.  I appreciate that there is example code, and that is very helpful.  That said, there is no actual place in the mainline box.com api documentation that connects someone to the example code.  I needed to post a lame, whiny plea for help on the forums to get this direction, and it should have been apparent from reading documentation.

Again, thank you for responding and putting me (hopefully) back on track, but this should not have been where I needed to go to get this information.

**Comment by MCalder423** [comment]
Just as a follow-up, I'm trying to run the example code and am getting a null pointer exception when trying to execute the CreateAppUser.main function:

"C:\Program Files\Java\jdk1.8.0_40\bin\java" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:58107,suspend=y,server=n -javaagent:C:\Users\marc.calder\.IntelliJIdea2017.1\system\groovyHotSwap\gragent.jar -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_40\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_40\jre\lib\rt.jar;C:\Users\marc.calder\Source\box-java-sdk-master\build\classes\example;C:\Users\marc.calder\Source\box-java-sdk-master\build\classes\main;C:\Users\marc.calder\.gradle\caches\modules-2\files-2.1\com.eclipsesource.minimal-json\minimal-json\0.9.1\9b409b88e38b11519ce3334cbcdda361462ac72d\minimal-json-0.9.1.jar;C:\Users\marc.calder\.gradle\caches\modules-2\files-2.1\org.bitbucket.b_c\jose4j\0.4.4\82deffa5cab3871084b47c24b467745c881996f0\jose4j-0.4.4.jar;C:\Users\marc.calder\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk15on\1.52\88a941faf9819d371e3174b5ed56a3f3f7d73269\bcprov-jdk15on-1.52.jar;C:\Users\marc.calder\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcpkix-jdk15on\1.52\b8ffac2bbc6626f86909589c8cc63637cc936504\bcpkix-jdk15on-1.52.jar;C:\Users\marc.calder\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.6\562424e36df3d2327e8e9301a76027fca17d54ea\slf4j-api-1.7.6.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2017.1\lib\idea_rt.jar" com.box.sdk.example.CreateAppUser
Connected to the target VM, address: '127.0.0.1:58107', transport: 'socket'
Disconnected from the target VM, address: '127.0.0.1:58107', transport: 'socket'
Exception in thread "main" java.lang.NullPointerException
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:444)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:390)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:300)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.tryRestoreUsingAccessTokenCache(BoxDeveloperEditionAPIConnection.java:368)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:179)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:206)
	at com.box.sdk.example.CreateAppUser.main(CreateAppUser.java:37)

Process finished with exit code 1

I downloaded my app config, put it in the config folder, then stepped through the code to ensure that it was being read in properly (it is), and then the line that tries to create the connection dies.

**Comment by iamharish** [comment]
I agree we could have more detailed logs but this was the reasoning of
current way it is

SDKs are not documented in the API Docs as API docs are, well not SDK docs.
But all the major features are mentioned there. Checkout
https://developer.box.com/docs/authentication-with-jwt#section-1-generating-an-rsa-keypair

And in SDKs github repo's README.md files, we have details on how to use
all those major features. Sadly there's a missing link between those
different locations. We will see how we can improve it

Seems like an issue with private key. Were you using a generated private
key or your own?
Private key has to be formatted to fit in a line, which means new line
chars '\n' has to be added where necessary, when copying. I would suggest
to use the auto-generated private key. That's secure and also Box doesn't
store any generated private key of developers.

If you want to try your own private key, try debugging to see if these two
lines work as intended and if the variables keyReader and keyPair are
populated with a private key

            PEMParser keyReader = new PEMParser(new
StringReader(this.privateKey));
            Object keyPair = keyReader.readObject();

Warm Regards,
Harish G

**Comment by MCalder423** [comment]
Hi Harish,
I used the auto-generated private key.  In the configuration tab for my application, I clicked the "Download as JSON" button, then took the downloaded file and copied it directly into the config folder in the example application.  Like I said above, I stepped through the code to make sure the file was being read properly, and it appeared to be, because the clientId and clientSecret fields were populated.  

However, within the jwyEncryptionPreferences object, the publicKeyId, privateKey, and privateKeyPassword fields were empty.  Do you think that might be where the problem is?

Thanks,
Marc

**Comment by MCalder423** [comment]
Hi Harish,
I had been using the auto-generated keys, but to make sure I hadn't messed anything up using an editor, I went ahead and using the developer console I generated a second public key.  I then took the downloaded json config file and copied it to the config folder in the example app.  I updated the source code of the CreateAppUser function to read the downloaded config file, and to set a proper name for the app user.  

When I executed the function in debug mode, I stepped through to ensure that the config file was being properly read in.  Executing the next line, which is the call to getAppEnterpriseConnection, the function errored out with an Illegal Key Size error.

I am pretty sure that I followed the proper method of getting that function to work and yet I get this error.  Unfortunately, this is holding up our entire project and if I can't get this solved in the next couple of days we are going to have to look at other options than box.com.

Here is a dump of the error:
`Connected to the target VM, address: '127.0.0.1:57920', transport: 'socket'
Exception in thread "main" com.box.sdk.BoxAPIException: Error parsing PKCS private key for Box Developer Edition.
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:452)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:390)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:300)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.tryRestoreUsingAccessTokenCache(BoxDeveloperEditionAPIConnection.java:368)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:179)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:206)
	at com.box.sdk.example.CreateAppUser.main(CreateAppUser.java:37)
Caused by: org.bouncycastle.pkcs.PKCSException: unable to read encrypted data: 1.2.840.113549.1.5.13 not available: Illegal key size
	at org.bouncycastle.pkcs.PKCS8EncryptedPrivateKeyInfo.decryptPrivateKeyInfo(Unknown Source)
	at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:441)
	... 6 more
Caused by: org.bouncycastle.operator.OperatorCreationException: 1.2.840.113549.1.5.13 not available: Illegal key size
	at org.bouncycastle.openssl.jcajce.JceOpenSSLPKCS8DecryptorProviderBuilder$1.get(Unknown Source)
	... 8 more
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1060)
	at javax.crypto.Cipher.init(Cipher.java:1536)
	at javax.crypto.Cipher.init(Cipher.java:1470)
	... 9 more
Disconnected from the target VM, address: '127.0.0.1:57920', transport: 'socket'

Process finished with exit code 1`

**Comment by cburnette** [comment]
Have you installed the proper JCE for your JVM (step 5 under Quickstart)?  It’s required to use the key size needed for Box JWT.

**Comment by MCalder423** [comment]
@cburnette Chad, you rock!!  I thought I had all the dependencies taken care of, but missed the JCE.  Thank you SO much for taking the time to point me in the right direction!
