### ISSUE TITLE
How to get Shared links?

### ISSUE THREAD

**Issue by misterfifi1** [box/box-java-sdk#455]
Hi, 

I would like to retrieve the folder ID from a shared link using the method documented here:
https://api.box.com/2.0/shared_items

Could you help me?

Regards,

**Comment by mattwiller** [comment]
Hi @misterfifi1 — you can get the item associated with a shared link like this:

```java
String sharedLink = "https://app.box.com/s/..."
BoxItem.Info item = BoxItem.getSharedLink(api, sharedLink);
String itemID = item.getID();
```

Can you give that a try and let me know if it works for you?
