### ISSUE TITLE
Potential Thread Locking Issue with making a Box API Call

### ISSUE THREAD

**Issue by telmperez** [box/box-java-sdk#466]
We're using version 2.4 of the Box Java SDK.

We're seeing odd intermittent issues when using the Box Java SDK where the call to Box hangs which causes our process to also hang and never complete. We're forced to perform a server restart when this happens. 

Here's a thread dump of where the call to Box hangs. Do we need to wrap the calls to Box on a separate thread? Is this something that the API already does for us internally? Has this happened to other users?

Thread 26609: (state = IN_NATIVE)
 - java.net.SocketInputStream.socketRead0(java.io.FileDescriptor, byte[], int, int, int) @bci=0 (Compiled frame; information may be imprecise)
 - java.net.SocketInputStream.read(byte[], int, int, int) @bci=87, line=152 (Compiled frame)
 - java.net.SocketInputStream.read(byte[], int, int) @bci=11, line=122 (Compiled frame)
 - sun.security.ssl.InputRecord.readFully(java.io.InputStream, byte[], int, int) @bci=21, line=442 (Compiled frame)
 - sun.security.ssl.InputRecord.read(java.io.InputStream, java.io.OutputStream) @bci=32, line=480 (Compiled frame)
 - sun.security.ssl.SSLSocketImpl.readRecord(sun.security.ssl.InputRecord, boolean) @bci=44, line=934 (Compiled frame)
 - sun.security.ssl.SSLSocketImpl.readDataRecord(sun.security.ssl.InputRecord) @bci=15, line=891 (Compiled frame)
 - sun.security.ssl.AppInputStream.read(byte[], int, int) @bci=72, line=102 (Compiled frame)
 - java.io.BufferedInputStream.fill() @bci=175, line=235 (Interpreted frame)
 - java.io.BufferedInputStream.read1(byte[], int, int) @bci=44, line=275 (Compiled frame)
 - java.io.BufferedInputStream.read(byte[], int, int) @bci=49, line=334 (Compiled frame)
 - sun.net.www.http.HttpClient.parseHTTPHeader(sun.net.www.MessageHeader, sun.net.ProgressSource, sun.net.www.protocol.http.HttpURLConnection) @bci=51, line=689 (Compiled frame)
 - sun.net.www.http.HttpClient.parseHTTP(sun.net.www.MessageHeader, sun.net.ProgressSource, sun.net.www.protocol.http.HttpURLConnection) @bci=56, line=633 (Compiled frame)
 - sun.net.www.protocol.http.HttpURLConnection.getInputStream() @bci=327, line=1324 (Compiled frame)
 - java.net.HttpURLConnection.getResponseCode() @bci=16, line=468 (Compiled frame)
 - sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode() @bci=4, line=338 (Compiled frame)
 - com.box.sdk.BoxAPIRequest.trySend(com.box.sdk.ProgressListener) @bci=360, line=416 (Interpreted frame)
 - com.box.sdk.BoxAPIRequest.send(com.box.sdk.ProgressListener) @bci=44, line=221 (Interpreted frame)
 - com.box.sdk.BoxAPIRequest.send() @bci=2, line=196 (Interpreted frame)
 - com.box.sdk.EventLog.getEnterpriseEvents(com.box.sdk.BoxAPIConnection, java.lang.String, java.util.Date, java.util.Date, com.box.sdk.BoxEvent$Type[]) @bci=225, line=111 (Interpreted frame)

**Comment by jacegangel** [comment]
I am also seeing this issue. I believe settings the connection timeout via BoxGlobalSettings. setConnectTimeout may force the error to evaluate, but that code was only recently merged and is currently failing the build.

**Comment by iamharish** [comment]
Released a [fix](https://github.com/box/box-java-sdk/releases/tag/v2.8.1). Should be in maven repo soon.
