### ISSUE TITLE
getThumbnail throws exception

### ISSUE THREAD

**Issue by kernelogic** [box/box-java-sdk#478]
No matter what file type is, image video pdf, it always throw this exception. Any idea?

The API returned an error code: 400
{"type":"error","status":400,"code":"requested_preview_unavailable","help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"Requested preview unavailable","request_id":"42029003059fa400f06c68"}

**Comment by towns** [comment]
Hi kernelogic.. can you share the code you have written that produces this error? Its hard to debug this without knowing what APIs you are calling and how you are calling them. If you could paste a snippet of your code into this issue, we can work further on this.

**Comment by kernelogic** [comment]
This is my code looks like, it's very straightforward.

            BoxFile boxFile = new BoxFile(utils.getEnterpriseBoxAPI(), "some box node ID");
            byte[] thumbnaildata = boxFile.getThumbnail(ThumbnailFileType.PNG, 144, 144, 144, 144);

**Comment by jmfrank63** [comment]
Hi kernellogic,

try a different size, only 32, 64, 128 and 256 are possible. From the documentation here:
https://developer.box.com/v2.0/reference#get-a-thumbnail-for-a-file

Sizes of 32x32, 64x64, 128x128, and 256x256 can be returned in the .png format
thus 144 returning "requested_preview_unavailable" is expected.
