### ISSUE TITLE
Bug report for EventStream.java: IllegalStateException in isDuplicate

### ISSUE THREAD

**Issue by nealwu** [box/box-java-sdk#48]
Hey Greg,

EventStream.java has the following method:

```
    /**
     * Indicates whether or not an event ID is a duplicate.
     *
     * <p>This method can be overridden by a subclass in order to provide custom de-duping logic.</p>
     *
     * @param  eventID the event ID.
     * @return         true if the event is a duplicate; otherwise false.
     */
    protected boolean isDuplicate(String eventID) {
        if (this.receivedEvents == null) {
            this.receivedEvents = new LinkedHashSet<String>(LRU_SIZE);
        }

        boolean newEvent = this.receivedEvents.add(eventID);
        if (newEvent && this.receivedEvents.size() > LRU_SIZE) {
            this.receivedEvents.iterator().remove();
        }

        return !newEvent;
    }
```

The line `this.receivedEvents.iterator().remove();` results in an IllegalStateException because you can't call `.remove()` on an iterator before calling `.next()`.

Also, `.iterator()` doesn't guarantee that the elements will be returned in any particular order, so if you just call `.remove()` on the first element you get, you'll effectively be removing an element at random. I'm not sure exactly what your intention was here, but I just wanted to double check on that since I myself have lost a bunch of time to that problem in the past.

Thanks!

**Comment by gcurtis** [comment]
Thanks! This is a good catch. It appears that we're missing a test for hitting the max LRU size (which would've caught this bug).

The iteration order should actually be predictable for a `LinkedHashSet` according to the javadocs:

> This linked list defines the iteration ordering, which is the order in which elements were inserted into the set (insertion-order).

So I think that this can be fixed by just calling `next()` before calling `remove()`.

**Comment by nealwu** [comment]
Oh nice call, I didn't check on `LinkedHashSet` in particular so that makes sense. And sure thing!
