### ISSUE TITLE
Java SDK usage for usecases involving inactive users

### ISSUE THREAD

**Issue by abhi8344** [box/box-java-sdk#483]
When you have  a BoxUser or BoxFolder Object created using the BOXAPIConnection Object of  an inactive user  the objects are unusable.
Method calls on the BoxUser/BoxFolder object throw 403/Unauthorized error.
 
If I want to for e.g iterate the list of folders an inactive user has, what  is the way out?

**Comment by carycheng77** [comment]
Hey @abhi8344, unfortunately if the user is set to inactive then the admin/user will not have access to the documents of the inactive user. However, if they have left your organization you can request to have the inactive user's content transferred over to another account(i.e admin or another Box Account).

Wondering what the use case here is to see if we provide a more prescriptive solution, thanks!

**Comment by abhi8344** [comment]
Well my requirement was to move any  contents of a disabled user  to the manager. I needed a valid handle to the root folder of the disabled user for some logic. My workaround was to enable the user, do my stuff and disable the  user again.

**Comment by carycheng77** [comment]
@abhi8344 Gotcha! Apologies for that, glad you were able to find a workaround and apologies for the late response. Going forward github issues will be addressed a lot more timely. Let us know if you have any other issues. 

Thanks!
