### ISSUE TITLE
Add isFile() and isFolder() convenience methods to BoxItem

### ISSUE THREAD

**Issue by gcurtis** [box/box-java-sdk#49]
These methods should simply return the result of an `instanceof` check. For example:

```
item.isFile() == (item instanceof BoxFile)
item.isFolder() == (item instanceof BoxFolder)
```

**Comment by mcmilwj** [comment]
How would I self-assign this enhancement request?

**Comment by gcurtis** [comment]
GitHub doesn't let me assign it to you because you aren't a member of the Box org, but feel free to take it!

**Comment by mcmilwj** [comment]
I was thinking something like this might be a little more future-proof:

```java
	public boolean isFile() {
		return BoxFile.class.isAssignableFrom(this.getClass());
	}
```

Thoughts?
