### ISSUE TITLE
Webhook Issue - METADATA_INSTANCE.UPDATED is not on the list of triggers

### ISSUE THREAD

**Issue by benjallen** [box/box-java-sdk#491]
It seems there is an issue in the Box Java SDK on which our production application was built. In particular, we attempt to set up a webhook on a folder and pass in a METADATA_INSTANCE.UPDATED trigger. The webhook does get created, however, when we inspect this webhook (using the native API or the Box CLI) METADATA_INSTANCE.UPDATED is not on the list of triggers.

We inspected the Java SDK source code on github and observed the trigger enumeration in the webhook class didn't have any METADATA triggers--this could explain what we have noticed.

If this is the case, is this a defect in the JDK? Can we request this get fixed as soon as possible? We have a production rollout coming up where this is crucial.

Thank you,

Ben Allen

**Comment by carycheng77** [comment]
Hey @benjallen, apologies for that! That's something that should definitely be included in the Java SDK. We'll work on a patch now and follow up, thanks!

**Comment by benjallen** [comment]
Thank you, @carycheng77  @mattwiller @iamharish !
