### ISSUE TITLE
No support for indefinite file locking

### ISSUE THREAD

**Issue by meavenson** [box/box-java-sdk#493]
Currently, there appears to be no support for indefinitely locking a Box file, as the two existing lock methods in BoxFile require a non-null expiry date to be supplied.  If you attempt to pass null instead of a Date object, a null pointer exception is thrown.

**Comment by carycheng77** [comment]
Hey @meavenson, thank you for letting us know, we'll get started on that fix!

**Comment by meavenson** [comment]
Thanks @carycheng77 !  I submitted a pull request for review, in case you'd like to use my fix.

**Comment by carycheng77** [comment]
#494
