### ISSUE TITLE
BoxFile.uploadVersion returns void

### ISSUE THREAD

**Issue by allenmichael** [box/box-java-sdk#518]
When uploading a new version of a file, the BoxFile.uploadVersion method returns `void` while the other methods for uploading (`BoxFolder.uploadLargeFile`, `BoxFile.uploadLargeFile`, `BoxFolder.uploadFile`) all return type `BoxFile.Info`. It may be convenient for consistency to have an `uploadVersion` method that returns `BoxFile.Info`.

**Comment by mattwiller** [comment]
Good catch, we can definitely add a new method (something like `BoxFile.uploadNewVersion` that returns the BoxFile.Info) and mark the old one as deprecated.
