### ISSUE TITLE
We need help( we are in trouble now) about BoxFolder.search () method

### ISSUE THREAD

**Issue by Yushi-I** [box/box-java-sdk#525]
The BoxFolder.search () method seems to be deleted from Box-SDK-2.9.0,
We using BoxFolder.search () for searching folders using the previous SDK.
(We use SDK ver.box-java-sdk-2.0.0)
When searching 1-byte characters with only alphanumeric characters in the folder name, there is no problem in response
Although there are 2-byte characters including Japanese names, "Bad Request"
It will be a response to the error.
Because of this malfunction, there is a failure that can not create a folder etc. by API linkage.
Support team  told to use the latest Java SDK.
But we have introduced the system more than one year ago, and the renovation costs and man-hours are.
Because it takes so, it can not be updated.
Below is the time of success and failure when creating folder name including Japanese on our side,
Since something has been worsened during this time period please restore it.
Last successful time: 1/9 (Tue) at 14:00(JP Time)
Time of first failure: 1/10 (Wed) 8: 00(JP Time)
I doubt that there was a system renovation in the above time zone.

**Comment by mattwiller** [comment]
Hi @Yushi-I — the BoxFolder.search() method has been deprecated, but has not actually been removed yet.  You should still be able to use it for now.  It will be removed in a future 3.0.0 version of the SDK.  If you want to stop using the deprecated method, please see the [search documentation](https://github.com/box/box-java-sdk/blob/master/doc/search.md) for how to use the new method.

For the folder creation error, can you please provide more details?  What is an example of a call that is failing for you?  Or, could you send an email to me at mwiller@box.com with your API key so I can investigate?

**Comment by mattwiller** [comment]
@Yushi-I I looked at our server logs from 2018-01-01 until today, and I don't see any of the Bad Request errors that you described for your application.  Can you please show me the stack trace and error message of the error you saw, the error response body from the API, or the code that's failing (including an example of a name with a double-byte character that's not working)?  Without more information I'm not able to look into this issue.

**Comment by Yushi-I** [comment]
@mattwiller Below is the information remaining in the log file.
Response message
<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>

Error log
--- [http-nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.box.sdk.BoxAPIException: The API returned an error code: 400] with root cause

2018-01-18 14:20:04　名称：DN_ASホストマシン（task_id:1136854）
2018-01-18 14:30:05　名称：女川町新庁舎ネットワーク案件（task_id:1136872）

**Comment by mattwiller** [comment]
@Yushi-I Thank you for the additional information!  Unfortunately, I'm still not sure what's causing the error you're seeing.  I tried the following code examples in the latest version of the SDK (v2.10.0) and they all worked correctly for me:

Searching using legacy (deprecated) search method with provided string:
```java
BoxAPIConnection api = new BoxAPIConnection(accessToken);
Iterable<BoxItem.Info> results = BoxFolder.getRootFolder(api).search("女川町新庁舎ネットワーク案件");
```

Searching using new search method with provided string:
```java
BoxAPIConnection api = new BoxAPIConnection(accessToken);
BoxSearch boxSearch = new BoxSearch(api);
BoxSearchParameters searchParams = new BoxSearchParameters();

searchParams.setQuery("女川町新庁舎ネットワーク案件");
PartialCollection<BoxItem.Info> results = boxSearch.searchRange(0, 10, searchParams);
```

Creating a folder with the provided string:
```java
BoxAPIConnection api = new BoxAPIConnection(accessToken);
BoxFolder root = BoxFolder.getRootFolder(api);
BoxFolder.Info jpFolder = root.createFolder("女川町新庁舎ネットワーク案件");
```

Additionally, the latest version of the SDK (v2.10.0) should be backwards-compatible with the version you are currently using (v2.0.0).  Are you running into any specific issues when upgrading to the newer version?  There should not be any breaking changes between the versions, so code written to work with v2.0.0 should also work with v2.10.0.  No changes to your application code should be necessary.

To help me continue troubleshooting, can you please provide the following information?
1. Can you please provide the full error message and stack trace for the BoxAPIException you're seeing?  This information would be very useful for me to understand what might be happening in the SDK.
2. Can you provide the code from your application that is generating this error (with any private information removed)?  What method are you calling and what inputs are you passing into it?
3. Are you seeing these errors with version 2.0.0 of the SDK, version 2.9.0, or both?
4. Are you using a proxy server between your application and the Box API?

**Comment by Yushi-I** [comment]
@mattwiller Ill answer the questions below.
1.Under the condition that it is operating as an application, detailed information can not be acquired.
2.Below is the excerpt of the corresponding part.
--------
BoxFolder rootFolder = BoxFolder.getRootFolder(boxAPIConnectManager.getAPIConnect());

Iterable＜BoxItem.Info＞ boxItemInfoIte = rootFolder.search(
        CommonUtil.makeBoxFolderSearchQuery(input.getBoxFolder().getFolderName()));
for(BoxItem.Info itemInfo : boxItemInfoIte){
    // 親がルートフォルダのみチェック対象とする
    if (itemInfo.getParent().getID().equals(rootFolder.getID())){
            // フォルダに対してのみチェックを行う
            if (itemInfo instanceof BoxFolder.Info) {
                BoxFolder.Info folderInfo = (BoxFolder.Info) itemInfo;
                // フォルダ名が一致するかチェック
                if(folderInfo.getName().equals(input.getBoxFolder().getFolderName())){
                    // DB検索：Boxフォルダ情報【一致したBoxフォルダIDで検索】
                    CtcBoxFolder duplBoxFolder = ctcBoxFolderService.findByBoxFolderId(folderInfo.getID());
                    if(duplBoxFolder == null){
                        // BoxとDB：Boxフォルダ情報のデータ不整合
                        responce.setResponceCd(RESPONCE_CD_WCL_MISSMATCH_DB);
                        responce.setBoxFolderInfoId(folderInfo.getID());
                        return responce;
                    }
                    // Box API：フォルダ名更新
                    folderInfo.setName(duplBoxFolder.getFolderName());
                    BoxFolder folder = new BoxFolder(boxAPIConnectManager.getAPIConnect(), folderInfo.getID());
                    folder.updateInfo(folderInfo);
                    break;
                }
            }
        }
    }
--------
3.An error occurs in ver2.0.0. we can not be tried with ver2.9.0.  even at ver2.10.0.
4.Proxy does not use, but there are products that control traffic(named A10).

**Comment by mattwiller** [comment]
Thank you for the additional information @Yushi-I — based on the additional information you provided we were able to reproduce the issue in our environment.

I forwarded this issue to one of our API teams at Box for further investigation and they are currently looking into it.  I'll update you here when I have a response from them.

**Comment by mattwiller** [comment]
@Yushi-I Our API team has applied a fix, and my testing shows that the API should be working correctly with double-byte characters now.  Can you please confirm if the issue is fixed for you?

**Comment by Yushi-I** [comment]
Hi matt.

Thanks for your reply.

I confirmed it, and I was able to create a folder containing more than 2 
bytes of characters.

Thanks for your help and Thanks for your fix.
I am very grateful to you.

Plz close this case.
