### ISSUE TITLE
Large File Upload fails if file size is > 2,147,483,647

### ISSUE THREAD

**Issue by pmatte1** [box/box-java-sdk#530]
Because the _processed_ variable in the uploadParts method of the LargeUploadFile is declared as an int it is maxed at  2,147,483,647.  However, the upload should handle files much larger than this, and therefore this creates a bug condition once the byte size exceeds  2,147,483,647.

The processed variable needs to be declared as a long, as it was done for the offset and filesize variables within that method.

![image](https://user-images.githubusercontent.com/35776253/35347356-e9d4b274-0102-11e8-9883-2e8c18c919e3.png)

**Comment by mattwiller** [comment]
The fix for this issue has been released in v2.11.0 of the SDK
