### ISSUE TITLE
BoxUser method moveFolderToUser does not have the ability to disable notifications

### ISSUE THREAD

**Issue by rjainrohit** [box/box-java-sdk#532]
When moving a folder from one user to another provide provisions to disable notifications.

**Comment by mattwiller** [comment]
Hi @rjainrohit — this looks like the same issue as #327 to me.  Could you try the workaround posted there and let me know if it works for you?  We're looking into options for how to make these sort of headers easier to set across endpoints, but for now you may need to set the header manually.

**Comment by rjainrohit** [comment]
Hi @mattwiller It did not work. I tried adding the Request interceptor to admin api and it started giving me insufficient privileges error at the time of getting BoxUserInfo for a Box user. So its not working in admin api for sure. We are programmatically making changes to the user's login and do not want any notifications to be sent. In fact we want to disable all notifications from box during our user provisioning process.

**Comment by mattwiller** [comment]
@rjainrohit Per the [API documentation](https://developer.box.com/v2.0/reference/#suppressing-notifications), changes to a user's login cannot have notifications suppressed — that would explain why you're seeing the permissions error there.
