### ISSUE TITLE
Get a thumbnail for a file

### ISSUE THREAD

**Issue by gcurtis** [box/box-java-sdk#54]

**Comment by mugglmenzel** [comment]
+1
Would be great to at least have a method in BoxFile which generates the thumbnail URL given width and height parameters (from an enum).

**Comment by havinash** [comment]
Yes, I agree. Methods to generate thumbnails will be very helpful.
Also, Box automatically generates thumbnails and previews for most of the files that gets uploaded. It will be awesome if there are methods to the get the public url of these generated thumbnails.

**Comment by xavier-figueroa** [comment]
it seems to be fixed with https://github.com/box/box-java-sdk/issues/191

**Comment by tarrencev** [comment]
Closed by #192
