### ISSUE TITLE
java.lang.OutOfMemory on Large File Upload

### ISSUE THREAD

**Issue by pmatte1** [box/box-java-sdk#541]
When doing a large file upload on extremely large files (example 3gb file), the way uploadParts is implemented allows for the opportunity where too many LargeFileUploadTask objects, which hold the upload bytes, overrun the available Heap space.  This is because the ThreadPoolExecutor will queue up additional tasks, and with large files, the size of each part is large, and the time to execute the upload of that part is much longer.

Currently the only control in place is a 1 second delay if all current pool workers are occupied, which is not enough for these large scale documents.

**EXAMPLE**
I am testing with a 3gb document, where each part is 8.3mb, and the average upload time is >1 minute.  With the current logic, there are hundreds of queued LargeFileUploadTask objects, because they are only closing out 1 every minute.

This is made worse under a threaded condition, as the threads will share the available memory.

**RECOMMENDED SOLUTION:**
The simplest solution is to only read new bytes, and construct and queue the LargeFileUploadTask if the current Queue length is less than a certain value.  The recommended size of the queue is 1.5 times the number of processing threads.

That will allow the developer to control the memory consumption based upon the number of parallel threads being configured for execution in the LargeFileUpload class.

**Comment by mattwiller** [comment]
Fixed by #543
