### ISSUE TITLE
Best way to authenticate using box-java-sdk

### ISSUE THREAD

**Issue by pbhattad-scs** [box/box-java-sdk#555]
Hi,
I am using box-java-sdk and authenticating in this below way

BoxAPIConnection api = new BoxDeveloperEditionAPIConnection(USER_ID, DeveloperEditionEntityType.USER, boxConfig, accessTokenCache);

Looking at the example as mentioned in the class "BoxDeveloperEditionAPIConnectionAsEnterpriseUser.class"

I am using the json config file which is generated using the Enterprise account. 
Can you tell me if this is the right way of accessing box.? My application is web based and will be used by many users at the same time.

Thanks,
Priyanka

**Comment by pbhattad-scs** [comment]
Thanks carycheng.

I think it is quite similar to what I am using (DeveloperEdition). Will change to this. 
I have another question: When I upload anything on Box, it doesn't recognize the new upload immediately. I have read that the it takes some time, just wanted to know if I m missing anything here...?

thank you.

**Comment by carycheng** [comment]
Hey @pbhattad-scs, 

If you try to download the file immediately after uploading the file may not be [ready](https://developer.box.com/v2.0/reference/#download-a-file).

<img width="733" alt="screen shot 2018-02-09 at 1 36 57 pm" src="https://user-images.githubusercontent.com/6364733/36051333-97c99cf8-0d9e-11e8-852b-340656f923d0.png">

Is download the action you were trying to perform on the newly uploaded file?
