### ISSUE TITLE
BoxUser.moveFolderToUser throws User is locked error

### ISSUE THREAD

**Issue by abhi8344** [box/box-java-sdk#556]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
// Replace this text with a description of what problem you're having.  
// Please include as much detail as possible to help us troubleshoot!  
// If it isn't obvious, please include how the behavior you expect differs from what actually happened.  
// This is really important so we know how to start troubleshooting your issue.

### Versions Used
Java SDK: // Replace with the version of the Java SDK you're using.  
Java: // Replace with the version of Java your application is running on.

### Steps to Reproduce
// Please include detailed steps to reproduce the issue you're seeing, if possible.  
// If you don't have a reproducible error, please make sure that you give us as much detail  
// as you can about what your application was doing when the error occurred.  
// Good steps to reproduce the problem help speed up debugging for us and gets your issue resolved sooner!

### Error Message, Including Stack Trace
// Replace with the full error output you're seeing, if applicable.  
// Please include the full stack trace to help us identify where the error is happening.

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

I am trying to move the root folder of an user to another user using the BoxUser.moveFolderToUser method. The response i get is given below and this error is not consistent/reproduceable

Response Code : 409
Response Message : {"type":"error","status":409,"code":"conflict","help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"User is locked","request_id":"4lom59fo9c8asoq0"}

Both the users are in active state when the api is invoked.

There isn't a locked status for users in box so this error probably isn't about the user status.

**Comment by carycheng** [comment]
Hey @abhi8344, will take a look at this

If possible could you email us your api key to ccheng@box.com so we can dig into this? Thanks!

**Comment by mattwiller** [comment]
Hi @abhi8344 — the error you're seeing means that there are already large folder operation locks held on the the source user account.  This likely means there is already a big move or something like that happening on that account, and another one cannot be performed at this time.  In this scenario, you should wait and try the operation again later.

**Comment by abhi8344** [comment]
@mattwiller The method fails in between the transfer so it successfully transferred some files and failed to transfer some .

**Comment by mattwiller** [comment]
@abhi8344 In this case, the transfer may still be in progress (hence the 409 status code, a new transfer cannot be started while the old one is running).  Can you check to see if items are still being moved?

**Comment by abhi8344** [comment]
The move has stopped and the code does not try to start another transfer. Also this method call returns  a handle to the moved folder in the target user directory once the transfer is complete.

**Comment by mattwiller** [comment]
@abhi8344 When your application sees a 409, you should retry the move later to avoid any ongoing operation.  If you retry it now, does it succeed?

**Comment by abhi8344** [comment]
@mattwiller  No i have not done that since it is something that is not reproducible in dev  env.
Here are the possible consequences of  doing that
1 ) The BoxUser.moveFolderToUser  creates a folder with the name in a certain way so there would be a item name already in use error thrown 
2) It starts creating copies of the folder suffixing the name with the (1) (2) etc. which is not desirable

I still do not understand how a folder move from one user to another could get into a locked state when no other move/copy  transactions are  initiated in either of these user accounts at that time. I really want to understand the behavior of the underlying rest apis(not the sdk) in this scenario .Is there any documentation ?

**Comment by mattwiller** [comment]
@abhi8344 I don't personally have much information on the specifics of how accounts are locked during file and folder operations; if you have a specific question about your account I would recommend [contacting Box Support](https://community.box.com/t5/Contact-Support/ct-p/BoxSupport#) since they have the access and tools to help diagnose that sort of issue much better than I can.

In general, I would recommend that if you get a 409 error on this endpoint, you should either:
1) Check the root folder of the destination user to verify if the move operation was started and you're getting a conflict with it — if not, retry
2) Just retry without checking, which might leave you with empty folder created with a (1) or (2) suffix that you can simply delete
