### ISSUE TITLE
canViewPath cannot be unset on existing collabs

### ISSUE THREAD

**Issue by jasonpan12** [box/box-java-sdk#558]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
The canViewPath parameter of collaborations can be set for a new collaboration, but not view or modify the parameter after that. There appears to not be a canViewPath variable in the collaboration:
https://github.com/box/box-java-sdk/blob/master/src/main/java/com/box/sdk/BoxCollaboration.java#L169

### Versions Used
Java SDK: 2.4.0

### Steps to Reproduce
Create a collaboration like so:
collaborate(BoxCollaborator collaborator, BoxCollaboration.Role role, Boolean notify, Boolean canViewPath)

cmd+f for canViewPath on [this page](http://opensource.box.com/box-java-sdk/javadoc/com/box/sdk/BoxFolder.html)

I'm not sure what happens if that is set to false or not - customer reported (I'm a boxer) and wanted to make this for due diligence per our internal convos :)

### Error Message, Including Stack Trace
No errors, I think the issue is just that the functionality isn't there?

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
#560
