### ISSUE TITLE
NullPointerException when calling BoxFolder.getChildrenRange

### ISSUE THREAD

**Issue by mylimaye** [box/box-java-sdk#566]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue - Yes

### Description of the Issue
Box Java SDK is throwing NullPointerException - when we are trying to fetch the contents of a folder. Here are related top frames of the Exception

java.lang.NullPointerException: null 
com.box.sdk.BoxResource.parseInfo(BoxResource.java:87) 
com.box.sdk.BoxFolder.getChildrenRange(BoxFolder.java:512)

This is happening only for few of the users. Our code, which calls the BoxFolder.getChildrenRange() looks like

try { 
BoxFolder folder = new BoxFolder(connection, folderId); 
boxColl = folder.getChildrenRange(offset, batchSize, "name", "parent", "size", "created_at", 
"content_modified_at", "modified_by", "owned_by", "version_number", "item_status", 
"path_collection"); 
} 
// catch and handle the exceptions

### Versions Used
Java SDK: 2.12.0
Java: 1.8.0_152

### Steps to Reproduce
It is not reproducible always. Only of few of our users are seeing this issue - when trying to access the contents of a folder.

### Error Message, Including Stack Trace
Null Pointer Exception is thrown with the stack looking like the one pasted above.

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Thanks for reporting this @mylimaye, we will look into this!

**Comment by mattwiller** [comment]
@mylimaye Could you please give us some more information about this error?  Does this error always occur on same folder, or is it on different folders?  When you say that some users see the error, is it consistent, e.g. does the same user always get the error when working on a specific folder?  For some reason, the stack trace you pasted doesn't line up with the actual code; for example, [BoxResource.java:87 is an empty line](https://github.com/box/box-java-sdk/blob/2e792592ba0e8a9159047e9a4219f556902d7c60/src/main/java/com/box/sdk/BoxResource.java#L87) when I look at what the codebase looked like in v2.12.0 — weird.

**Comment by mylimaye** [comment]
@mattwiller - apologies for wrong information. We have moved to v2.12.0 recently - but didn't realize that the stack trace belonged when we were using v2.3.0

**Comment by mylimaye** [comment]
We have noticed one particular user has been getting this exception when trying to fetch contents of root folder

**Comment by mattwiller** [comment]
@mylimaye Just double-checking, are you still seeing this error after the upgrade to v2.12.0?  A [fix was made to this area of the code in v2.4.0](https://github.com/box/box-java-sdk/commit/7a690178da4c84e45dadf9960b95dabcae4c32f2) that looks like it would prevent this error in cases where the user had a web_link item in the folder.  These items aren't very common, so it might explain why it's just some users that see the problem.

**Comment by mylimaye** [comment]
Thanks for the information @mattwiller . I will monitor for this issue in our application for a day. If not, I will close this issue.

**Comment by mylimaye** [comment]
@mattwiller - I am closing this issue, as we are no longer seeing it after upgrading to latest version of Box Java SDK. If I see the issue again, I will open a new issue with fresh stack trace
