### ISSUE TITLE
Sort by relevance with search query

### ISSUE THREAD

**Issue by Arvind6353** [box/box-java-sdk#574]
Hi ,
Is there a way to sort the search results by relevance.?

I am unable to find a way to search the Box with sort.

Can you let me know if by default the box sdk search sorts by relevance .

**BoxSearch boxSearch = new BoxSearch(serviceAccountClient);
			
Am using searchRange function**

**Comment by carycheng** [comment]
Hey @Arvind6353,

The search is sorted by relevance by default but the API does not allow for any additional sorting parameter. 

Let us know if you have any additional questions or if there is anything else we can help with, thanks!
