### ISSUE TITLE
User.moveFolderToUser throwing "access_denied_insufficient_permissions"

### ISSUE THREAD

**Issue by abhi8344** [box/box-java-sdk#585]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
// Replace this text with a description of what problem you're having.  
// Please include as much detail as possible to help us troubleshoot!  
// If it isn't obvious, please include how the behavior you expect differs from what actually happened.  
// This is really important so we know how to start troubleshooting your issue.

### Versions Used
Java SDK: // Replace with the version of the Java SDK you're using.  
Java: // Replace with the version of Java your application is running on.

### Steps to Reproduce
// Please include detailed steps to reproduce the issue you're seeing, if possible.  
// If you don't have a reproducible error, please make sure that you give us as much detail  
// as you can about what your application was doing when the error occurred.  
// Good steps to reproduce the problem help speed up debugging for us and gets your issue resolved sooner!

### Error Message, Including Stack Trace
// Replace with the full error output you're seeing, if applicable.  
// Please include the full stack trace to help us identify where the error is happening.

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

The User.moveFolderToUser is failing for with the error  "access_denied_insufficient_permissions" after March 23rd.

Box support says that the user moving the folder has to be a admin/co-admin but i am sure and i have logs/evidence showing that it worked without the user being an admin/co-admin. 

Has there been any change/bug fixed in the underlying rest api's that this method is invoking?

https://api.box.com/2.0/users/boxuserid/folders/0

**Comment by mattwiller** [comment]
@abhi8344 This does not sound like an SDK issue, but rather on with the API — if you're in contact with Box Support they are better suited to handle this question.  We have not made any change to how this API endpoint is called in the SDK since it was originally implemented 3 years ago.
