### ISSUE TITLE
Is there an api to  add & remove co-admin role to/from an user? 

### ISSUE THREAD

**Issue by abhi8344** [box/box-java-sdk#586]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
// Replace this text with a description of what problem you're having.  
// Please include as much detail as possible to help us troubleshoot!  
// If it isn't obvious, please include how the behavior you expect differs from what actually happened.  
// This is really important so we know how to start troubleshooting your issue.

### Versions Used
Java SDK: // Replace with the version of the Java SDK you're using.  
Java: // Replace with the version of Java your application is running on.

### Steps to Reproduce
// Please include detailed steps to reproduce the issue you're seeing, if possible.  
// If you don't have a reproducible error, please make sure that you give us as much detail  
// as you can about what your application was doing when the error occurred.  
// Good steps to reproduce the problem help speed up debugging for us and gets your issue resolved sooner!

### Error Message, Including Stack Trace
// Replace with the full error output you're seeing, if applicable.  
// Please include the full stack trace to help us identify where the error is happening.

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@abhi8344 The [Update User API endpoint](https://developer.box.com/v2.0/reference/#update-a-users-information) should allow you to change a user's role to Co-Admin.  You can use this in the SDK using the [`BoxUser#updateInfo() method`](https://github.com/box/box-java-sdk/blob/master/doc/users.md#update-user).
