### ISSUE TITLE
Moving folder across accounts

### ISSUE THREAD

**Issue by abhi8344** [box/box-java-sdk#587]
- [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
// Replace this text with a description of what problem you're having.  
// Please include as much detail as possible to help us troubleshoot!  
// If it isn't obvious, please include how the behavior you expect differs from what actually happened.  
// This is really important so we know how to start troubleshooting your issue.

### Versions Used
Java SDK: // Replace with the version of the Java SDK you're using.  
Java: // Replace with the version of Java your application is running on.

### Steps to Reproduce
// Please include detailed steps to reproduce the issue you're seeing, if possible.  
// If you don't have a reproducible error, please make sure that you give us as much detail  
// as you can about what your application was doing when the error occurred.  
// Good steps to reproduce the problem help speed up debugging for us and gets your issue resolved sooner!

### Error Message, Including Stack Trace
// Replace with the full error output you're seeing, if applicable.  
// Please include the full stack trace to help us identify where the error is happening.

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

The rest apis exposed by box to transfer the root folder of one user to another takes two params the sourceuserid and the destinationuserid

https://api.box.com/2.0/users/$sourceuserid/folders/0

There is an authorization header with the Bearer token and the $destinationuserid is passed as ownedby in the body.

The corresponding  java SDK method in the BoxUser Class takes only one parameter  public BoxFolder.Info moveFolderToUser(String sourceUserID)  and the destinationuserid is the boxuser id of the BoxUser object the method is invoked on.

My requirement  is to move the root folder of an user to another user and both the users have "USER" role.When i invoke the method i get an error "insufficient permission error" probably because the destination user is not at admin.

It looks to me like the REST apis are more flexible in fulfilling this requirement wherein i can use the token of an admin and pass the source and the destination user box id.
 Am I missing something here?

**Comment by mattwiller** [comment]
@abhi8344 That's correct — the user whose token is used to call the API must be an Admin or Co-Admin, but the two users who you are transferring content to and from can be ordinary managed users.  However, the source and destination users must be in the Admin's enterprise.  Is that the case for the token owner, source user, and destination user for your API call?

**Comment by mattwiller** [comment]
@abhi8344 The [`moveFolderToUser()`](https://github.com/box/box-java-sdk/blob/master/doc/users.md#move-users-folder) method is the one you're looking for.  The `BoxUser` that you call the method on is the source user, and you pass the destination user ID to the method:

```java
BoxUser sourceUser = new BoxUser(api, sourceUserID);
sourceUser.moveFolderToUser(destinationUserID);
```

**Comment by abhi8344** [comment]
I am already using this method…. The problem with this method is that the source user has to be an admin.

Whereas if I use the REST api I can pass 3 variables

The api token of an admin in the Authorization header
The $destinationuserid in the ownedby param
The sourceuserid in the url

Do you see my point ?

**Comment by mattwiller** [comment]
@abhi8344 The SDK does not impose any restrictions on the source or destination user — it just calls the REST API with the IDs.  If you're getting a permission error, chances are that the user whose token the SDK is using is not an Admin — are you sure you're setting up the `BoxAPIConnection` with the correct credentials?  Which user are you using in the SDK vs. when you call the REST API manually, and how are you getting those tokens?
