### ISSUE TITLE
Get folder items and read the JSON response (entries list)

### ISSUE THREAD

**Issue by duc30** [box/box-java-sdk#591]
- [x]  I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue.

### Description of the Issue
I am trying to retrieve the files with the associated metadata template within a folder with a single request to the Box API (through the Box Java SDK).
I am using the “fields” param in the following API request :
```
GET https://api.box.com/2.0/folders/<folderId>/items?fields=metadata.enterprise.<metadata_template_name>,modified_at,name,size
```
I found out in the Box Java SDK the piece of code which is triggering the above request :
```
String fields = "metadata.enterprise.<metadata_template_name>,modified_at,name,size";
for (BoxItem.Info itemInfo : boxFolder.getChildren(fields)) {
	// Do something
}
```
But… I did not find in the SDK a straightforward way to read the JSON response.
We just need to read the "entries" list in the JSON response (files information + metadata) **without having to send additional requests to the Box API for performance optimization purposes.** 

### What we don't want to do
```
for (BoxItem.Info itemInfo : boxFolder.getChildren(fields)) {
	if (itemInfo instanceof BoxFile.Info) {
		BoxFile file = ((BoxFile.Info) itemInfo).getResource();
		BoxFile.Info fileInfo = file.getInfo(); // <--- This line causes a new request to the Box API and we want to avoid that.
	}
}
```

### Versions Used
Java Box SDK: 2.9.0
Java: 1.8

### Questions
**Am I supposed to use the BoxAPIRequest and BoxAPIResponse classes directly ?
Is there another way to avoid doing it manually ? 
Please note that it is impacting one of our projects in a professional environment.
Thanks for your help.**

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @duc30, 

Could you try out this snippet and see if this works? 
```Java
        BoxFolder boxFolder = new BoxFolder(api, "");
        String fields = "metadata.enterprise.<metadata_template_name>,modified_at,name,size";
        for (BoxItem.Info itemInfo : boxFolder.getChildren(fields)) {
        	if (itemInfo instanceof BoxFile.Info) {
        		Metadata metadata = ((BoxFile.Info) itemInfo).getMetadata("<metadata_template_name>", "enterprise");
        	}
        }
```

Thank you!

**Comment by duc30** [comment]
Hi @carycheng,

Thank you for your reply.

I tried your snippet and I was able to read the file information but the getMetadata() method causes a new call to the Box API.
Despite this, it allowed me to reach my target.

Regards,

Duc
