### ISSUE TITLE
Uploading new version of a file makes its size zero

### ISSUE THREAD

**Issue by madhmeht** [box/box-java-sdk#594]
- [x] I have checked that the [SDK documentation][https://github.com/box/box-java-sdk/blob/master/doc/files.md] [API documentation][https://developer.box.com/reference] doesn't solve my issue

While uploading a file, I use BoxFolder#uploadFile(fileContents, fileName) method. It throws an error if a file with the same name exists. In the catch block, I use File#uploadVersion(stream) to upload the new version. This method does not throw any error but the file size of the new version is **zero**. 

If I use BoxFolder#canUpload(fileName, 98734576), this also throws the same error. The new version uploaded in the catch block gets uploaded correctly with the correct size. 
I am not sure what gets enabled on backend after this preflight check. 
If I am uploading 20 files out of which just 2 files already exist on Box, I would prefer to make 22 API requests instead of 40 API requests.  

### Versions Used
Java SDK: JDK 8u101
Box sdk - box-java-sdk:2.15.0

[sdk-docs]: (https://github.com/box/box-java-sdk/blob/master/doc/files.md)
[api-docs]: (https://developer.box.com/reference)

**Comment by mattwiller** [comment]
@madhmeht I suspect that the `fileContents` stream you're using is getting completely consumed in the first upload attempt, so when you retry as uploading a new version there are no bytes to send and you get an empty file uploaded.  Could you try resetting or recreating the stream you're using for the file contents and see if that fixes the problem?

**Comment by madhmeht** [comment]
Apologies for the late reply. You were correct, the stream was getting consumed that's why uploaded file had zero size.
