### ISSUE TITLE
Missing Attributes in the Get Collaboration

### ISSUE THREAD

**Issue by rjainrohit** [box/box-java-sdk#599]
- [X ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
The REST API returns more attributes than the SDK. Currently missing what we need is accessible_by "Login Id".

In situations when missing properties in the class is there a way via the SDK to view the JSON response and parse it ourselves in our program?

### Versions Used
Java SDK: // Replace with the version of the Java SDK you're using.  
Java: // Replace with the version of Java your application is running on.

### Steps to Reproduce
NA

### Error Message, Including Stack Trace
NA

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by rjainrohit** [comment]
Hey @carycheng getID() returns the Box user ID and I am looking for Login (email address) very similar what the REST API returns when getting the collaboration info.

**Comment by carycheng** [comment]
Hey @rjainrohit, 

I've added a getter for the Login, the pr can be found here #602 

Thank you!

**Comment by mattwiller** [comment]
@rjainrohit We just released v2.19.0 of the SDK, which includes a `.getLogin()` method on `BoxCollaboration.Info` — hope that helps!
