### ISSUE TITLE
Clarification for authenticating BOX using BOXApi SDK

### ISSUE THREAD

**Issue by pbhattad-scs** [box/box-java-sdk#600]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
// Replace this text with a description of what problem you're having.  
// Please include as much detail as possible to help us troubleshoot!  
// If it isn't obvious, please include how the behavior you expect differs from what actually happened.  
// This is really important so we know how to start troubleshooting your issue.

### Versions Used
Java SDK: // Replace with the version of the Java SDK you're using.  
Java: // Replace with the version of Java your application is running on.

### Steps to Reproduce
// Please include detailed steps to reproduce the issue you're seeing, if possible.  
// If you don't have a reproducible error, please make sure that you give us as much detail  
// as you can about what your application was doing when the error occurred.  
// Good steps to reproduce the problem help speed up debugging for us and gets your issue resolved sooner!

### Error Message, Including Stack Trace
// Replace with the full error output you're seeing, if applicable.  
// Please include the full stack trace to help us identify where the error is happening.

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @pbhattad-scs,

It looks like you've made an empty issue. What specifically in authentication are you looking for assistance with?

Thank you!

**Comment by pbhattad-scs** [comment]
Hi carycheng

I am have created a custom app and authorising as  OAuth 2.0 with JWT (Server Authentication).
I am using this example to authenticate 
## code 1
` BoxAPIConnection api = new BoxDeveloperEditionAPIConnection(USER_ID, DeveloperEditionEntityType.USER, boxConfig,accessTokenCache); 
`
I do not want to use USER_ID as it would need to store the admin name/id. instead I want to use it as
## code 2
```
Reader reader = new FileReader("src/example/config/config.json");
 BoxConfig boxConfig = BoxConfig.readFrom(reader);

 BoxDeveloperEditionAPIConnection api = BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(
	                boxConfig, accessTokenCache)

```
What settings do I need to change to configure this as above? Also which is the right approach which should be used?.

For the code1 , now the box is not displaying the file and says "This shared file or folder link has been removed or is unavailable to you." 
How do I fix this.?

Thanks,
Priyanka

**Comment by carycheng** [comment]
Hey @pbhattad-scs, 

Code snippet 2 looks correct and is a good approach to achieve what you're trying to do. Wondering if you had any specific questions about the settings(i.e scopes, app setup)? 

As far as the error you are seeing, are you seeing that inside the Box Webapp or via an API response? Any additional information or screenshots would be very helpful, thanks!

**Comment by carycheng** [comment]
Hey @pbhattad-scs, 

You will need to head over to the developer console to generate a config.json file. You can follow the steps found [here](https://developer.box.com/v2.0/docs/authenticate-with-jwt) to get started. 

As far as scopes go and granting the correct set of permissions to your token, you can specify that in the developer console -> select/create your app -> "Configuration" tab on the left column. 

You should see this: 
<img width="1232" alt="screen shot 2018-05-05 at 9 46 40 am" src="https://user-images.githubusercontent.com/6364733/39728320-3f24d34a-520b-11e8-810e-28d1619e8991.png">

This will allow you to control the permissions your app will have over your content. 

Let us know if this was helpful, thanks!

**Comment by pbhattad-scs** [comment]
Hi Carycheng,

Thanks for the reply. I configured the application as Enterprise and selected all the checkboxes for the scope except the last one. I have the json.config. 

It connects to the box app using the code snippet 2. However, when I try to use get the rootFolder

`BoxFolder rootFolder = BoxFolder.getRootFolder(api);` 

It doesn't return the rootFolder, it returns null. The api here is BoxDeveloperEditionAPIConnection api

What wrong am I doing? 

Thanks,
Priyanka

**Comment by pbhattad-scs** [comment]
After connecting to the Box App, I am trying to get all the folders which are present in my app, which would help me to decide which folder I want to search to get all the files.

When I was using the code snippet 1 as mentioned in the earlier comments,  
`BoxFolder rootFolder = BoxFolder.getRootFolder(api);` is working fine. but when I changed the way I connect to code snippet 2, it doesn't work.

**Comment by mattwiller** [comment]
@pbhattad-scs That code you have above should work — I just downloaded a new configuration JSON file from the Developer Console and tested the following code on my machine and it worked fine:

```java
FileReader reader = new FileReader("/Users/mwiller/Downloads/951173_f9cdw0uh_config.json");
BoxConfig boxConfig = BoxConfig.readFrom(reader);

BoxDeveloperEditionAPIConnection api = BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(
        	                boxConfig, null);

BoxFolder rootFolder = BoxFolder.getRootFolder(api);

Assert.assertNotNull(rootFolder); // this succeeds!
```

Are you seeing any sort of Exception or other error?  Does your configuration JSON file have all of the required properties (e.g. `clientID`, `clientSecret`, `appAuth.privateKey`, `enterpriseID`)?

**Comment by pbhattad-scs** [comment]
Leave a comment

**Comment by mattwiller** [comment]
@pbhattad-scs Ahh, I think I see what you mean — the root folder is accessible, but it's the root folder of the Service Account used by your app, not the Admin.  These are two totally separate accounts, with their own folders and files.  Please see the [SDK authentication docs](https://github.com/box/box-java-sdk/blob/master/doc/authentication.md#server-authentication-with-jwt) and the [Service Account documentation](https://developer.box.com/v2.0/docs/service-account) for more information.  To access the admin's files and folders as the Service Account, you'll need to ensure that the "Perform Actions As Users" feature is turned on for your application in the Developer Console and call `api.asUser('ADMIN_USER_ID');` to act as the admin user and make calls on their account.

**Comment by pbhattad-scs** [comment]
@mattwiller  thanks for the links. I have enabled the "Perform Actions As Users" feature for the app.
However, I cannot use the code `api.asUser('ADMIN_USER_ID');`

**Comment by mattwiller** [comment]
@pbhattad-scs You'll need to make sure you or your enterprise admin re-authorizes the application in the Enterprise Settings page — any permission or scope changes for the app need to be re-approved before they take effect.
