### ISSUE TITLE
Parsing private key exception - simple example

### ISSUE THREAD

**Issue by mangelo123** [box/box-java-sdk#605]
I am running a very simple example with the boxConfig.json that was generated:

```
public class BoxAPITest {

	
	public static void main(String[] args) {

		BoxAPITest test = new BoxAPITest();
		try {
			Reader reader = new FileReader(test.getFileName("boxConfig.json"));
			BoxConfig boxConfig = BoxConfig.readFrom(reader);
			
			// Set cache info
			int MAX_CACHE_ENTRIES = 100;
			IAccessTokenCache accessTokenCache = new 
			  InMemoryLRUAccessTokenCache(MAX_CACHE_ENTRIES);

			// Create new app enterprise connection object
			BoxDeveloperEditionAPIConnection client = 
			  BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(boxConfig, accessTokenCache);

			// PERFORM ACTIONS WITH CLIENT
		}
		catch (Exception e) {
			System.out.println(e);
		}
	}
	
	private String getFileName(String filename) {
		ClassLoader cl = getClass().getClassLoader();
		String absoluteFilename = cl.getResource(filename).getFile();
		
		return absoluteFilename; 
	}

}
```

I get the following:

`com.box.sdk.BoxAPIException: Error parsing PKCS private key for Box Developer Edition.`

**Comment by carycheng** [comment]
Hey @mangelo123, 

Have you authorized your app in your enterprise admin console yet?

You can find directions [here](https://community.box.com/t5/How-to-Guides-for-Admins/Enabling-Custom-Built-Applications/ta-p/2188)

Thank you!

**Comment by mangelo123** [comment]
I am not the one that can do that, but will check. I could expect a parsing error if it has not been authorized? Another developer got further than I using the NodeJS example.

**Comment by mangelo123** [comment]
It was the security policy. Working now.
