### ISSUE TITLE
addHeader methot works wrong

### ISSUE THREAD

**Issue by KVolodymyrABTO** [box/box-java-sdk#611]
https://github.com/box/box-java-sdk/blob/b881194f9a65cf44f9f400a72f7d9892e24e66dc/src/main/java/com/box/sdk/BoxAPIRequest.java#L168

You can't call indexOf(String) for List of RequestHeader, so this line always will return "-1" an user can add several "As-User" headers that will cause 403 response from server

**Comment by carycheng** [comment]
Hey @KVolodymyrABTO, 

If possible could we get more context behind what you are trying to do? A code snippet would be very helpful as well. 

Are you adding multiple request headers to your Box API Request before sending it over? 

Thank you!

**Comment by KVolodymyrABTO** [comment]
Hi @carycheng ,
I doesn't have some special case, I have a program that manage Box files using Admin account, so I need to add "As-User" header to request, and some times I war retrieve 404 error from server:
`com.box.sdk.BoxAPIException: The API returned an error code: 404
{"type":"error","status":404,"code":"not_found","context_info":{"invalid_user_id":{"id":"21655****, 21655****"}},"help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"On-Behalf-Of User not found","request_id":"pzp6z4frfrl2nqwl"}`
After debug I was found that some times when I try to add "As-User" header it already present in headers list, as I understand, from your code,  "As-User" header should by only one, but 
`int index = this.headers.indexOf("As-User"); ` always will return -1 and "As-User" header will be added anyway.

However, did you look at code I was link? Look what is "headers" list - it `List<RequestHeader>` and did you think that `indexOf("As-User")` for this list return correct index.

**Comment by KVolodymyrABTO** [comment]
@mattwiller Thanks for fix
