### ISSUE TITLE
Move of Files between one folder to another folder using BoxFolders iterator doesn't automatically handle paging  and make additional API calls to load more data when more than 1000 files, it only moves maximum 1000 files.

### ISSUE THREAD

**Issue by alkleela** [box/box-java-sdk#617]
- [Yes] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Move of Files between one folder to another folder using BoxFolders iterator as indicated in [(https://github.com/box/box-java-sdk/blob/master/doc/folders.md#get-a-folders-items)], doesn't automatically grab the next batch of file. Basically it doesn't automatically handle paging and  make additional API calls to load more data  when the number of files are more than 1000, it only moves 
maximum1000 files.

### Versions Used
Java SDK: box-java-sdk-2.20.1 , box-java-sdk-2.8.2 jars
Java: "1.8.0_144 : Java(TM) SE Runtime Environment (build 1.8.0_144-b01), 1.7.0_79 : Java(TM) SE Runtime Environment (build 1.7.0_79-b15)

### Steps to Reproduce
I have around 1010 files in a folder, and was using the below code to move the files.
`
        String fldrID = "50073256125"; //1010 files
        String newFldrId=  "50070316320" ; //empty folder
        BoxItem.Info mvdItemInfo = null;
        
        BoxFolder boxFolder = new BoxFolder(dr.getUserApi(),fldrID);
        BoxFolder newFldr = new BoxFolder(dr.getUserApi(),newFldrId);
        for(BoxItem.Info itemInfo : boxFolder){            
            if(itemInfo instanceof BoxFile.Info){
                try {                                
                    mvdItemInfo = ((BoxFile)itemInfo.getResource()).move(newFldr);
                  
                } catch (BoxAPIException b) {
                   System.out.println("exception in moving file itemid:"+((BoxFile)itemInfo.getResource()).getID());
                    b.printStackTrace();
                    throw b;
                }
            }
        }
`

### Error Message, Including Stack Trace
No error message or exception thrown.

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
https://github.com/box/box-java-sdk/blob/master/doc/folders.md#get-a-folders-items

**Comment by mattwiller** [comment]
@alkleela This is due to the fact that you're moving items out of the folder while iterating over it — the iterator does try to get the second page of items, but when it requests the second page with `limit=1000&offset=1000` the folder only has 10 items left in it so none are returned from the API.  I would recommend using the iterator to create a `List<String>` of file IDs, and then move those files by doing something like:

```java
BoxFile f = new BoxFile(api, fileID);
f.move(newFldr);
```
