### ISSUE TITLE
Unable to set a Shared Link Password

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/box-java-sdk#622]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
In order to create a shared link with a password, we have to revert to the HTTP calls. The SDK does not provide the means to set a password

### Versions Used
Java SDK: 1.8  
Java: 1.8

### Steps to Reproduce
Create File. Create a Sharedlink. You can set the Download etc and even check if a link is password enabled but not set one.

### Error Message, Including Stack Trace
NA

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
java class https://github.com/box/box-java-sdk/blob/master/src/main/java/com/box/sdk/BoxSharedLink.java

**Comment by carycheng** [comment]
Hey @jacquesvandermerwe, 

Sorry about that, we have a pr out for this now, you can track it at #623

**Comment by carycheng** [comment]
Hey @jacquesvandermerwe, 

We have just released v2.21.0 version of the SDK with the ability to create passwords for shared links included. 

Let us know if there are other issues you may come across, thanks!
