### ISSUE TITLE
"Quick Test", "Getting Started" links in README.md 404

### ISSUE THREAD

**Issue by mhuisman** [box/box-java-sdk#625]
- [X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
README.md line 31 "Getting Started Section..." link to https://developer.box.com/v2.0/docs/getting-started-box-platform 404s.

README.md line 36 "Following things work only if..." link to https://developer.box.com/v2.0/docs/configuring-box-platform 404s.

### Versions Used
https://github.com/box/box-java-sdk README.md master

### Steps to Reproduce
1. navigate to https://github.com/box/box-java-sdk/blob/master/README.md 
2. click "here" link in Quick Test section
3. view 404 page at : https://developer.box.com/v2.0/docs/configuring-box-platform
4. repeat for "Getting Started Section" link to https://developer.box.com/v2.0/docs/getting-started-box-platform

### Error Message, Including Stack Trace
404 not found [screenshot](https://i.imgur.com/ISCFDNo.png)

### Suggested Remedy ###

Perhaps change both links to point to - https://developer.box.com/docs/getting-started-box-view ?  If acceptable I could easily knock out a PR.

Thanks!

**Comment by carycheng** [comment]
Hey @mhuisman, 

Thanks for writing in! Apologies for any inconvenience, we have a PR out for this now. You can track this at #626, thanks!

**Comment by carycheng** [comment]
Hey @mhuisman, fix has been merged and will be going out with our Thursday release. Let us know if you come across anything else, thanks!
