### ISSUE TITLE
Box API - JWT Authentication in JAVA throwing error as decryptPrivateKeyInfo(Unknown Source)

### ISSUE THREAD

**Issue by AshnaKazi** [box/box-java-sdk#628]
I am following Box article on https://github.com/box/box-java-sdk, and have installed JCE as instructed(We are located in US) and it did not fix our issue. 

### Description of the Issue
I am trying to upload the files to Box(via Box API) using a service account, with JWT authentication.

I have set up a custom APP in Box, and is authorized by Admin. The Appication access is set to "Application", and application scope includes "Read/write all files/fodlers in Box" and "Mange Users". The Advanced Features is to "Generate User Access Token"

I am able to access the files using a Box developer token from this Box App.

But while using JWT authentication I am getting the error as at line
BoxDeveloperEditionAPIConnection client = BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(boxConfig, accessTokenCache);

### Versions Used
Java SDK: 1.8
Java: Java Version 8 Update 151  

### Steps to Reproduce
Below is the code I am following:

// Read config file into Box Config object
Reader reader = new FileReader("F:\\BOX_CONNECTOR\\config\\48245_f10g2l6t_config.json");
BoxConfig boxConfig = BoxConfig.readFrom(reader);

// Set cache info
int MAX_CACHE_ENTRIES = 100;
IAccessTokenCache accessTokenCache = new InMemoryLRUAccessTokenCache(MAX_CACHE_ENTRIES);

BoxDeveloperEditionAPIConnection client =
BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(boxConfig, accessTokenCache);

// PERFORM ACTIONS WITH CLIENT

String filePath = "E:\\emltopdf-app-strap03.txt";
String fileName = "TESTJWT";
String folderId = "***number removed for privacy***99";

// Select Box folder
BoxFolder folder = new BoxFolder(client, folderId);

// Upload file
FileInputStream stream = new FileInputStream(filePath);
BoxFile.Info newFileInfo = folder.uploadFile(stream, fileName);
stream.close()

### Error Message, Including Stack Trace
Exception in thread "main" java.lang.NoSuchFieldError: id_hmacWithSHA3_224
at org.bouncycastle.openssl.jcajce.PEMUtilities.<clinit>(Unknown Source)
at org.bouncycastle.openssl.jcajce.JceOpenSSLPKCS8DecryptorProviderBuilder$1.get(Unknown Source)
at org.bouncycastle.pkcs.PKCS8EncryptedPrivateKeyInfo.decryptPrivateKeyInfo(Unknown Source)
at com.box.sdk.BoxDeveloperEditionAPIConnection.decryptPrivateKey(BoxDeveloperEditionAPIConnection.java:504)
at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:450)
at com.box.sdk.BoxDeveloperEditionAPIConnection.constructJWTAssertion(BoxDeveloperEditionAPIConnection.java:431)
at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDeveloperEditionAPIConnection.java:320)
at com.box.sdk.BoxDeveloperEditionAPIConnection.tryRestoreUsingAccessTokenCache(BoxDeveloperEditionAPIConnection.java:419)
at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:199)
at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(BoxDeveloperEditionAPIConnection.java:226)
at com.acc.ecm.cap.box.FolderIter_JWT.main(FolderIter_JWT.java:114)
g.

[sdk-docs]: https://github.com/box/box-java-sdk
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @AshnaKazi, 

I just tried the below snippet and was able to upload a file 
```Java
    public void testUploadMethod() throws IOException {
        BoxDeveloperEditionAPIConnection client = null;
        Reader reader = new FileReader("src/test/config/config.json");
        BoxConfig boxConfig = BoxConfig.readFrom(reader);

        client = BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(boxConfig);

        String filePath = "/Users/ccheng/Desktop/pic.jpg";
        String fileName = "TESTJWT";
        String folderId = "0";

        // Select Box folder
        BoxFolder folder = new BoxFolder(client, folderId);

        // Upload file
        FileInputStream stream = new FileInputStream(filePath);
        BoxFile.Info newFileInfo = folder.uploadFile(stream, fileName);
        stream.close();
    }
```

Curious how you got your config.json? Did you download it from the dev console?

**Comment by AshnaKazi** [comment]
Hi carycheng,

I downloaded the json after clicking on the “Generate a Private/Public KeyPair”. I also tried it by regenerating the second one(for same application), and tried using this new json. Still it gave same error.

Below is my
API KEY/ Client ID: 4k6bolx4mwrtjkgrsbc6sox7e421fh5q


Thanks,

Ashna Kazi
Enterprise Content Management
Accenture India - Mumbai
Mobile(India) :  +91-9833887059

**Comment by carycheng** [comment]
Resolved from user advocate so closing this out. 

Please reach back out to us if you have any other issues!
