### ISSUE TITLE
file mimeType information not present in BoxFile or boxFile.getInfo() Objects

### ISSUE THREAD

**Issue by prashantharshi** [box/box-java-sdk#629]
I am using box java sdk. I also need file mimetype info apart from other metadata fields, but i dont see any getter function for that in the BoxFile object and neither in BoxFile.info object. How to get the mimetype of the file ? 

version i am using is : 
<dependency>
        <groupId>com.box</groupId>
        <artifactId>box-java-sdk</artifactId>
      <version>2.20.1</version>
  </dependency>

**Comment by prashantharshi** [comment]
Our use case is that we need some file metadata fields like name , downloadurl , mimetype which we need to pass in our REST api. But i am not getting this field in the file metadata method. i assume file mimetype is a very common field , any reason its not been return in metadata object ? any hack or workaround to fetch the same ?

**Comment by carycheng** [comment]
Hey @prashantharshi, 

We do not return the mime type directly, however on the file object there is a field named `extension` that indicates the encoding (file format) of the file contents or usage. 

This should allow you to infer the mime type from that, let us know if this helps, thanks!
