### ISSUE TITLE
Some times got exception "ParseException: Expected value at 1:0"

### ISSUE THREAD

**Issue by KVolodymyrABTO** [box/box-java-sdk#630]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
// Replace this text with a description of what problem you're having.  
// Please include as much detail as possible to help us troubleshoot!  
// If it isn't obvious, please include how the behavior you expect differs from what actually happened.  
// This is really important so we know how to start troubleshooting your issue.

### Versions Used
Java SDK: // Replace with the version of the Java SDK you're using.  
Java: // Replace with the version of Java your application is running on.

### Steps to Reproduce
// Please include detailed steps to reproduce the issue you're seeing, if possible.  
// If you don't have a reproducible error, please make sure that you give us as much detail  
// as you can about what your application was doing when the error occurred.  
// Good steps to reproduce the problem help speed up debugging for us and gets your issue resolved sooner!

### Error Message, Including Stack Trace
// Replace with the full error output you're seeing, if applicable.  
// Please include the full stack trace to help us identify where the error is happening.

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by KVolodymyrABTO** [comment]
Some times got exception: 
com.eclipsesource.json.ParseException: Expected value at 1:0 
at com.eclipsesource.json.JsonParser.error(JsonParser.java:371) 
at com.eclipsesource.json.JsonParser.expected(JsonParser.java:364) 
at com.eclipsesource.json.JsonParser.readValue(JsonParser.java:97) 
at com.eclipsesource.json.JsonParser.parse(JsonParser.java:62) 
at com.eclipsesource.json.JsonValue.readFrom(JsonValue.java:105) 
at com.eclipsesource.json.JsonObject.readFrom(JsonObject.java:138) 
at com.box.sdk.BoxAPIResponseException.<init>(BoxAPIResponseException.java:43) 
at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:90) 
at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:553) 
at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:326) 
at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:301) 
at com.box.sdk.BoxFile.getVersions(BoxFile.java:612)

I can't describe steps to reproduce this exception, because it is random issue. So maybe you can add some external logging or try to catch this exception itself

**Comment by carycheng** [comment]
Hey @KVolodymyrABTO, 

We need a little more info in order to dig into this, can you possibly email me the request id from the exception if you have it, if not the api key would be greatly appreciated, thank you!

**Comment by mattwiller** [comment]
@KVolodymyrABTO What version of the SDK are you using?  We addressed an error similar to this in v2.20.1 recently.

**Comment by KVolodymyrABTO** [comment]
Hi @carycheng and @mattwiller. I was make research and found that your fix in newer version should work. Thanks for reply. I'll update SDK and if problem will repeat I inform.
