### ISSUE TITLE
Populate enterprise id in BoxCollaborator.Info to Identity if collaborator is external

### ISSUE THREAD

**Issue by rjainrohit** [box/box-java-sdk#631]
- [X ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I want to identify if the collaboration is accessible by enterprise managed user or external user.  
When I call BoxCollaboration.getAccessibleBy() if it can provide me enterprise id I can then identify if the user is external or not.

### Versions Used
Java SDK: 2.19  
Java: 1.8

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@rjainrohit The `BoxCollaborator.Info` object returned from `getAccessibleBy()` should have the user ID available via `getID()` — if that's not working for you, could you provide a code sample showing what you're trying to do and what isn't working?

**Comment by rjainrohit** [comment]
@mattwiller sorry typo here I meant enterprise id not entity id. I have updated the Issue. The real objective here is to identify in the collaboration object if the BoxCollaborator.Info object returned from getAccessibleBy() is external or managed user.

**Comment by mattwiller** [comment]
@rjainrohit Thanks for the clarification!  Unfortunately, the Box API does not return the user's enterprise ID with the collaboration object; it is not possible for the SDK to provide that data.  One option you could try is to get the user's login email address by calling `getLogin()` on the `BoxCollaborator.Info` object and see if the user is from your enterprise or not that way.

**Comment by rjainrohit** [comment]
@mattwiller This approach will only work if that particular email domain is exclusive to our enterprise.  We could have users for belonging to same email domain both managed and external users of box. 

Any other suggestion on how to identify if the collaborator is external or managed?

**Comment by mattwiller** [comment]
@rjainrohit Unfortunately, I can't recommend any other way to do this since the data is not returned by the API.  I'll file a ticket internally to see if we can get something added to the API to resolve this issue, but for now there's nothing we can do in the SDK to work around it.
