### ISSUE TITLE
Type missing in BoxItem#Info

### ISSUE THREAD

**Issue by jmoore315** [box/box-java-sdk#634]
- [X ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
BoxItem does not include `type` as an exposed field. This seems to be a major oversight - there is no way to check if an item is a file or folder. 

### Versions Used
Java SDK: 2.8.2
Java: 1.8.144

### Steps to Reproduce
Retrieve a BoxItem via an API call. There is no way to see what the item is except `getResource()` and performing a bunch of `isInstanceOf` checks... yikes.

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @jmoore315 

That is definitely a gap, in the meantime you can get around it by using

```java
        BoxAPIConnection api = new BoxAPIConnection("");
        BoxFolder folder = new BoxFolder(api, "12345");
        String resourceType = BoxResource.getResourceType(folder.getClass());
```

If you have the Info class you can do
```java
        BoxAPIConnection api = new BoxAPIConnection("");
        BoxFolder folder = new BoxFolder(api, "");
        BoxItem.Info folderInfo = folder.getInfo();
        String folderResource = BoxResource.getResourceType(folderInfo.getResource().getClass());
```

Apologies for it not being intuitive! Let us know if that works and we'll work on getting type in as an exposed field as well. 

Thank you!
