### ISSUE TITLE
JDK TCP CONNECTION ISSUE

### ISSUE THREAD

**Issue by jtrujillo3** [box/box-java-sdk#642]
- [X ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Upgrading from 2.14.0 to 2.21.0 it was discovered a network related issue with latest version of BOX SDK. Using box-java-sdk-2.14.0.jar it does not allow BOX connection if the server time does not match with BOX Server time.  This has been tested with version 15 onwards with the core issue being higher number of TCP connections observed for the same input parameters for a data migration utility. 

### Versions Used
Java SDK: 2.14 and 2.21 tested

### Additional Details
For both the scenarios:
-code is the same
-all the utility parameters are the same
-for the utility they specify 100 threads and 50 users
-they upload one directory with the 10 000 files, each file 12 bytes
-the same Linux node

Scenario 1: the utility + box-java-sdk-2.14.0.jar
-during uploading ~100 TCP sessions seen

Scenario 2: the utility + box-java-sdk-2.21.0.jar
-during uploading up to 3000 TCP seen

**Comment by carycheng** [comment]
Hey @jtrujillo3, 

With the Java SDK release today we merged @pmatte1 fix for the TCP Connection issue. Let us know if that solves the issue, thanks!
