### ISSUE TITLE
The Search API return irrelevant search results

### ISSUE THREAD

**Issue by hxwhou** [box/box-java-sdk#645]
- [x] I have checked that the https://github.com/box/box-java-sdk/blob/master/doc/search.md and https://developer.box.com/v2.0/reference#searching-for-content doesn't solve my issue

### Description of the Issue
When I invoke the search API, it always return many irrelevant search results. This will make our users cannot get what they want result and have some concerns.

### Versions Used
Java SDK: 2.0  
Java: 1.8.

### Steps to Reproduce
1. Open the box on Browser
2. Type the file name, such as "UAT Scenario 3 Replace Artifact URL_Workflow.png"
3. Select the search scope in specified folder
4. Click the search button to get the result.

### Return many irrelevant search results 
The search result include many items which name only match the word '3'

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @hxwhou, 

Just to clarify, are you running a search inside the Box web application or are you specifically using the box-java-sdk to make a call against the search endpoint?

**Comment by hxwhou** [comment]
I used the box-java-sdk in our application and the same result in box web application.

**Comment by carycheng** [comment]
Hey @hxwhou, 

Unfortunately the box-java-sdk just acts as a wrapper around the search endpoint. However, there are certain thing you can try setting to limit the search results that come back. For example the query params found [here](https://developer.box.com/v2.0/reference#searching-for-content)

Let us know if that helps and please let us know if you come across any issues.

Thanks!
