### ISSUE TITLE
access_denied_insufficient_permissions on file collaborator 

### ISSUE THREAD

**Issue by ajayaks** [box/box-java-sdk#648]
Hi, 

I am trying to add collaborator on file via below, I can upload file without adding collaborator.

BoxFile.collaborate("email", BoxCollaboration.Role.EDITOR, true, true);

But getting below error while uploading:-

com.box.sdk.BoxAPIResponseException: The API returned an error code [403 | zdyag3fvfy4zokod] access_denied_insufficient_permissions - Access denied - insufficient permission
	at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:92) ~[box-java-sdk-2.23.0.jar:na]
	at com.box.sdk.BoxJSONResponse.<init>(BoxJSONResponse.java:32) ~[box-java-sdk-2.23.0.jar:na]
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:551) ~[box-java-sdk-2.23.0.jar:na]
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:326) ~[box-java-sdk-2.23.0.jar:na]

Other question I have is, 
How to do data classification on file via SDK?

Regards
Ajay

**Comment by carycheng** [comment]
Hey @ajayaks, 

The 403 means that you don't have the correct access level with the token you are using in the BoxAPIConnection. What scopes do you have for your application in the developer console?

**Comment by ajayaks** [comment]
Hi carycheg,
I have assigned below scopes to my application.
1. Manage users
2. Manager groups.
3. Read and write to files in box.

What are other scopes required for adding the collaborator?
How to do data classification on file via SDK?

Regards
Ajay

**Comment by ajayaks** [comment]
Hi carycheg, 

With same access token  i am able to create collaborator via api call like below.
curl https://api.box.com/2.0/collaborations \
-H "Authorization: Bearer <>" \
-d '{"item": { "id": "<>", "type": "file"}, "accessible_by": { "id": "<>", "type": "user" }, "role": "editor"}' \
-X POST 

And i can see the collaborator also on file but as explained in above thread its not working when i use with sdk.
collaborate("<email>", BoxCollaboration.Role.EDITOR, true, true);
  and getting same 

com.box.sdk.BoxAPIResponseException: The API returned an error code [403 | ei6fbrfvlx84697m] access_denied_insufficient_permissions - Access denied - insufficient permission

Please suggest.
Regards
Ajay

**Comment by ajayaks** [comment]
Hi, 

I cound not find that option(can_view_path).

Along with that i was trying to do below via code but could not find any option.

![image](https://user-images.githubusercontent.com/7519767/46051378-fe3d1c00-c0ed-11e8-8f58-0b625d687af1.png)

Can we set "People in the file" option from SDK while creating the shared link via code.

**Comment by ajayaks** [comment]
Hi carycheg, 
Its working but somehow i had setup the collaborator on folder level and after that i have gone to folder setting -> Shared link Access -> Files and folders.

After that with token i m able to upload the file in that folder but while creating a shared link via i am getting 403 forbidden, user which i m using is the owner of the application and folder also.


com.box.sdk.BoxAPIResponseException: The API returned an error code [403 | 5hwhzjfvn2e4pk0u] forbidden - Forbidden
	at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:92) ~[box-java-sdk-2.23.0.jar:na]
	at com.box.sdk.BoxJSONResponse.<init>(BoxJSONResponse.java:32) ~[box-java-sdk-2.23.0.jar:na]

BoxSharedLink.Permissions permissions = new BoxSharedLink.Permissions();
permissions.setCanDownload(true);
permissions.setCanPreview(true);
BoxSharedLink sharedLink = file.createSharedLink(BoxSharedLink.Access.OPEN, null, permissions);

I tried with even with BoxSharedLink.Access.Collaborator .

In any case shared link is not generating if i have done the setting on folder level.


If i remove that check from folder setting then its creating shared link, please suggest.

Intension is if set the collaborator manually and enable the folder setting then all files in folder can be accessed by the collaborator only hence no need to add collaborator on file level but i need the shared link after file upload via code ,where i am getting 403 exception.
Regards
Ajay

**Comment by carycheng** [comment]
Hey @ajayaks, 

Can you please check if you have additional folder settings flipped on? 

If you go into your Box account, right click on a folder and select `settings` you should be able to go to the folder settings page. On that page, look for a section called `Shared Link Access` - it should look like this

<img width="1210" alt="screen shot 2018-10-01 at 5 26 56 pm" src="https://user-images.githubusercontent.com/6364733/46322717-5d43da80-c59f-11e8-9daa-d777429e795a.png">

Can you please let us know if you have this feature flipped on? 

Thank you

**Comment by ajayaks** [comment]
Its working once you set the collaborator on folder level then no need to set the permission, it should be null.
Thanks for your support, we can close this ticket.
Regards
Ajay

**Comment by carycheng** [comment]
Hey @ajayaks, 

Thank you for letting us know, if you come across any other issues with the Java SDK please write in.

Thanks!
