### ISSUE TITLE
Add authorization header in Notification URL

### ISSUE THREAD

**Issue by yogaredhat** [box/box-java-sdk#650]
Hey Team,

I was trying to call the notification URL when FILE_UPLOADED event got triggered using webhhok.  I am using one of my Rest End point as a notification URL  and my rest end point support https basic auth or oauth only if the authoriztion header is present. However as per the current box webhook set up , I do not see any option to add the authorization header for the notification URL.  Is there any way I can add auth header in notification  URL.

BoxWebHook.Info webhookInfo = BoxWebHook.create(file, "rest end point", BoxWebHook.Trigger.FILE_DOWNLOAD)

Thanks

**Comment by carycheng** [comment]
Hey @yogaredhat, 

Are you trying to add your own auth header to the notification URL for when Box sends the request?

If so Box does not support this capability unfortunately, however, would love to hear more about your use case. Maybe there is another way we can tackle this, thanks!

**Comment by yogaredhat** [comment]
we have a vendor app that put a file in our shared box folder. we would like to create a webhook that triggered when a file_uploaded in our shared folder and notify our rest api (that support httpbasic and oauth ) so that app on our side download the file and process it .  let me know if you need any additional details from my end.

**Comment by yogaredhat** [comment]
Hey @carycheng,

Any suggestion on how can we get the header added to notification URL?

**Comment by carycheng** [comment]
Hey @yogaredhat, 

Unfortunately that functionality is not available today for webhooks. We cannot attach arbitrary headers. The endpoint you are authenticating on must be publicly accessible.
