### ISSUE TITLE
Feature Request: Move maxrequestsattempts to Globalsettings

### ISSUE THREAD

**Issue by Band-Aid** [box/box-java-sdk#656]
- [ X I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
This is a feature request to move setMaxRequestAttempts to GlobalSettings.
Is there a reason this is BoxAPIConnection based instead of a global setting?

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@Band-Aid I just opened a PR that should solve the issue — we'll put the fix into the next SDK release.
