### ISSUE TITLE
Box folders are listing Bookmarks as files causing 404's when fetching files

### ISSUE THREAD

**Issue by nddipiazza** [box/box-java-sdk#663]
### Description of the Issue
Box folder's [getChildren method](https://github.com/box/box-java-sdk/blob/master/src/main/java/com/box/sdk/BoxFolder.java#L595) returns Bookmarks and files alike. Bookmarks are returned as `BoxItem.Info` which are actually `instanceof BoxFile.Info`. Next my application wants to download the files that we listed from the folder. This results in my application not having any way to determine the child `BoxFile.Info` objects are bookmarks or a real files so we have no choice but to make unneeded requests that always result in 404 response for bookmarks.

### Versions Used
Java SDK: 2.14.0
Java: Java 8 181

### Steps to Reproduce
We came to realize this by using getChildren on folders to list files within. We then download the file content. Upon doing this, we were getting many 404s which made us worry. We contacted box support and they let us know these 404's were in fact expected because they were bookmarks, not actual files.

Is there a way to tell a `BoxItem.Info` is a bookmark?

The biggest issue here is there is no way to discern is this file actually deleted since we called "getChildren" or is it a bookmark?

**Comment by carycheng** [comment]
Hey @nddipiazza, 

This issue should be resolved in the newer versions of the Java SDK. The current one is [v2.24.0](http://opensource.box.com/box-java-sdk/)

I would try updating and see if the issue persists. I tried with the below snippet and was able to distinguish between Bookmarks and Box Files.

```java
    public void getChildrenDistinguishesBoomarkandFile() throws IOException {
        BoxAPIConnection api = new BoxAPIConnection("ACCESS-TOKEN");
        BoxFolder folder = new BoxFolder(api, "FOLDER-ID");
        Iterable<BoxItem.Info> folderItems = folder.getChildren();
        for (BoxItem.Info item : folderItems) {
            if (item instanceof BoxFile.Info) {
                System.out.println("Item: " + item);
				// Download here
            }
        }
    }
```

Let me know if this solves your issue, thank you!
