### ISSUE TITLE
[security] Elliptic Curve Key Disclosure in Jose4J

### ISSUE THREAD

**Issue by sumerjabri** [box/box-java-sdk#664]
- [X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Jose4J version used is < 5.5, and is vulnerable to elliptic curve key disclosure. See https://app.snyk.io/vuln/SNYK-JAVA-ORGBITBUCKETBC-30206.

Please upgrade to version 5.5 or higher.

### Versions Used
Java SDK: `2.23.0`
Java: `openjdk version "1.8.0_191"`

### Steps to Reproduce
N/A

### Error Message, Including Stack Trace
N/A

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @sumerjabri, 

I don't believe the SDK today uses this functionality today.

Is there a specific issue you are concerned about or is this a general potential vulnerability concern? 

Thanks!

**Comment by sumerjabri** [comment]
We use Box Java SDK to help integrate our product (Crafter CMS) with Box. Some of our clients audit our software, and these issues show up and we're required to address them.

Since you don't make use of the vulnerable functionality, it becomes the latter designation of general vulnerability concern.

How should we proceed?

**Comment by carycheng** [comment]
Hey @sumerjabri, 

We released SDK v2.25.1 today containing the updates for bouncycastle and jose4j. You can check it out [here](https://search.maven.org/artifact/com.box/box-java-sdk/2.25.1/jar) 

Thanks!

**Comment by sumerjabri** [comment]
Looks great, thanks!
