### ISSUE TITLE
[security] Insufficient Validation in BouncyCastle bcprov-jdk15on

### ISSUE THREAD

**Issue by sumerjabri** [box/box-java-sdk#665]
- [X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
BouncyCastle bcprov-jdk15on version used is < 1.56, and is vulnerable to insufficient validation of ASN.1 encoding of signature on verification. See https://app.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-32340.

Please upgrade to version 1.56 or higher.

### Versions Used
Java SDK: `2.23.0`
Java: `openjdk version "1.8.0_191"`

### Steps to Reproduce
N/A

### Error Message, Including Stack Trace
N/A

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @sumerjabri,

I don't believe the SDK today uses this functionality today.

Is there a specific issue you are concerned about or is this a general potential vulnerability concern?

Thanks!

**Comment by sumerjabri** [comment]
We use Box Java SDK to help integrate our product (Crafter CMS) with Box. Some of our clients audit our software, and these issues show up and we're required to address them.

Since you don't make use of the vulnerable functionality, it becomes the latter designation of general vulnerability concern.

How should we proceed?

**Comment by carycheng** [comment]
Hey @sumerjabri,

We released SDK v2.25.1 today containing the updates for bouncycastle and jose4j. You can check it out here

Thanks!

**Comment by sumerjabri** [comment]
Looks great, thanks!
