### ISSUE TITLE
Get Tasks on a File missing is_complete, created by and created at

### ISSUE THREAD

**Issue by rjainrohit** [box/box-java-sdk#673]
- [X ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
BoxFile.getTasks does not currently has the option to provide what fields one would like the API to return. The default API does not return "is_complete", "created_by", "created_at" etc. These fields are important for any business logic developed around tasks. This is to request to please provide either these attributes as part of default REST API or add a method to the Box Java SDK with optional fields.

Example:
 public List<BoxTask.Info> getTasks(String... fields)

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
@rjainrohit, 

Thank you for writing in! We have a PR open to address your issue, please see #677.

**Comment by carycheng** [comment]
@rjainrohit,

This patch has been released in Java SDK 2.26.0 and you can find it here!

https://search.maven.org/artifact/com.box/box-java-sdk/2.26.0/jar
