### ISSUE TITLE
BoxTaskAssignment.Info Missing "status" field.

### ISSUE THREAD

**Issue by rjainrohit** [box/box-java-sdk#674]
- [X ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
When a task assignment is completed by a user the "resolution_state" is updated as "completed" but when the task assignment is rejected by a user the "resolution_state" does not change and it continues to stay as "incomplete". So to check if user performed any action on the task the only field returned in the response is "status". But "status" is not available in the JAVA API as a member of BoxTaskAssignment.Info. So this is the request to please add that field and make it available to the JAVA SDK.

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
@rjainrohit, 

Thank you for writing in! We have a PR open to address your issue, please see #677.

**Comment by carycheng** [comment]
@rjainrohit,

This patch has been released in Java SDK 2.26.0 and you can find it here!

https://search.maven.org/artifact/com.box/box-java-sdk/2.26.0/jar
