### ISSUE TITLE
BoxFolder missing field is_collaboration_restricted_to_enterprise

### ISSUE THREAD

**Issue by rjainrohit** [box/box-java-sdk#675]
- [ X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
BoxFolder is missing the field "is_collaboration_restricted_to_enterprise". This is the request to please make it available in the Box JAVA SDK. 

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
@rjainrohit, 

Thank you for writing in! We have a PR open to address your issue, please see #677.

**Comment by rjainrohit** [comment]
Hi @carycheng Just FYI the BoxFolder ALL_FIELDS array is missing is_collaboration_restricted_to_enterprise.

**Comment by carycheng** [comment]
@rjainrohit, 

I'll open a new ticket for that, for now the changes have been pushed and released today and you can find them here.

https://search.maven.org/artifact/com.box/box-java-sdk/2.26.0/jar

Thank you!
