### ISSUE TITLE
BoxTask.getAllAssignments throwing Null Pointer Exception

### ISSUE THREAD

**Issue by rjainrohit** [box/box-java-sdk#676]
- [X ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
BoxTask.getAllAssignments is throwing null pointer exception as the JSON response does not return field "offset"
### Versions Used
Java SDK: 2.25.1 
Java: 1.8

### Steps to Reproduce
// Please include detailed steps to reproduce the issue you're seeing, if possible.  
// If you don't have a reproducible error, please make sure that you give us as much detail  
// as you can about what your application was doing when the error occurred.  
// Good steps to reproduce the problem help speed up debugging for us and gets your issue resolved sooner!

### Error Message, Including Stack Trace
Caused by: java.lang.NullPointerException
	at com.box.sdk.JSONIterator.loadNextPage(JSONIterator.java:80)
	at com.box.sdk.JSONIterator.loadNextJsonObject(JSONIterator.java:90)
	at com.box.sdk.JSONIterator.hasNext(JSONIterator.java:32)
	at com.box.sdk.BoxTaskAssignmentIterator.hasNext(BoxTaskAssignmentIterator.java:45)

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Thanks @rjainrohit!

We will take a look at this and get back to you soon

**Comment by rjainrohit** [comment]
Hi @carycheng any info on the fix? It seems either we cannot use the Box JSON Iterator for this or the REST API must support offset in the response. Please advise.

**Comment by carycheng** [comment]
Hey @rjainrohit, 

I am looking in this currently. In the meantime, if you would like to return all Task Assignments, the [Task.getAssignments()](https://github.com/box/box-java-sdk/blob/master/doc/tasks.md#get-a-tasks-assignments) function will give you a List of all Assignments associated with the task.

**Comment by rjainrohit** [comment]
Hi @carycheng the getTaskAssignments will only provide me value if i specify task_assignment_collection as a field to be returned in response when I call getTasks on a file.  Additionally the default response for task_assignment_collection is missing resolution_state and other task_assignment attributes that i need.

**Comment by carycheng** [comment]
Hey @rjainrohit,

We added the patch for the getAllAssignments() throwing Null Pointer Exception to #677.

Thanks!

**Comment by rjainrohit** [comment]
Thank You !!

**Comment by carycheng** [comment]
@rjainrohit,

This patch has been released in Java SDK 2.26.0 and you can find it here!

https://search.maven.org/artifact/com.box/box-java-sdk/2.26.0/jar
