### ISSUE TITLE
Didn't get new tokens pair with valid refresh token

### ISSUE THREAD

**Issue by ajayaks** [box/box-java-sdk#679]
Hi, 

I have noticed one strange issue as below.

I am persisting  the box token state and deserializing  it for creating next request also using api.getAccessToken() and api.getRefreshToken() before moving forward.

Things are working fine but once in a while this logic doesn't work and its having cascade effect.

Same access token and refresh token which worked 2 mins back , started failing and i am getting  400 response.

No one has changed the token pairs and even if access token is expired it was suppose to generate the new token pair using existing refresh token. There were no concurrent requests during the time when i got this issue.

com.box.sdk.BoxAPIResponseException: The API returned an error code [400]
	at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:92)
	at com.box.sdk.BoxJSONResponse.<init>(BoxJSONResponse.java:32)
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:551)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:326)

So  the issue is why did i get this exception and didn't get new token pairs even with valid refresh token.

Please suggest.

Regards
Ajay

**Comment by carycheng** [comment]
Hey @ajayaks,

Can you please provide us with your:

1.) API Key
2.) Time of failure of your API call.

Please note: It is important to save your new access token because if you have multiple applications running in parallel this may lead to race conditions between the new access tokens.

**Comment by ajayaks** [comment]
Hi Cheng,
Would you please share your mail id where i can send the Api key , dont
want to share it openly.

Regards
Ajay

**Comment by ajayaks** [comment]
Hi Cheng,

Any update on this.

**Comment by mattwiller** [comment]
@ajayaks We're unable to debug your issue, and it doesn't seem like there's evidence that this is an SDK problem at this time.  You should open a case with [Box Support](https://community.box.com/t5/Contact-Support/ct-p/BoxSupport#) — they can assist you further!
