### ISSUE TITLE
resumable upload for large files

### ISSUE THREAD

**Issue by LeasyZhang** [box/box-java-sdk#686]
I have checked that the Java SDK docs and https://developer.box.com/reference doesn't solve my issue
Description of the Issue
We're using BoxFolder#uploadLargeFile function to upload large files, sometimes we may meet upload failure due to network issues, we use this function to re-upload same file. But it seems it will upload the file from beginning. Do you have any suggestion on how to upload from where we failed instead of re-upload the whole file.

Versions Used
Java SDK: 2.22.1
Java: jdk 10.0.1

Steps to Reproduce
run BoxFolder#uploadLargeFile functions and interrupt manually during upload(throw exception for example) 
re-run the  BoxFolder#uploadLargeFile function with exactly same parameter on first step

Error Message, Including Stack Trace
no error message. just have question on using this function.

**Comment by carycheng** [comment]
Hey @LeasyZhang,

We definitely understand that this is an important need for our users to not restart an upload of a large file from the beginning. We have added this to our backlog and will keep you updated on this when we get started!

Thank you!

**Comment by LeasyZhang** [comment]
Hey @carycheng
 So currently we can use /upload/append API to upload files in one upload session, if upload process interrupted due to network issues. We need to upload files from beginning. 
 Looking forward for new feature, and thank you for your explanation.
Thank you!
