### ISSUE TITLE
.getRootFolder() returns a 405

### ISSUE THREAD

**Issue by MaxPowerDarrel** [box/box-java-sdk#687]
- [ X ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Trying a simple "Hello World" Kind of thing.  I am trying to use OAuth-JWT, and to prove I am connected I am trying to get the Root Folder.  In response, I get an error that says "405- Method not supported"

### Versions Used
Java SDK: 2.28.1
Java: 1.8.0_181
### Steps to Reproduce
`@RestController("/api/box")
class BoxResource {

    @GetMapping
    fun getGreeting(): MutableIterable<BoxItem.Info>? {
        try {
            return BoxFolder.getRootFolder(boxApiConnection())
        } catch (e: Exception) {
            e.printStackTrace()
            return null
        }
    }

    private fun boxApiConnection(): BoxAPIConnection? {
        try {
            val jwtPreferences = JWTEncryptionPreferences()
            jwtPreferences.publicKeyID = Configuration.publicKeyId
            jwtPreferences.privateKeyPassword = Configuration.privateKeyPassword
            jwtPreferences.privateKey = Configuration.privateKey
            jwtPreferences.encryptionAlgorithm = EncryptionAlgorithm.RSA_SHA_256
            val boxConfig = BoxConfig(Configuration.clientId, Configuration.clientSecret, Configuration.enterpriseId, jwtPreferences)
            return BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(boxConfig)
        } catch (e: Exception) {
            e.printStackTrace()
            return null
        }

    }
}

object Configuration {
    val publicKeyId = "tr6vthwq"
    val privateKeyPassword = "SECRET"
    val privateKey = "PRIVATE RSA KEY"
    val clientId = "lb8s1if0gu8ydnd60qgzmb08y0zqpndw"
    val clientSecret = "SECRET"
    val enterpriseId = "CAN BE GIVEN ON REQUEST"
    val accountId = "CAN BE GIVEN ON REQUEST"
}`

### Error Message, Including Stack Trace
// Replace with the full error output you're seeing, if applicable.  
// Please include the full stack trace to help us identify where the error is happening.

The API returned an error code [405 | 2uz313g0zg1j52xl.14ij7h65ps8k9v5jd5c9mquoqmm] method_not_allowed - Method Not Allowed; nested exception is com.fasterxml.jackson.databind.JsonMappingException: The API returned an error code [405 | 2uz313g0zg1j52xl.14ij7h65ps8k9v5jd5c9mquoqmm] method_not_allowed - Method Not Allowed (through reference chain: com.box.sdk.BoxFolder[\"metadata\"])

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by MaxPowerDarrel** [comment]
I am more than happy to work and submit a PR if needed.

**Comment by mattwiller** [comment]
@MaxPowerDarrel `BoxFolder.getRootFolder()` does not make any API calls on its own, so it's not possible that this method is the problem.  Your application code must be doing something with the root folder that is not valid — can you verify what operations are being done on that folder?

**Comment by MaxPowerDarrel** [comment]
I was doing something silly with Spring.  Isolating that and the issue seems to have resolved itself.

I feel silly.

**Comment by mattwiller** [comment]
@MaxPowerDarrel Glad you got it working!  Please let us know if you run into any other issues in the future.
