### ISSUE TITLE
Event Stream Enhancement: No "action_by" being captured when making an "get events" call

### ISSUE THREAD

**Issue by jtrujillo3** [box/box-java-sdk#688]
- [ x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
When getting enterprise events, it seems as though the "action_by" response is not being carried over to the response object. 

### Versions Used
Java SDK: 2.23.1

### Steps to Reproduce
Date startDate = new Date(System.currentTimeMillis() - (1000 * 60 * 60 * 6));
Date endDate = new Date(System.currentTimeMillis());
EventLog eventLog = EventLog.getEnterpriseEvents(api, startDate, endDate);
for (BoxEvent event : eventLog) {
            System.out.println("Enterprise Event Created by User: "
                    + event.getCreatedBy().getName()
                    + " Login: " + event.getCreatedBy().getLogin()
                    + " Event Type: " + event.getType()
                    + " Created at: " + event.getCreatedAt().toString());
}

### Error Message, Including Stack Trace
There is no error but you cannot get the action type with the event object returned.  It looks like in BoxEvent.java there is not a catch for the "action_by" memberName

**Comment by carycheng** [comment]
Hey @jtrujillo3,

Thanks for letting us know! We have a ticket for this on the backlog and will add this to our next sprint.

Always appreciate your insights!

**Comment by carycheng** [comment]
Hey @jtrujillo3,

We've added `action_by` field to enterprise events. This will go out with our next release. Thanks!

**Comment by carycheng** [comment]
Hey @jtrujillo3, we just release v2.30.0 of the Java SDK today with inclusion of the `action_by` field on enterprise events stream. 

Let us know if that looks good, thanks!

**Comment by jtrujillo3** [comment]
Thank you!

Jackie Trujillo
Technical Consultant

[image: box] <http://www.box.com/home?from=em>
Cloud Content Management
box.com <http://www.box.com/home?from=em>

[image: fb/box] <http://facebook.com/box>  [image: /blog]
<https://www.box.com/blog/>  [image: t.co/box] <http://twitter.com/boxhq>
