### ISSUE TITLE
Search by multiple tags

### ISSUE THREAD

**Issue by dcods22** [box/box-java-sdk#696]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
// Replace this text with a description of what problem you're having.  
// Please include as much detail as possible to help us troubleshoot!  
// If it isn't obvious, please include how the behavior you expect differs from what actually happened.  
// This is really important so we know how to start troubleshooting your issue.

I am trying to search by multiple tags.  If I pass one tag it works perfectly fine but if I add multiple tags while they are comma separated it does not work.  If I remove the extra quotes around the query it does not change the results. It seems through the Box UI you can search by multiple tags and they were comma separated which was why I tried that route.

### Versions Used
Java SDK: // Replace with the version of the Java SDK you're using.  
Java: // Replace with the version of Java your application is running on.
2.28.1

### Steps to Reproduce
// Please include detailed steps to reproduce the issue you're seeing, if possible.  
// If you don't have a reproducible error, please make sure that you give us as much detail  
// as you can about what your application was doing when the error occurred.  
// Good steps to reproduce the problem help speed up debugging for us and gets your issue resolved sooner!

            String commaSeperatedTags = String.join(",", tags);
            boxSearchParameters.setContentTypes(Arrays.asList("tags"));
            boxSearchParameters.setQuery("\"" + commaSeperatedTags + "\"");

### Error Message, Including Stack Trace
// Replace with the full error output you're seeing, if applicable.  
// Please include the full stack trace to help us identify where the error is happening.

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @dcods22,

It's a little bit confusing so this snippet should do the trick. What you ultimately want is to have `"tag_1"OR"tag_2"` set as your query.

Something like this:
```java
        BoxAPIConnection api = new BoxAPIConnection("ACCESS_TOKEN");
        BoxSearch boxSearch = new BoxSearch(api);
        BoxSearchParameters searchParams = new BoxSearchParameters();
        searchParams.setContentTypes(Arrays.asList("tags"));
        searchParams.setQuery("\"foo\"" + "OR" + "\"bar\"");
        PartialCollection<BoxItem.Info> searchResults = boxSearch.searchRange(0, 5, searchParams);
```

Here are some helpful tips if you run into more search related issues in the future:

https://community.box.com/t5/Managing-Files-and-Folders/Search-for-Files-Folders-and-Content/ta-p/19269

But you are always more than welcome to submit an issue here and we will do our best to help.

Thank you!

**Comment by dcods22** [comment]
Hi,

Thank you for the response @carycheng I was wondering can we also do "AND" and "OR" queries when doing a metadata search? I would love to do a search on our custom filter where we do something like

firstName = 'Dan' or nickName = 'Dan'

Thanks,

Dan

**Comment by carycheng** [comment]
Hey @dcods22,

Today we support `AND` operator for metadata search only.
