### ISSUE TITLE
What's the maximum retry times?

### ISSUE THREAD

**Issue by LeasyZhang** [box/box-java-sdk#706]
- [ ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I'm using Box Java SDK to do large file upload and one question I want to figure out is what's
the maximum retry times will be performed by this Java SDK?

### Versions Used
Java SDK: 2.20.1
Java: 1.8

**Comment by carycheng** [comment]
Hey @LeasyZhang,

Are you referring to the upload of each individual part? If so, each upload part is attempted 3 times. You can see it here in the class [LargeFileUploadTask](https://github.com/box/box-java-sdk/blob/master/src/main/java/com/box/sdk/LargeFileUploadTask.java)

Let us know if this helps!

**Comment by LeasyZhang** [comment]
Hey @carycheng 

It's exactly the answer I want to know!

Thank you.
