### ISSUE TITLE
Missing specific attribute in collaboration move action 

### ISSUE THREAD

**Issue by tsaishu** [box/box-java-sdk#708]
- I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
If UserA has a sub folder and moves it to UserB, this action is capable on Box/UI.
However using java SDK, this does not seems to be capable and throws below message. 
As a solution, probably "Owned_by" parameter for the folder should be explicitly specified on API. 

＝＝＝
400 cannot_make_collaborated_subfolder_private
＝＝＝

We would like to know below. Thanks.
1.The cause of the issue
2.The workaround /Solution

### Versions Used
Java SDK: 2.34.0

### Steps to Reproduce
1. UserA creates the folder and creates subfolder as well. 
2. UserA collaborates subfolder to UserB. UserB has been collaborated with "Co-owner". 
3. UserA moves the subfolder to UserB.  

### Error Message, Including Stack Trace
400 cannot_make_collaborated_subfolder_private

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by jasonkimchi** [comment]
Hi @mattwiller , just checking in on this one. Does your closure indicate that we can't expect to see owned_by exposed in BoxFolder.move()? The cannot_make_collaborated_subfolder_private error from our docs indicates that the fix is to specify a new owned_by.id value as we make the move call, but BoxFolder.move() does not expose owned_by.

**Comment by mattwiller** [comment]
@jasonkimchi @tsaishu I wasn't aware that the `owner` parameter could be passed when moving a folder; this isn't really documented anywhere outside of the one reference in the [Error Codes docs](https://developer.box.com/docs/error-codes).  Our team will discuss the best way to add this parameter to this SDK (as well as the other SDKs!)

**Comment by jae-hyup** [comment]
I have same problem. @mattwiller or Box team, can you please indicate if there is API available or workaround?
