### ISSUE TITLE
Add support for etags

### ISSUE THREAD

**Issue by gcurtis** [box/box-java-sdk#71]
Adding etags to the SDK will allow developers to:
1. automatically enable caching for a performance gain.
2. enforce version checking so that newer files on Box aren't accidentally overwritten by older local files.
## Caching Files and Folders

Caching etag support can be added to `BoxFile.getInfo()` and `BoxFolder.getInfo()` without any interface changes to the current design. This means that all clients will automatically gain the benefits of caching without needing to implement any additional logic.

``` java
BoxFile myFile = new BoxFile(api, "id");

// Info will be retrieved and automatically cached in the file object. The file
// object will then internally update its current etag to the one returned by
// the getInfo request.
BoxFile.Info firstInfo = myFile.getInfo();

// Since getInfo() has been called before, this call will automatically insert
// an "If-None-Match" header and used the cached info if a 304 is returned.
BoxFile.Info secondInfo = myFile.getInfo();
```

If a client persists info and later wants to restore it, the `BoxFile.Info` constructor will automatically parse the etag field from the JSON and resume caching.

``` java
BoxFile.Info storedInfo = new BoxFile.Info(json);
BoxFile myFile = storedInfo.getResource();

// This call will automatically insert an "If-None-Match" header using the etag
// parsed from the original JSON. If the server returns a 304, then the original
// storedInfo will be returned (since it hasn't changed).
BoxFile.Info info = myFile.getInfo();
```
## Caching Shared Items

Since `BoxItem.getSharedItem()` is a static method, we cannot automatically track etags. Instead, an overloaded method will be added that allows for the user to manually specify an etag. Fortunately, using etags with shared items is expected to be a less common use-case than using it with files or folders.

``` java
String sharedLink = "http://cloud.box.com/mylink"
String password = null;
String etag = "0";
BoxItem.Info sharedItemInfo = BoxItem.getSharedItem(api, sharedLink, passsword,
    etag);
```
## Enabling Version Checking

An optional parameter will be added to the constructors of `BoxFile` and `BoxFolder` in addition to a `setLocalEtag(String)` method if the user wants to enable version checking for POST/PUT/DELETE methods.

``` java
String localEtag = "0";
BoxFile myFile = new BoxFile(api, "id", localEtag);
```

``` java
BoxFile myFile = new BoxFile(api, "id");
myFile.setLocalEtag("0");
```

From then on, this etag will be used with an "If-Match" header whenever POST/PUT/DELETE calls are made to ensure that the local file is up-to-date.

``` java
// This call will automatically send an "If-Match" header and throw an error if
// the etag didn't match.
myFile.move(destination);
```

If the call does succeed, then the file object will update its internal etag to match the one returned by the server. This allows for future calls to be made without the user needing to manually set the etag each time.

``` java
myFile.move(destination);

// This call will succeed because the etag was automatically updated after the
// first move call.
myFile.rename("New Name");
```

An important distinction between "version checking" methods (PUT/POST/DELETE) and "caching" methods (GET) is that caching methods won't automatically update the etag if the user has specified one manually via `setLocalEtag(String)` or the constructor. This is because we want to be safer when writing data than reading it. Automatically updating the etag after a read is dangerous because the user may not realize that they are no longer validating against the version of the etag they specified.

``` java
String localEtag = "0";
BoxFile myFile = new BoxFile(api, "id", localEtag);

// Even if getInfo() returns a newer etag, we won't automatically overwrite the
// etag that the user specified in the constructor.
BoxFile.Info info = myFile.getInfo();

// The move call will still perform an "If-Match" against the original etag (in
// this case, "0").
myFile.move(destination);
```
## Handling Failed Version Checks

If a 412 (Precondition Failed) status is returned due to a failed version check, the request will have to be retried with the newer etag. To do this, the item's etag should be set to the version returned by `getInfo()`.

``` java
String localEtag = "0";
BoxFile myFile = new BoxFile(api, "id", localEtag);

try {
    // Pretend that this call fails because the local etag is out-of-date.
    myFile.move(destination);
} catch (BoxAPIException e) {
    // Get the file's info to see what changed since we last retrieved it.
    BoxFile.Info info = myFile.getInfo();

    // If we're sure we still want to modify the file, then we set the etag
    // retrieved from getInfo() and call move() again.
    myFile.setLocalEtag(info.getEtag());
    myFile.move(destination);
}
```
## Disabling Version Checking

Version checking can also be disabled entirely by setting the etag to to null.

``` java
String localEtag = "0";
BoxFile myFile = new BoxFile(api, "id", localEtag);

// Set the etag to null if we don't want to enforce version checking anymore.
myFile.setLocalEtag(null);
```

**Comment by tarrencev** [comment]
I'm working through the implementation of this and I'm not sure supporting etags for reads is worth the overhead right now.

1. There are some issues with the files endpoint and lock/unlock which returns incorrect etags
2. We will need to maintain a list of requested fields on a cached info object to decide whether to add the etag header or not, since if a info request for a file was made with files `name,description` and then later made with `name,description,size` the api would still return a `304` but our cached info object doesn't contain the `size` field.

To me, version checking is the compelling use case for etags and it seems the read stuff just isn't worth the added complexity

**Comment by gcurtis** [comment]
I'm going to close this ticket for now since there were some complications with the initial attempt at implementing etags. We can revisit this if there's more demand for etags support.
