### ISSUE TITLE
Can we better document how to get a single Groups' members?

### ISSUE THREAD

**Issue by nddipiazza** [box/box-java-sdk#711]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue

Hey I'm trying to figure out from the docs how to get the members of a single group.

In particular, I'd like to loop through all groups in the enterprise, and list out their user memberships. 

It's pretty clear how to do this the reverse way... listing all users and getting their group memberhips one-by-one. But how do you do this for group memberhips?

If you point me in the right direction, i would be happy to create a PR to improve the groups.md doc.

Also we should put documentation about whether or not BoxGroup can be nested.

**Comment by nddipiazza** [comment]
i guess it may be fairly obvious

```
Set<SolrInputDocument> buffer = Sets.newHashSet();
    for (BoxGroup.Info groupInfo : BoxGroup.getAllGroups(api)) {
      BoxGroup group = new BoxGroup(api, groupInfo.getID());
      Iterable<BoxGroupMembership.Info> memberships = group.getAllMemberships();
      for (BoxGroupMembership.Info membershipInfo : memberships) {
          // do something with the membership???
      }
    }
```

**Comment by carycheng** [comment]
Hello @nddipiazza,

You are right, group memberships is the association between a user and a group. You can read more about it [here](https://developer.box.com/reference#membership-object).

The code you have will do what you are looking for. It will iterate through all groups in your enterprise and it will retrieve all memberships for a given group and finally it will iterate through each membership.

```java
        for (BoxGroup.Info groupInfo : BoxGroup.getAllGroups(api)) {
	          BoxGroup group = new BoxGroup(api, groupInfo.getID());
	          Iterable<BoxGroupMembership.Info> memberships = group.getAllMemberships();
	          for (BoxGroupMembership.Info membershipInfo : memberships) {
	              System.out.print("Member Name: " + membershipInfo.getID() + " with role: " + membershipInfo.getRole());
	          }
        }
```

If you have any other questions please do not hesitate to reach out, thanks!

**Comment by nddipiazza** [comment]
ok you can close this
