### ISSUE TITLE
is_externally_owned

### ISSUE THREAD

**Issue by mxmmarmol** [box/box-java-sdk#712]
- [yes ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
is_externally_owned Is an attribute that can be found on Box Api reference documentation, but BoxFolder.Info does not have it implemented. Can please be added?

### Versions Used
v2.32.0

### Steps to Reproduce
https://developer.box.com/reference#fields 

### Error Message, Including Stack Trace
no error message, is a missing attribute

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @mxmmarmol,

Thank you for the call out! We have a pr out for this now at #714. We will get this merged as soon as possible.

Thank you!

**Comment by mmarmol-navent** [comment]
@carycheng awesome! It should be present in both Folder and File Info based on the doc! Thanks!

**Comment by carycheng** [comment]
@mmarmol-navent, great catch! I've updated the pr to reflect both folder and file now, thanks!

**Comment by carycheng** [comment]
@mmarmol-navent, new Java SDK v2.35.0 is out with is_external_only field for files and folders.

Let us know if you have any other questions, thank you!

**Comment by mxmmarmol** [comment]
The release works, but on the Folder and File the static field with ALL has the property missing. I think ti should also be added there.

**Comment by carycheng** [comment]
Hey @mxmmarmol,

v2.36.0 of the Java SDK now with the fields added. You can see it [here](https://github.com/box/box-java-sdk/releases/tag/v2.36.0).

Thank you for your patience and please let us know if you run into any other issues.

Much appreciated!
