### ISSUE TITLE
BoxDateFormat cannot handle milliseconds but API sends BoxEvents that contain milliseconds in timestamps.

### ISSUE THREAD

**Issue by MagikSquirrel** [box/box-java-sdk#715]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Downloading BoxEvent's from the API result in ParsingExceptions. I've narrowed this down to an explicit event that is received from the API. Upon inspection of this event, the fields "created_at", "source->completed_at" contain time stamps that do not fit the DateFormat pattern as defined in BoxDateFormat.java. I believe this is because for some reason this particular event's timestmaps contain milliseconds within the date string. Milliseconds are not in other events and the format string in the SDK is not capable of handling them as currently implemented.

Here is the event from the API (I've zeroed out PII).

```
{  
   "type":"event",
   "event_id":"0000000000000000000000000000000000000000",
   "created_by":{  
      "type":"user",
      "id":"2",
      "name":"Anonymous User",
      "login":""
   },
   "created_at":"2019-07-15T08:18:34.462-07:00",
   "recorded_at":"2019-07-15T08:18:35-07:00",
   "event_type":"TASK_ASSIGNMENT_COMPLETE",
   "session_id":"000000000000000000000000000",
   "source":{  
      "item":{  
         "id":"000000000000",
         "type":"file",
         "name":null,
         "file_version":{  
            "type":"file_version",
            "id":null,
            "sha1":null
         },
         "sequence_id":null,
         "etag":null,
         "sha1":null
      },
      "message":"",
      "completed_at":"2019-07-15T08:18:34.118-07:00",
      "assigned_at":"2017-10-17T13:27:38+00:00",
      "reminded_at":null,
      "status":"approved",
      "type":"task_assignment",
      "id":"00000000000",
      "assigned_to":{  
         "type":"user",
         "id":"0000000000",
         "name":"User One",
         "login":"user1@example.com"
      },
      "resolution_state":"approved",
      "assigned_by":{  
         "type":"user",
         "id":"000000000",
         "name":"User Two",
         "login":"user2@example.com"
      }
   }
}
```

### Versions Used
Java SDK: v2.34.0
Java: 1.8.0-202

### Steps to Reproduce
```
@Test
@Category(UnitTest.class)
public void testMilliseconds() throws ParseException {
    BoxDateFormat.parse("2019-07-15T08:18:34.462-07:00"); //Throws exception
}
```

### Error Message, Including Stack Trace
```
java.text.ParseException: Unparseable date: "2019-07-15T08:18:34.462-07:00"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at com.box.sdk.BoxDateFormat.parse(BoxDateFormat.java:31)
```

**Comment by carycheng** [comment]
Thank you for this callout @MagikSquirrel,

We will look into this and update you on the resolution.

**Comment by PJSimon** [comment]
Hi @MagikSquirrel!  I just wanted to let you know that this was fixed in https://github.com/box/box-java-sdk/pull/772!

Thanks for your support and contribution!
