### ISSUE TITLE
how to search all jpg file？

### ISSUE THREAD

**Issue by yangjieK** [box/box-java-sdk#716]
- [x] I have checked that the [https://developer.box.com/docs/search-for-content][sdk-docs]  doesn't solve my issue

### Description of the Issue

I need search all jpg and video file in box
but try search api just like this . I dont know what is searchTerm to be written.

`
String searchTerm = "SEARCH QUERY";
String type = "file";	// file, folder, or web_link
int limit = 10;
int offset = 0;

BoxSearchParameters bsp = new BoxSearchParameters();
bsp.setType(type);
bsp.setQuery(searchTerm);
bsp.setFileExtensions("jpg");

BoxSearch bs = new BoxSearch(client);
PartialCollection<BoxItem.Info> searchResults = bs.searchRange(offset, limit, bsp);
`

**Comment by mattwiller** [comment]
@yangjieK Unfortunately, it is not possible to perform a search for all files of a given extension in Box.  A search term must be provided, and the search results will only include files that match the search term.
