### ISSUE TITLE
Box getAllGroups method returning 0 groups

### ISSUE THREAD

**Issue by nddipiazza** [box/box-java-sdk#717]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue

I am getting 0 groups back from getAllGroups.
    
### Versions Used
Java SDK: box-java-sdk:2.24.0
Java: 1.8.181

### Steps to Reproduce

I am making this call to `BoxGroup.getAllGroups(api)` using JWT service account:

```
        JWTEncryptionPreferences encryptionPref = new JWTEncryptionPreferences();
        encryptionPref.setPublicKeyID(boxJwtPublicKeyId);
        encryptionPref.setPrivateKey(privateKey);
        encryptionPref.setPrivateKeyPassword(boxJwtPrivateKeyPassword);
        encryptionPref.setEncryptionAlgorithm(EncryptionAlgorithm.RSA_SHA_256);

        BoxAPIConnection api = new BoxDeveloperEditionAPIConnection(myAdminUserId, DeveloperEditionEntityType.USER, apiKey, apiSecret, encryptionPref,
          ACCESS_TOKEN_CACHE);    
        for (BoxGroup.Info groupInfo : BoxGroup.getAllGroups(api)) {
         // do stuff with group info
         }
```

I can get groups back from my test account, but in production this is coming back completely empty. 

Here is my permissions for the crawling user:

![image](https://user-images.githubusercontent.com/2238777/61513647-6e8d9480-a9c3-11e9-97fa-820936081b6c.png)

### Error Message, Including Stack Trace
No error messages. Just empty results. 

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @nddipiazza,

Can you please provide us with the response body and error code is there is any?

**Comment by nddipiazza** [comment]
There was no error code actually. It was just 0 groups.

**Comment by carycheng** [comment]
Hey @nddipiazza,

Can you please confirm your scopes between your test environment and production environment and make sure they both have the same scopes?

If they do can you go into your admin console for production and reauthorize your application to make sure the correct scope catch?

Thanks!

**Comment by nddipiazza** [comment]
Hey @carycheng. sorry i thought i responded to this the day after i got this msg. But I guess I forgot.

I'm waiting to get this info. Will update when I have more info.

**Comment by nddipiazza** [comment]
OK. getting this info soon.

**Comment by nddipiazza** [comment]
@carycheng they seem to match as far as we can tell. we created a fresh new application and it continues to have this same problem.

**Comment by nddipiazza** [comment]
Re registering the API key worked. Thank you for your support.
