### ISSUE TITLE
Auth issues when trying to connect and retrieve data from Box programmatically

### ISSUE THREAD

**Issue by hexastax** [box/box-java-sdk#722]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Could someone provide a recommendation for a connector in Java which connects to Box and retrieves files, comments, and collaborations? I am able to do that for a particular App, using a Developer Token. However, I want to be able to not rely on Developer Tokens since they are short-lived.

I have looked at:
1. Connecting with OAuth. I do not see a full code sample for it. This seems more suited for interactive logins involving GUI. I want to just connect programmatically and retrieve data from Box. Hitting the first URL returns the HTML login page. It has a hidden redirect_url... I suppose I could extract that and see if I can make that work.. Seems too complicated; there must be an easier way?

There is a sample involving some Spark code
`get("/return", (req, res) -> {
    // Capture auth code 
    String code = req.queryParams("code");                
    // Instantiate new Box API connection object
    BoxAPIConnection client = new BoxAPIConnection(Config.client_id, Config.client_secret, code);     
    // PERFORM API ACTIONS WITH CLIENT
  });`
Where would the code come from? I'm surmising it'd be returned from the redirect..

2. Use JWT
- Got the public and private key set up, downloaded the JSON generated by Box.
- The below code returned an error: "The API returned an error code [400] invalid_grant - Please check the 'sub' claim. The 'sub' specified is invalid."
- Tried running with user ID from my app and using the Enterprise ID (which is 0). Still get the 400 error.

`    JWTEncryptionPreferences jwtPreferences = new JWTEncryptionPreferences();
    jwtPreferences.setPublicKeyID(PUBLIC_KEY_ID);
    jwtPreferences.setPrivateKeyPassword(PRIVATE_KEY_PASSWORD);
    jwtPreferences.setPrivateKey(PRIVATE_KEY);
    jwtPreferences.setEncryptionAlgorithm(EncryptionAlgorithm.RSA_SHA_256);

    BoxDeveloperEditionAPIConnection api = BoxDeveloperEditionAPIConnection.getAppUserConnection(
      USER_ID, CLIENT_ID,
      CLIENT_SECRET, jwtPreferences);

    BoxUser.Info userInfo = BoxUser.getCurrentUser(api).getInfo();`

3. Using the App Token View
- Have a primary access token and secondary.
- Get the error "The API returned an error code [403 | ... access_denied_insufficient_permissions - Access denied - insufficient permission"

`private static final String PRIMARY_ACCESS_TOKEN = "..."
  private static final String USER_ID = "183070079";
    BoxTransactionalAPIConnection api = new BoxTransactionalAPIConnection(PRIMARY_ACCESS_TOKEN);
    api.asUser(USER_ID);
    BoxFolder rootFolder = BoxFolder.getRootFolder(api);
`
If I run with no user ID provided I get no content back.. presumably there's nothing in the uppermost root, has to be a specific user(s).

Any hints or recommendations would be greatly appreciated.
Thanks.

### Versions Used
Java SDK: Box 2.36.0, java 1.8
Java: 1.8

### Error Message, Including Stack Trace

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hey @hexastax,

For your use case of programmatically authenticating with Box then performing actions with the Box API - Server Authentication with JWT is indeed the best route to take. You can read more about it [here](https://developer.box.com/docs/setting-up-a-jwt-app). 

As far as the current issue you are seeing, something that pops out is that your enterprise ID is not `0`. `0` refers to the root folder id. The best way to check your enterprise ID is to from your: `Admin Console` -> Left navbar click `Account & Billing` -> In that tab the second row will say `Enterprise ID`.

I also think something else that would be helpful would be to use the `BoxConfig.readFrom()` static helper method. This will make sure there are not any formatting issues(whitespaces etc...) when you pass in your JSON config file that you downloaded. The readFrom method takes in an Reader object.

**Comment by PJSimon** [comment]
@hexastax I'm closing this issue as it appears resolved!  Thanks!
