### ISSUE TITLE
Metadata replace(String path, List<String> values) missing

### ISSUE THREAD

**Issue by mxmmarmol** [box/box-java-sdk#725]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
The metadata class does not expose on the replace operation a way to replace a list of strings. But metadata can have list of strings and values, and in fact the add method include its, so one added we can not replace it.

### Versions Used
Any version

### Steps to Reproduce
Not needed

### Error Message, Including Stack Trace
None

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by carycheng** [comment]
Hello @mxmmarmol,

Thanks for pointing that out, we have a pr out for this that you can track at #726 

We will work on getting this reviewed and released as soon as possible. Thank you for your patience.

**Comment by mxmmarmol** [comment]
duplicated, [#726](https://github.com/box/box-java-sdk/pull/726)
