### ISSUE TITLE
Is it possible to use the search api to find all files/folders in a folder? 

### ISSUE THREAD

**Issue by nddipiazza** [box/box-java-sdk#727]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

Just a quick question,

Is it possible to use the java-box-sdk's search endpoint so that you can find all files underneath a given folder?

For example,

```
--folderLevel1
----fileLevel1
----folderLevel2
--------fileLevel2
--------folderLevel3
---------------fileLevel4
```

I want to be able to search `folderLevel1` and get `fileLevel1`, `fileLevel2`,  `fileLevel3`, and `fileLevel4`

**Comment by mattwiller** [comment]
@nddipiazza Unfortunately, that is not currently possible with the Search API.  The best way I know of to do this would be to traverse the folder tree under the given folder.

**Comment by nddipiazza** [comment]
Results in many times more api calls and floods box with api calls. we should add this as a new feature request.
