### ISSUE TITLE
Help accessing folder from shared link

### ISSUE THREAD

**Issue by JonasHess** [box/box-java-sdk#732]
How would I be accessing a folder when all I have is a shared link to it?

```
import com.box.sdk.BoxAPIConnection;
import com.box.sdk.BoxFolder;
import com.box.sdk.BoxItem;
import org.junit.Test;

public class BoxFileListTest {

    final String DEVELOPER_TOKEN = "xxxxxxxxxxxxxxxxxxxx";

    @Test
    public void listBoxFiles() {

        BoxAPIConnection api = new BoxAPIConnection(DEVELOPER_TOKEN);

        final String sharedLink = "https://app.box.com/s/a2ef3yjjhavudm7r7bfnd23sas5wqgt5";

        BoxFolder folder = null;

        //TODO convert sharedLink to folder object

        for (BoxItem.Info itemInfo : folder) {
            System.out.format("[%s] %s\n", itemInfo.getID(), itemInfo.getName());
        }
    }

}
```

**Comment by carycheng** [comment]
Hey @JonasHess,

In order to retrieve an item (file or folder) from a given shared link you will need to use the shared item endpoint listed [here](https://p.catchpoint.com/ui/Entry/PC/V/ARHZ-C-D-barfnjXMAGp6gAA).

**Comment by PJSimon** [comment]
Hi @JonasHess, I think there was a typo in @carycheng's link.  It should have been: https://developer.box.com/reference#get-a-shared-item

Let us know if you're still having issues, otherwise, we'll close this issue.

Thanks!

**Comment by carycheng** [comment]
Apologies @JonasHess and good catch @PJSimon,

That is indeed the endpoint you would want to hit. For a Java example please refer to this function here https://github.com/box/box-java-sdk/blob/master/doc/shared-items.md

**Comment by PJSimon** [comment]
Hi @JonasHess, I'm going to close this issue, as we haven't heard from you in a while, but if you're still having issues, you can just re-open this issue.  Thanks!
