### ISSUE TITLE
Need the ability to provide completion_rule when adding task to a File

### ISSUE THREAD

**Issue by rjainrohit** [box/box-java-sdk#743]
- [ X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
We want to create approval tasks with completion_rule "any_assignee". The REST API documentation has this below

When a task is created with completion rule "all_assignees" (default), the task will only be considered completed when all assignees have completed the task. When a task is created with completion rule "any_assignee", the task will be considered completed when one assignee has completed the task.

### Versions Used
Java SDK: 2.38
Java: 1.8+

### Steps to Reproduce
NA

### Error Message, Including Stack Trace
NA

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/reference#create-a-task

**Comment by carycheng** [comment]
Hey @rjainrohit, Task completion_rule was just released in v2.39.0 of the Java SDK today. Please try it out and let us know, thank you.

**Comment by PJSimon** [comment]
Hi @rjainrohit,
I'm going go ahead and close this issue for now.  If you have any further questions, please feel free to re-open it!  We're happy to help further, if needed!
Thanks,
Patrick
