### ISSUE TITLE
Support provision grant

### ISSUE THREAD

**Issue by gcurtis** [box/box-java-sdk#75]
Add support for the [provision grant](https://developers.box.com/provision/) auth flow.

**Comment by tarrencev** [comment]
@gcurtis is this still something we want to add? Looks like the documentation has been moved/cant find anything about it in the new docs

**Comment by gcurtis** [comment]
It's weird that provision grant has completely disappeared from the API docs. I don't really remember what it was (even though I apparently answered a Stackoverflow question about it). I think it's been deprecated in favor of a new upcoming auth method.

I'll just close this out.
