### ISSUE TITLE
Changing Box Shared Link for a Folder Sending two PUT calls and removing the link altogether

### ISSUE THREAD

**Issue by saurabh0118** [box/box-java-sdk#751]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
The issue is when we use Box Java SDK. I can clearly notice we receive 2 feeds.  Out of those one is ITEM_SHARED_UNSHARE , which is causing this .

### Versions Used
Java SDK: Box SDK 2.4.0
Java: Open jdk 11

### Steps to Reproduce
The issue is when we use Box Java SDK. I can clearly notice we receive 2 feeds.  Out of those one is ITEM_SHARED_UNSHARE , which is causing this .

[2019-11-04T21:35:04.004Z]  TXN_ID =  [com.boxfpnlogger.service.BoxFPNAdapterService]  [https-jsse-nio-8443-exec-5] [447] [INFO ] CLASS=BoxFPNAdapterService,METHOD=isAuthenticatedFPNRequest(),MESSAGE=Received a FPN Feed of type ITEM_SHARED_UPDATE for file/folderID

[2019-11-04T21:35:05.005Z]  TXN_ID =  [com.boxfpnlogger.utility.BoxSDKUtility]  [https-jsse-nio-8443-exec-5] [76] [INFO ] Scanning folderID=92054827257

[2019-11-04T21:35:05.005Z]  TXN_ID =  [com.boxfpnlogger.service.BoxFPNAdapterService]  [https-jsse-nio-8443-exec-6] [447] [INFO ] CLASS=BoxFPNAdapterService,METHOD=isAuthenticatedFPNRequest(),MESSAGE=Received a FPN Feed of type ITEM_SHARED_UNSHARE for file/folderID

Code being used : 

```
  private void modifyFolderLink(String folderId, String boxItemOwnerId) {

    BoxDeveloperEditionAPIConnection api = getBoxDeveloperEditionApiConnection();
    api.asUser(boxItemOwnerId);
    logger.info("Correcting the link for folderID " + folderId);
    BoxFolder boxFolder = new BoxFolder(api, folderId);
    BoxSharedLink sharedLink = new BoxSharedLink();
    sharedLink.setAccess(BoxSharedLink.Access.COLLABORATORS);
    BoxFolder.Info info = boxFolder.new Info();
    info.setSharedLink(sharedLink);
    boxFolder.updateInfo(info);
    logger.info("Corrected the link for folderID " + folderId);
  }
```

**Comment by PJSimon** [comment]
Hi @saurabh0118,

Thanks for opening the issue!  We're taking a look and will get back to you soon.

Patrick

**Comment by carycheng** [comment]
Hey @saurabh0118,

Curious if you have an expiry date set for the shared link? One of the triggers for the `ITEM_SHARED_UNSHARE` event you are seeing is when an expiry date is set for the Shared Link and is eventually past due. This will prompt a chron job to go ahead and remove the shared link kicking off the unshare event you are seeing.

Please let us know, thanks!

**Comment by saurabh0118** [comment]
No there is no expiry date.

My code sample is present in the description.

**Comment by saurabh0118** [comment]
The problem what is happening here is , I am using the word by word box sdk documentation, and why there are two events here ?

There should be only ITEM_SHARE_UPDATE ?

**Comment by saurabh0118** [comment]
To update , only Default access option works . In all other cases Box SDK is unsharing the links.

**Comment by saurabh0118** [comment]
I take the previous comment back.  It's random. This time it unshared the link with default option as well.

**Comment by chitreshd** [comment]
Hi @saurabh0118 : I am an engineer at Box. Can you please let us know if you're subscribing for user **only** events (  https://developer.box.com/en/guides/events/for-user/ i.e. not filtering by stream_type ) or **also** enterprise events ( https://developer.box.com/en/guides/events/for-enterprise/ i.e. filtering by "stream_type" )

**Comment by PJSimon** [comment]
Hi @saurabh0118 , I just wanted to make sure you saw the additional information request from @chitreshd , above.

**Comment by PJSimon** [comment]
Hi @saurabh0118, I'm going to close this issue for now, but please feel free to re-open it if you're still having issues!  Thanks!
