### ISSUE TITLE
Need the Ability to Update Tracking Codes

### ISSUE THREAD

**Issue by rjainrohit** [box/box-java-sdk#752]
- [X ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
 Currently the SDK has the ability to read tracking codes but there is none to update.

### Versions Used
Java SDK: 1.8+
Java: 1.8+

### Steps to Reproduce
NA

### Error Message, Including Stack Trace
NA

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by sujaygarlanka** [comment]
We are looking into adding this soon.

**Comment by PJSimon** [comment]
@rjainrohit Can you explain what the request is here, please?  What is a tracking code?  Thanks!

**Comment by rjainrohit** [comment]
@PJSimon  https://developer.box.com/en/reference/post-users/#param-tracking_codes for your reference.

**Comment by rjainrohit** [comment]
> We are looking into adding this soon (SDK-1200). Thanks for the feedback!

Is there an estimated date?

**Comment by sujaygarlanka** [comment]
@rjainrohit This is now resolved by PR #766.

**Comment by rjainrohit** [comment]
Can you please also provide the ability to send tracking codes at the time of creating the user and not just at the time of update?
