### ISSUE TITLE
create duplicated folders via java jdk

### ISSUE THREAD

**Issue by winstonxie3000** [box/box-java-sdk#753]
The create folder API https://api.box.com/2.0/folders is not allowed to create a duplicated folder with the same name. It works fine normally, however, when it runs in the multiple-threads environment, it will still create 2 folders in the same parent folder with exact folder name. Please see the following code snippet with JAVA BOX SDK 2.20.1, Java version: openjdk 1.8.0_201

```
public static void main(String[] args) {

    ExecutorService executorService
            = Executors.newFixedThreadPool(2000);
    for (int i = 0; i < 1000; i++) {
        executorService.execute(()->{
            BoxAPIConnection boxAPIConnection = new BoxAPIConnection("UCFBs8D0xVEkqJqV0C29EH85ZbIjTWeY");
            BoxFolder rootFolder = BoxFolder.getRootFolder(boxAPIConnection);

            try {
                BoxFolder.Info folderInfo = rootFolder.createFolder("testDuplicatedFolder");
                logger.info("creating folder {} in {}", folderInfo.getName(), System.currentTimeMillis());
            } catch (Exception e) {
                // do nothing
            }
        });
    }

}

```
What's more interesting is it will create 2 folders with the exact name "testDuplicatedFolder" but will never create a third "testDuplicatedFolder" folder.

Could you please help look into this ASAP? Thanks a lot.

**Comment by sujaygarlanka** [comment]
Sorry for the delayed response. I was able to replicate your issue. Looking into what may be causing this issue. Will get back to you soon.

**Comment by winstonxie3000** [comment]
@sujaygarlanka Thanks for looking into this. Unfortunately, the multiple-threads mechanism is a must-have in our project. The workaround we took is adding a pause() in each thread. like below. 

```
import com.google.common.util.concurrent.RateLimiter;

try {
                RateLimiter rateLimiter = RateLimiter.create(2);
                rateLimiter.acquire();
                BoxFolder.Info folderInfo = rootFolder.createFolder("testDuplicatedFolder");
                logger.info("creating folder {} in {}", folderInfo.getName(), System.currentTimeMillis());
            } catch (Exception e) {
                // do nothing
            }
```
which would resolve the problem but kind of sacrifice the performance.

**Comment by mmarmol-navent** [comment]
Hi, we had this issue from day one with box api, my best suggestion to you is to use a locking mechanism when creating folders using redis or something else so you can ensure that only one thread at a given time is creating a X folder at a given time. That is how we solve it at least.

**Comment by winstonxie3000** [comment]
Hi, @sujaygarlanka any good news on this? Thanks.

**Comment by sujaygarlanka** [comment]
I spoke to our team responsible for the this API endpoint. They are looking into it. We'll keep you updated on any progress.

**Comment by sujaygarlanka** [comment]
Hello @winstonxie3000, In order to properly escalate this issue with our file system team, could you create a support ticket [here](https://community.box.com/t5/Contact-Support/ct-p/BoxSupport).

**Comment by Syed-SnapLogic** [comment]
@sujaygarlanka , I am also facing the same issue with the box java sdk 2.4.0.  Can I know if the issue reported by @winstonxie3000 is resolved, and if yes, the version that contains the fix?  thnx.

**Comment by sujaygarlanka** [comment]
@Syed-SnapLogic This is an API issue, so you won't have to update your SDK when this is fixed. Unfortunately, this has not been fixed yet and is unlikely to be fixed in the near future. We recommend using a mechanism like what @mmarmol mentioned above.

**Comment by cwatsoniac** [comment]
FYI, still not fixed.  We opened another new case with Box.
