### ISSUE TITLE
Got java.lang.NullPointerException since BoxAPIResponse.bodyString is null 

### ISSUE THREAD

**Issue by winstonxie3000** [box/box-java-sdk#754]
API https://api.box.com/2.0/folders  JAVA BOX SDK 2.20.1, Java version: openjdk 1.8.0_201

Sample code:
```
    public static void main(String[] args) {

        ExecutorService executorService
                = Executors.newFixedThreadPool(2000);
        for (int i = 0; i < 1000; i++) {
            executorService.execute(()->{
                BoxAPIConnection boxAPIConnection = new BoxAPIConnection("MTlGdNwJLXqfH5HsO4pmUCEmHOsiCIXB");
                BoxFolder rootFolder = BoxFolder.getRootFolder(boxAPIConnection);

                try {
                    RateLimiter rateLimiter = RateLimiter.create(2.0);
                    rateLimiter.acquire();
                    BoxFolder.Info folderInfo = rootFolder.createFolder("testDuplicatedFolder");
                    logger.info("creating folder {} in {}", folderInfo.getName(), System.currentTimeMillis());
                } catch (Exception e) {
                    if (e instanceof NullPointerException)
                        logger.error("Exception occur", e);
                }
            });
        }

    }

```
The exception is as below. BoxAPIResponse.bodyString is null, so when the sdk try to convert bodyString to json it eat the real exception and throws out the NPE.
```
Caused by: java.lang.NullPointerException: null
        at java.io.StringReader.<init>(StringReader.java:50)
        at com.eclipsesource.json.JsonParser.<init>(JsonParser.java:44)
        at com.eclipsesource.json.JsonValue.readFrom(JsonValue.java:105)
        at com.eclipsesource.json.JsonObject.readFrom(JsonObject.java:138)
        at com.box.sdk.BoxAPIResponseException.<init>(BoxAPIResponseException.java:43)
        at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:90)
        at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:549)
        at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:326)
        at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:301)
        at com.box.sdk.BoxFolder.createFolder(BoxFolder.java:324)
```

**Comment by sujaygarlanka** [comment]
@winstonxie3000 Sorry, can't replicate this issue. If you are still encountering this issue, can you give more information?

**Comment by sujaygarlanka** [comment]
Actually, I think a better option would be for you to attach the Java SDK logs here. The Java SDK logs everything using the standard Java Logger class.

**Comment by winstonxie3000** [comment]
@sujaygarlanka Thanks for looking into it. Actually I've attached the sdk stack-trace log and that's all the log I can get. I think the cause should be the responseObj.bodyToString() in BoxAPIResponseException.java:43 become null. Can you search in your API backend server log based on the timestamp I provided: "2019-11-20 06:08:35.309000" timezone: UTC , actually around that time period there were quite a bunch of NPE occured. you should be able to get detailed logs on your backend. Thanks a lot.

**Comment by sujaygarlanka** [comment]
@winstonxie3000 I took a look at our logs and our API had some issues around that time. It was not returning response bodies, which is why the SDK was throwing the Null pointer exception. If this keeps happening, please let us know.
