### ISSUE TITLE
Null pointer exception when uploading a file

### ISSUE THREAD

**Issue by A01123748** [box/box-java-sdk#755]
- I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Receiving a null pointer exception when uploading a file through java api. This issue is intermittent. Sometimes the file gets uploaded correctly, sometimes it throws this error.

### Versions Used
Java SDK: box-java-sdk-2.20.1
Java: 1.8.0_162

### Steps to Reproduce
BoxUtils.java:

	public static Object[] upload(String processID, String tokenIndex ,String filePath, String fileNameInServer, String folderId, BoxAPIConnection api, String asUser, String username, int attempt, int counter) {
		
		BoxAPIConnection client;
		
		try {
			client = api;
			String userString = asUser != null ? asUser : username;
			Utils.print(processID, "Uploading to the box of: " + userString + " try no."+attempt, username);
			
			if(StringUtils.isNotEmpty(asUser)) {
				client.asUser(asUser);
			}else {
				BoxFolder rootFolder = BoxFolder.getRootFolder(client);
				BoxItem.Info itemInfo2 = rootFolder.getInfo();
				Utils.message(processID, "Item info: "+itemInfo2.getName(), username);
			}
		}catch (Exception e) {
			e.printStackTrace();
			if(asUser != null && !asUser.isEmpty()) {
				String newFilePath = filePath.substring(0, filePath.lastIndexOf("/log")) + "/classes/config";
				client = connectToBox(newFilePath,0);
			}
			else {
				client = tokens.get(tokenIndex);
			}
		}
			
		int pos = filePath.lastIndexOf("\\");
		if(pos == -1){	//Unix servers
			pos = filePath.lastIndexOf("/");
		}
		String fileName = filePath.substring(pos+1);
		BoxFolder folder = new BoxFolder(client, folderId);
		
		String link = null;
		FileInputStream stream = null;
		File bbFile = null;
		try {
			bbFile = new File(filePath);
			if(bbFile.exists()) {
				stream = new FileInputStream(bbFile);
				folder.canUpload(fileName, bbFile.length());
				Utils.message(processID, "Uploading file...", username);
				Info infoFile = smartUploadFile(processID, folder, stream, fileNameInServer, bbFile.length(), username);
				BoxFile file = new BoxFile(client, infoFile.getID());
				link = getsharedLink(file);
			}
		}catch (Exception e) {
			Utils.message(processID, "Exception: "+e.getMessage(), username);
			e.printStackTrace();
			if(e.getMessage().contains("item_name_in_use") || e.getMessage().contains("Item with the same name already exists")) {
				String newfileNameInServer = fileNameInServer + "(" + counter++ + ")";
				return upload(processID, tokenIndex, filePath, newfileNameInServer, folderId, api, asUser, username, attempt, counter);
			}
			else {
				if(attempt < 5) {
					try {
						Thread.sleep(1000 * 60 * 5);
					} catch (InterruptedException e2) {
						Utils.message(processID, "Exception: "+e2.getMessage(), username);
						e2.printStackTrace();
					}
					return upload(processID, tokenIndex, filePath, fileNameInServer, folderId, api, asUser, username, ++attempt, counter);
				}
			}
			
		}
		finally {
			try {
				stream.close();
			} catch (IOException e) {
				Utils.message(processID, "Exception: "+e.getMessage(), username);
				e.printStackTrace();
			}
		}
		
		Object[] res = new Object[2];
		//client.asSelf();
		res[0] = link;
		res[1] = client;
		return res;
	}

	private static Info smartUploadFile(String processID, BoxFolder folder, InputStream stream, String fileName, long fileSize, String username) {
		Info infoFile = null;
		try {
			Utils.message(processID, "smartUploadFile: folder: " + folder.getID(), username);
			Utils.message(processID, "smartUploadFile: stream: " + stream, username);
			Utils.message(processID, "smartUploadFile: fileName: " + fileName, username);
			Utils.message(processID, "smartUploadFile: fileSize: " + fileSize, username);
			if(fileSize > 20000000) {
				infoFile = folder.uploadLargeFile(stream, fileName, fileSize);
			}else {
                                          **//The line below is throwing the null pointer exception**
					infoFile = folder.uploadFile(stream, fileName);
				}
		}
		catch(InterruptedException | IOException e) {
			Utils.message(processID, "Exception: "+e.getMessage(), username);
			e.printStackTrace();
                       
			infoFile = folder.uploadFile(stream, fileName, fileSize, new ProgressListener() {
			    public void onProgressChanged(long numBytes, long totalBytes) {
			        double percentComplete = (float)numBytes / totalBytes * 100.0;
			        if(Math.floor(percentComplete)%0.0==0 || Math.floor(percentComplete)%25.0==0 || Math.floor(percentComplete)%50.0==0 || Math.floor(percentComplete)%75.0==0 || Math.floor(percentComplete)%100.0==0)
			        	Utils.message(processID, "Uploading file..."+percentComplete +"%", username);
			    }
			});
		}
		return infoFile;
	}

### Error Message, Including Stack Trace
java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:50)
	at com.eclipsesource.json.JsonParser.<init>(JsonParser.java:44)
	at com.eclipsesource.json.JsonValue.readFrom(JsonValue.java:105)
	at com.eclipsesource.json.JsonObject.readFrom(JsonObject.java:138)
	at com.box.sdk.BoxAPIResponseException.<init>(BoxAPIResponseException.java:43)
	at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:90)
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:553)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:326)
	at com.box.sdk.BoxFolder.uploadFile(BoxFolder.java:482)
	at com.box.sdk.BoxFolder.uploadFile(BoxFolder.java:439)
	at com.utils.BoxUtils.smartUploadFile(BoxUtils.java:134)
	at com.utils.BoxUtils.upload(BoxUtils.java:87)

**Comment by winstonxie3000** [comment]
Similar problem as I encountered in https://github.com/box/box-java-sdk/issues/754 as BoxAPIResponse.bodyString becomes null.

**Comment by A01123748** [comment]
Similar problem happening when generating shared link:
 java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:50)
	at com.eclipsesource.json.JsonParser.<init>(JsonParser.java:44)
	at com.eclipsesource.json.JsonValue.readFrom(JsonValue.java:105)
	at com.eclipsesource.json.JsonObject.readFrom(JsonObject.java:138)
	at com.box.sdk.BoxAPIResponseException.<init>(BoxAPIResponseException.java:43)
	at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:90)
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:549)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:326)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:301)
	at com.box.sdk.BoxFile.updateInfo(BoxFile.java:598)
	at com.box.sdk.BoxFile.createSharedLink(BoxFile.java:158)
	at com.utils.BoxUtils.getsharedLink(BoxUtils.java:190)

**Comment by sujaygarlanka** [comment]
@A01123748 I am trying to debug the error, but am having issues replicating it. The best way to help us debug the issue is if you can make the getSharedLink request in Postman and share the body that is returned with us. If you need any hep with this, this is a good guide: https://developer.box.com/en/guides/tooling/postman/.

**Comment by A01123748** [comment]
This integration uses JWT authentication, which makes it nearly to impossible to run with Postman.
If you have another ideas on how to look at the actual request being send to the server, please send  me more information regarding. Also, as the issue description indicates, this is an issue really hard to replicate. Something that might make it more reproducible for you will be uploading multiple files at the same time. I'm testing with up to 20 files at the same time, most of them similar size (aprox. 20 MB). Let me know if there is some more information that I can send you.

**Comment by sujaygarlanka** [comment]
You can run this with Postman by generating an access token in the [developer console](https://cloud.app.box.com/developers/console) for the app. However, I think a better option would be for you to attach the Java SDK logs. The Java SDK logs everything using the standard Java Logger class. If you can simplify your code to only contain the call that is causing the issue, then run it and attach the produced logs here, that would be very helpful.

**Comment by A01123748** [comment]
The code is already oversimplified and the stack-trace is attached as well. Not sure what else you want me to add here.

**Comment by sujaygarlanka** [comment]
@A01123748 I was able to look into the #754 issue, which was the same as yours. That developer issue stemmed from an issue of our API and not the SDK. I believe the same applies in your case. If you continue to have this issue, please let us know. In the future, if you want to see finer a level of logging, go to your `logging.properties` file at the following path `/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre/lib/logging.properties` and change the `.level = INFO` to log level to `.level = FINER`. This will allow you to see the requests and responses coming back.

**Comment by PJSimon** [comment]
@A01123748 I'm closing this issue as we haven't heard back from you in a while.  If you'd like to continue the conversation, please just re-open the issue!  Thanks!
