### ISSUE TITLE
Weblink with Empty URL throwing the error

### ISSUE THREAD

**Issue by samrajcse** [box/box-java-sdk#756]
Hi Team,

When we are listing down the folder we have weblink with empty url (I know we can't able to create now but might be created earlier). When I am iterating the Box folder api, it is throwing the below error. Same error in very latest API 2.41.0 too.

{
            "type": "web_link",
            "id": "<ID>",
            "sequence_id": "4",
            "etag": "4",
            "name": "<NAME>",
            "url": ""
        }

Exception stack trace:
		
Exception in thread "main" com.box.sdk.BoxAPIException: Couldn't parse url for weblink
	at com.box.sdk.BoxWebLink$Info.parseJSONMember(BoxWebLink.java:279)
	at com.box.sdk.BoxJSONObject.update(BoxJSONObject.java:193)
	at com.box.sdk.BoxJSONObject.<init>(BoxJSONObject.java:52)
	at com.box.sdk.BoxJSONObject.<init>(BoxJSONObject.java:42)
	at com.box.sdk.BoxResource$Info.<init>(BoxResource.java:175)
	at com.box.sdk.BoxItem$Info.<init>(BoxItem.java:234)
	at com.box.sdk.BoxWebLink$Info.<init>(BoxWebLink.java:245)
	at com.box.sdk.BoxItemIterator.next(BoxItemIterator.java:45)
	at com.box.sdk.BoxItemIterator.next(BoxItemIterator.java:8)
	at 
Caused by: java.net.MalformedURLException: no protocol: 
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at com.box.sdk.BoxWebLink$Info.parseJSONMember(BoxWebLink.java:277)
	... 10 more

**Comment by PJSimon** [comment]
Hi, @samrajcse!  Thanks for submitting this issue.  This week is the Thanksgiving holiday, so we will take a look next week and get back to you.

**Comment by sujaygarlanka** [comment]
@samrajcse When a weblink is created, a valid url must be specified (https://developer.box.com/en/reference/post-web-links/). So when you get a weblink it should have a valid url. So if the url returned is invalid, the SDK will and should throw an error. In your case, an empty string is returned and is an invalid URL. To avoid getting the URL back, you can pass in a fields parameters. This will specify which fields to only be returned. For example, `https://api.box.com/2.0
/web_links/:web_link_id?fields=name` will only return the name. You can specify fields that don't include the URL, which will prevent you from having this issue. Hope this helps!

**Comment by samrajcse** [comment]
Hi Sujay,

Problem is we are fetching the list of the record that contains the files, folder and weblink. When we are iterating the files, it throws the exception. 

If the code in BoxWebLink.java line #276, we need to have this condition to avoid this in future. 

 if (memberName.equals("url") &&value!=null && value.asString()!=null && !value.asString().isEmpty()) {

**Comment by sujaygarlanka** [comment]
@samrajcse You can catch the exception and continue iterating. The only issue will be that you won't be able to get the other data from that weblink. We can add the checks you mention above, but we would like to throw an error for behavior that is not expected behavior for the API at this point. An empty or nil url is part of that unexpected behavior. If you still need the data for the weblinks that don't have URLs we can look into adding this check. However, if you only need to continue to iterate, I would catch the error and continue.

**Comment by PJSimon** [comment]
Hi @samrajcse!  I'm closing this issue, assuming @sujaygarlanka's recommendation worked for you.  If that's not the case, please just re-open this issue!  Thanks!
