### ISSUE TITLE
Collaboration with Custom email message

### ISSUE THREAD

**Issue by yogaredhat** [box/box-java-sdk#758]
Hi Team ,

I checked collaboration API here : https://developer.box.com/en/reference/post-collaborations/#request

We are using box API to send collaboration req to User and want to add custom email message while adding collaboration for single user.

But I Could not find any option to add custom email message while adding collaboration for a single user or a single group to a file or folder. 

Would appreciate if is there any work around  for this or something that this functionality that can be added ..

**Comment by PJSimon** [comment]
Hi @yogaredhat!  Unfortunately, this functionality does not exist.  I sent a feature request to the owning team, here at Box.  I'm not sure if it's something they can add to their roadmap in the near future, but if I hear any update on the request, I will update you here.

**Comment by yogaredhat** [comment]
@PJSimon Thanks for this updates.

**Comment by deepikapotnuru** [comment]
HI @PJSimon Could you please update on issue. We have urgent requirement.

**Comment by PJSimon** [comment]
@yogaredhat could you please email me (see my email address in my GitHub profile) so I can connect you to the Product Manager for the team that owns this service?  He would like to understand your use case further.

I have already connected him with @deepikapotnuru , so hopefully we can get this feature onto the team's road map.  Thanks!

**Comment by antusus** [comment]
Hello,
@yogaredhat, @deepikapotnuru I can see that request sent by @PJSimon was closed by the owning team and will not be developed.

You can try and reach out using [Developer portal](https://support.box.com/hc/en-us/community/topics/360001932973-Platform-and-Developer-Forum) of [file a support ticket](https://support.box.com/hc/en-us/requests/new).
Those two ways can help you connect with API developers directly.

Closing the issue as we have no immediate resolution for the requested enhancement.
