### ISSUE TITLE
As-User support

### ISSUE THREAD

**Issue by gcurtis** [box/box-java-sdk#76]

**Comment by robertrlandry** [comment]
So, I take it the as-user header is still unsupported? Is there an ETA for this? I appreciate any insights.

**Comment by dorfire** [comment]
Any updates?

**Comment by nddipiazza** [comment]
Any updates?

**Comment by mattwiller** [comment]
@robertrlandry @dorfire @nddipiazza Unfortunately, there's currently no straightforward way to set the As-User header but I think it can be done with a request interceptor.  Something like this should work:

```java
api.setRequestInterceptor(new RequestInterceptor() {
    @Override
    public BoxAPIResponse onRequest(BoxAPIRequest request) {
        request.addHeader("As-User", "USER_ID");
        return null;
    }
});
```

Then, to remove the As-User state:

```java
api.setRequestInterceptor(null);
```

Does this solve your problem?

**Comment by mattwiller** [comment]
@robertrlandry @dorfire @nddipiazza We just introduced a convenience method to set this header on the `BoxAPIConnection` in v2.16.0 of the SDK — see the [documentation](https://github.com/box/box-java-sdk/blob/master/doc/overview.md#as-user) for more information.

**Comment by nddipiazza** [comment]
kick ass. @mattwiller  we will try it out.
