### ISSUE TITLE
Retrieve for a User all his groups

### ISSUE THREAD

**Issue by alessandrobenedetti** [box/box-java-sdk#77]
Hi,
After a quick overview of the Java Client I was wondering if the API endpoint to retrieve the membership per user is available in the java Client:

https://developers.box.com/docs/#groups-get-all-group-memberships-for-a-user

Because I was not able to find it in BoxUser class.

Cheers

**Comment by gcurtis** [comment]
Unfortunately, that endpoint isn't in the SDK yet - we are working on adding it though.

**Comment by sohtsuka** [comment]
Hi @gcurtis,

I made up membership-related features (including the one requested by this issue) for my own needs, and I think I can make them clean and contribute, if there are no problems. 

Added classes and methods are like following:
```java
// GET|PUT|DELETE /group_memberships/{id}
public class BoxGroupMembership extends BoxResource {
    public BoxGroupMembership(BoxAPIConnection api, String id) { ... }
    public Info getInfo() { ... }
    public void updateInfo(Info) { ... }
    public void delete() { ... }
    public class Info extends BoxResource.Info { ... }
    public enum Role { ... }
}
```

BoxGroup class:
```java
// GET /groups/{id}/memberships
public Collection<BoxGroupMembership.Info> getMemberships() { ... }
// POST /group_memberships
public BoxGroupMembership.Info addMembership(BoxUser user) { ... }
public BoxGroupMembership.Info addMembership(BoxUser user, BoxGroupMembership.Role role) { ... }
```

BoxUser class:
```java
// GET /users/{id}/memberships
public Collection<BoxGroupMembership.Info> getMemberships() { ... }
```

If you have already implemented similar features, I will just wait for the next release.
Can I get your thoughts?

**Comment by gcurtis** [comment]
Hey @sohtsuka, sorry for the delayed response.

This looks great! Go ahead and submit a pull request for it and we can get started on merging it in.
