### ISSUE TITLE
Trying to download versions of a file with Java sdk.  Keep getting the current version

### ISSUE THREAD

**Issue by StevenRieger** [box/box-java-sdk#776]
- [x ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Using the api to download all files in a folder including versions of files
Using the exact sample code provided by Box documentation
When I download a version of the file, it's only downloading the current file.

### Versions Used
Java SDK: 2.32.0 jar
Java: 1.8.0_191

### Steps to Reproduce
See Code Below...
### Error Message, Including Stack Trace
No Error
```
public void copyFile( BoxItem.Info fileInfo, Path localFolderPath )
	{
		try
		{

			// Download the current file
			downloadFile( fileInfo, localFolderPath );

			// If there are any versions, download the version files.
			BoxFile aBoxFile = new BoxFile( boxFileExport.getBoxService().getBoxAPIConnection(), fileInfo.getID() );
			List<BoxFileVersion> fileVersions = (List<BoxFileVersion>) aBoxFile.getVersions();
			for (BoxFileVersion aFileVersion : fileVersions)
			{
				downloadFile( aFileVersion, localFolderPath );
			}

		} catch ( Exception e )
		{
			boxFileExport.LMSLogger.log( Level.SEVERE, "An error occurred: " + e.getMessage() );
		}
	}
```
```
public void downloadFile( BoxFileVersion aFileVersion, Path localFolderPath )
	{
		FileOutputStream stream;
		String localFilePath;

		try
		{
			// Format the modified date from this version of the file to be used in the name of the downloaded file.
			String pattern = "yyyy-MM-dd";
			SimpleDateFormat simpleDateFormat = new SimpleDateFormat( pattern );
			String dateStr = simpleDateFormat.format( aFileVersion.getModifiedAt() );

			// Break up the file name to name and extension
			String fileName = aFileVersion.getName();
			int dot = fileName.lastIndexOf( "." );
			String fileExtension = fileName.substring( dot + 1 );
			fileName = fileName.substring( 0, dot );

			// Build the path and file name to be downloaded
			localFilePath = localFolderPath.resolve( Paths.get( fileName + " " + dateStr + "." + fileExtension ) ).toAbsolutePath().toString();

			// If local file exists
			File localPathFile = new File( localFilePath );
			if( localPathFile.exists() )
			{
				// Fetch the local existing file date
				long localFileDate = localPathFile.lastModified();
				// Fetch the BoxVersionFile modified date. Verify the versioned file has a modified date...
				long boxFileDate = ( aFileVersion.getModifiedAt() != null ) ? aFileVersion.getModifiedAt().getTime() : System.currentTimeMillis();

				// if box file date is older or equal than local file date
				if( boxFileDate <= localFileDate )
					return;
			}
			stream = new FileOutputStream( localFilePath );
			boxFileExport.LMSLogger.log( Level.INFO, "Downloading: " + localFilePath );
			// BoxFile boxFile = new BoxFile( boxService.getBoxAPIConnection(), aFileVersion.getID() );
			aFileVersion.download( stream );
			stream.close();
			boxFileExport.setNumFilesCopied( boxFileExport.getNumFilesCopied() + 1 );
		} catch ( Exception e )
		{
			boxFileExport.LMSLogger.log( Level.SEVERE, "An error occurred: " + e.getMessage() );
		}
	}

```

**Comment by sujaygarlanka** [comment]
@StevenRieger I tried out our sample code for downloading a version and it is working in my environment. The believe the issue may be somewhere in your code. Perhaps the localFilePath is not properly updated. If so, then each file version downloaded could be overwriting the previous version, so at the end you are left with only the most recent version.

**Comment by StevenRieger** [comment]
It downloads the file however the content isn’t the older version of the file. Have you confirmed yours is?

Regards,

STeveR
Mobile: 847.219.3961
Office: 847.777.7094

________________________________

**Comment by sujaygarlanka** [comment]
@StevenRieger Ya, I did a visual inspection of the files and they were older versions. Also, just to clarify, `getVersions()` will return all versions except the most current version. The most current version must be retrieved using the download method for a Box File.

**Comment by sujaygarlanka** [comment]
Could you show your logs or print statements?

**Comment by sujaygarlanka** [comment]
@StevenRieger Is this still an issue?

**Comment by StevenRieger** [comment]
Yes it is.

I’m working on creating a small program to download a single file with version history that I can send to you with logs etc.

Please give me a couple days to finish this…

Regards,
STEVEN RIEGER
Director Information Technology
25 Northwest Point Blvd
Suite 330
Elk Grove Village, IL 60007
Direct:  847.777.7094
Mobile:  847.219.3961

**Comment by PJSimon** [comment]
Hi @StevenRieger, 

Just checking in!  How's it going?  Were you able to resolve your issue?

Thanks,

Patrick

**Comment by PJSimon** [comment]
Closed by accident, sorry!  :^)

**Comment by StevenRieger** [comment]
Strangely it started working. Go ahead and close the incident

Regards,

STeveR
Mobile: 847.219.3961
Office: 847.777.7094

________________________________

**Comment by PJSimon** [comment]
Hooray!
