### ISSUE TITLE
BoxAPIConnection  check() method ?

### ISSUE THREAD

**Issue by alessandrobenedetti** [box/box-java-sdk#78]
Hi,
what do you think of this use case ?
As a User I would like to get an instance of this class for example :
api = new BoxAPIConnection(clientId,clientSecret,accessToken,refreshToken);
I would like to call a method ( api.check()  for example) to verify if the parameter are correct, and if not which one is not.
Right now the one that is closer to this feature is the :
"refresh()" that gives precise information about the parameters but it lacks of the "Access Token" check.

Cheers

**Comment by gcurtis** [comment]
A simple way to do this is by just making an API call and seeing if it succeeds. For example, a simple call would be:

```java
BoxAPIConnection api = new BoxAPIConnection(clientId, clientSecret, accessToken, refreshToken);

// This call will throw a BoxAPIException if authentication failed.
BoxUser.getCurrentUser(api);
```

You can also call [`BoxAPIException.getResponse()`](http://opensource.box.com/box-java-sdk/javadoc/com/box/sdk/BoxAPIException.html#getResponse()) to see the error message returned by the server.

Other than that, there isn't an API endpoint for checking if authentication information is correct - so I'm not sure how a `check()` method would be able to validate that.
