### ISSUE TITLE
Need to support getAllGroupsByName with fields option 

### ISSUE THREAD

**Issue by wadahiro** [box/box-java-sdk#786]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Currently, the SDK has the ability to get groups by name ([`getAllGroupsByName`](https://github.com/box/box-java-sdk/blob/d32a97db2e13a0296d102ae1682a7a799ee93857/src/main/java/com/box/sdk/BoxGroup.java#L150)) but there is no `fields` option.

### Versions Used
Java SDK: 2.44.1
Java: 1.8.0_222

### Steps to Reproduce
NA

### Error Message, Including Stack Trace
NA

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by wadahiro** [comment]
In my project using the SDK, I've added the following methods as a workaround:

https://github.com/openstandia/connector-box/blob/62e135f6aa956a59c0518c7144eacf101fe3dadd/src/main/java/com/box/sdk/AdditionalAPI.java#L11-L35

It would be great if the SDK could support this feature. Is it possible to accept a pull request for this request?

**Comment by sujaygarlanka** [comment]
@wadahiro We would love to take a look at a PR! The main things we look for are an implementation that is consistent with how it is done elsewhere in the SDK and some simple testing. Testing can include amending an existing test or creating a new one. Thanks!

**Comment by wadahiro** [comment]
@sujaygarlanka I submitted the PR. Could you review it?

https://github.com/box/box-java-sdk/pull/789

**Comment by PJSimon** [comment]
Kudos to you, @wadahiro for:
1. Reporting this issue
1. Fixing it for everyone!

It was our pleasure to get this approved and merged for you!  Thank you for your contribution!
