### ISSUE TITLE
Provide options to update user properties

### ISSUE THREAD

**Issue by tcharles79** [box/box-java-sdk#79]
Hello,

I'm looking for options to update user storage, email alias, primary login through SDK. These features are available in current SDK but no in new SDK. Please provide. Thanks.

getUsersManager().addEmailAlias(..)
getUsersManager().updateUserPrimaryLogin(..)
getUsersManager().updateUserInformaiton(..)

Cheers

**Comment by gcurtis** [comment]
This is the next feature I plan on adding to the SDK. I should be able to get something out before the end of next week.

**Comment by gcurtis** [comment]
Hey @tcharles79, the changes for updating a user's info and email aliases are in now.

Updating a user's primary login (along with any other properties) can be done by updating their info:

```java
BoxUser user = new BoxUser(api, "id");
BoxUser.Info info = user.new Info();
info.setLogin("other-email@domain.com")
user.updateInfo(info);
```

Retrieving, adding, and deleting email aliases can be done with the `getEmailAliases()`, `addEmailAlias()`, and `deleteEmailAlias()` methods on `BoxUser`.

Please give these changes a try and let me know if you run into any issues.

**Comment by tcharles79** [comment]
If i remove the on-behalf-of header and adding the user as BoxUser user = new BoxUser(api, userId); than it works. I'm able to change the user storage through admin token (client id).

Thanks.
