### ISSUE TITLE
How to get the MD5 of a file

### ISSUE THREAD

**Issue by dinukadesilva** [box/box-java-sdk#793]
I can see that the SHA1 can be taken as following. 

```
BoxAPIConnection api = new BoxAPIConnection("-- token --");
BoxFile boxFile = new BoxFile("-- box-file-id --");
BoxFile.Info boxFileInfo = boxFile.getInfo();

boxFileInfo.getSha1()
```

But, I need to get the MD5. Is there any way I could get it.

**Comment by sujaygarlanka** [comment]
@dinukadesilva Our API does not return the MD5 value for a file, so our SDK can't get it.
