### ISSUE TITLE
unable to run example.Main after setup first time due to proxy error

### ISSUE THREAD

**Issue by amitbatajoo** [box/box-java-sdk#794]
How to setup proxy for box java api.?
All the setup was done by following the document: https://github.com/box/box-java-sdk
Latest version.
But..
I am not able to run the example main project due to unable to create network connection error message.
Please anyone can suggest me how to correct the proxy setup for network connection problem.
Thank you in advance!

**Comment by PJSimon** [comment]
Did you try calling `setProxy` in BoxAPIConnection.java? 
https://github.com/box/box-java-sdk/blob/165ade6fc3c76e69da51350f8d958b5a6b27ad8f/src/main/java/com/box/sdk/BoxAPIConnection.java#L517

If that doesn't resolve your issue, please re-open this issue and we'll go from there!  

Thanks!

**Comment by amitbatajoo** [comment]
@PJSimon Thank you very much for your instruction.
I just corrected and set the setProxy method with my proxy informaiton.

I just code new error message:

Exception in thread "com.box.sdk.BoxAPIException:Couldn't connect to the Box API due to network error"
 at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:649)
.......................
......................
Caused by:java.io.IOException:Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
---

How can we solve it?

Please help me.

Thank you in advance!
