### ISSUE TITLE
Is it necessary to change URLs in BoxAPIConnection.java for private box developer console?

### ISSUE THREAD

**Issue by amitbatajoo** [box/box-java-sdk#798]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue

If I use the box api for my private organization. Do I need to change the URLS in the BoxAPIConnection.java or the default urls is used. I am unable to connect the box.
private static final String AUTHORIZATION_URL = "https://xxxx.account.box.com/api/oauth2/authorize	";
private static final String TOKEN_URL_STRING = "https://xxxx.api.box.com/oauth2/token";
private static final String REVOKE_URL_STRING = "https://xxxx.api.box.com/oauth2/revoke";
private static final String DEFAULT_BASE_URL = "https://xxxx.api.box.com/2.0/";
 private static final String DEFAULT_BASE_UPLOAD_URL = "xxxx.https://upload.box.com/api/2.0/";

### Versions Used
Java SDK: box-java-sdk:2.32.0
Java: open-jdk 12.0.1

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by sujaygarlanka** [comment]
@amitbatajoo No, you should not have to change the URLs for your organization. Your token may be incorrect. Try getting a token from your developer console and make a request through the SDK with that.

**Comment by amitbatajoo** [comment]
@sujaygarlanka 
Thank you very much for your instruction.
I just tried to run with all the setup according to https://github.com/box/box-java-sdk/blob/master/doc/authentication.md#developer-token document. 
But still it returns the error message:

Exception in thread "main" com.box.sdk.Box.APIResponseException: The API returned an error code [401 | a8cxtnge..............eb] unauthorized- Unauthrized-Cannot authorize with this serivce
  at com.boxk.sdk.BoxAPIResponse.<init>(BoxAPI Response.java.92)
............................
.......................
(sorry I cannot type all error message, its too long to type all.)
One more thing, I have to connect the API after setting the porxy setup. So If my proxy is not correct, can you please suggest some example to setup proxy for box.api in java.

Please help me!

Thank you in advance.

**Comment by sujaygarlanka** [comment]
The Java SDK only has basic proxy support. It does not support NTLM, socks or other types. Is your proxy basic http or https?

**Comment by amitbatajoo** [comment]
It does not support NTLM, socks or other types. Is your proxy basic http or https?
> my proxy is https.

Is there any solution for this?

**Comment by amitbatajoo** [comment]
The issue is sovled! 
Thank you.
