### ISSUE TITLE
Unabe to run runAccessAsAppUser

### ISSUE THREAD

**Issue by amitbatajoo** [box/box-java-sdk#799]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue. 

### Description of the Issue

* When I run the runAccessAsAppUser in gradle after all the setup and also app authentication approved. I got the following error message.
* I have also set the proxy host and username and password for the BoxAPIConnection.

> Task :runCreateAppUser
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further detail
s.
Exception in thread "main" com.box.sdk.BoxAPIResponseException: The API returned
 an error code [400] unauthorized_client - This app is not authorized by the ent
erprise admin
        at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:92)
        at com.box.sdk.BoxJSONResponse.<init>(BoxJSONResponse.java:32)
        at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:677)
        at com.box.sdk.BoxAPIRequest.sendWithoutRetry(BoxAPIRequest.java:326)
        at com.box.sdk.BoxDeveloperEditionAPIConnection.authenticate(BoxDevelope
rEditionAPIConnection.java:342)
        at com.box.sdk.BoxDeveloperEditionAPIConnection.tryRestoreUsingAccessTok
enCache(BoxDeveloperEditionAPIConnection.java:468)
        at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnecti
on(BoxDeveloperEditionAPIConnection.java:203)
        at com.box.sdk.BoxDeveloperEditionAPIConnection.getAppEnterpriseConnecti
on(BoxDeveloperEditionAPIConnection.java:230)
        at com.box.sdk.example.CreateAppUser.main(CreateAppUser.java:38)

What can be the solution for this kind of error?
Also, is there any sample example of proxy setup for box api connection.
### Versions Used
Java SDK: 2.46.0
Java: open jdk 12.0.1

Please help me to solve this error problem.

Thank you in advance.

**Comment by carycheng** [comment]
Hey @amitbatajoo did you have your app approved by the admin of your Box enterprise? Before you can access Box API's via your application you will need to have your admin approve your application through the admin console. 

This can be done by providing them with a copy of you client id(api key) and having them input it in the: Admin Console -> Apps Tab(found in the left nav bar) -> "Custom Apps" Tab -> Authorize New App.

Please let us know if you run into other issues or if there is anything else we can clarify for you.

Thank you!

**Comment by amitbatajoo** [comment]
@carycheng 
Thank you for your reply.
I have done all the setup according to the documents and your instruction. But still I have following error.

WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" com.box.sdk.BoxAPIResponseException: The API returned an error code [400] invalid_request - Cannot obtain token based on the enterprise configuration for your app
        at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:92)
        at com.box.sdk.BoxJSONResponse.<init>(BoxJSONResponse.java:32)

Please help me to solve it!

Thank you in advance.

**Comment by amitbatajoo** [comment]
Thank you for the support. I solved the issue. 
I am going to close this issue.
