### ISSUE TITLE
how to download all files or folder from box using api in java

### ISSUE THREAD

**Issue by amitbatajoo** [box/box-java-sdk#801]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue

Try to download the multiple files from the box folder. The used example source code is give in this link:

https://developer.box.com/guides/downloads/folder/

All the authentication and permission for the apps is done according to documents .
https://github.com/box/box-java-sdk

I am able to download single file with same setting.

# This error message is similar to authorized setting for the apps, but in my case all the setup is completed and also able to download single file using simple download method. 

When I try to download multiple files and folder, this error is generated

Error Message:

> Task :runBoxPlayground
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/C:/Users/admin/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.60/bd47ad3bd14b8e82595c7adaa143501e60842a84/bcprov-jdk15on-1.60.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" com.box.sdk.BoxAPIResponseException: The API returned an error code [400 | jihfogge68uux76f.084990a20e8efccb7bf74e9664afa2355] bad_request - Bad Request
        at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:92)
        at com.box.sdk.BoxJSONResponse.<init>(BoxJSONResponse.java:32)
        at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:677)
        at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:381)
        at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:348)
        at com.box.sdk.BoxFolder.getInfo(BoxFolder.java:289)
        at com.box.sdk.example.Playground.main(Playground.java:27)

> Task :runBoxPlayground FAILED

FAILURE: Build failed with an exception.
 
### Versions Used
Java SDK: 2.46.0 (Outh2+JWT)
Java: open jdk 12.0.1

Anyone please help me, what can be the solution. 
If there any working code for files and folder download from box using api. Please suggest me.

Thank you in advnace!

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by PJSimon** [comment]
Hi @amitbatajoo , we'll take a look ASAP!  Thanks!

**Comment by amitbatajoo** [comment]
> Hi @amitbatajoo , we'll take a look ASAP! Thanks!

hello @PJSimon , Thanks for your reply, I will be waiting for your next reply!
