### ISSUE TITLE
How to get File Request Link for a folder

### ISSUE THREAD

**Issue by amitbatajoo** [box/box-java-sdk#806]
- [ X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ X] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported.
- [ X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Need help!

# How can we get the Link for file request to a folder using box-api sdk java. 
So that we can we can send by email to friend to upload files. ?

# Is it possible to send email by using api.?

Please suggest me the solution?

Thank you in advance!

![FileRequest](https://user-images.githubusercontent.com/6213118/82207869-7bfa0f00-9945-11ea-8502-2761b0b48d9e.PNG)

### Versions Used
Java SDK: 2.47
Java: open jdk 12.0.2

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by sujaygarlanka** [comment]
@amitbatajoo This was just recently released and there is still no endpoint coverage for this. When there is, we will add it to the Java SDK and let you know.

**Comment by amitbatajoo** [comment]
@sujaygarlanka Thank you for your reply. Please teach me after the it is solved.
Also, is there any method to send file send request by the use of email using sdk api java?
If there is, please help me!

**Comment by amitbatajoo** [comment]
@sujaygarlanka @PJSimon 
>This was just recently released and there is still no endpoint coverage for this. When there is, we will >add it to the Java SDK and let you know.
Is it  possible to tell me, how long time it will take to add this feature in api?
Hope it will happen soon.

Thank you in advance!

**Comment by sujaygarlanka** [comment]
@amitbatajoo The API coverage is tentatively planned for August. This is not a hard commit internally, so we cannot guarantee it will be out by then.

**Comment by antusus** [comment]
Hello @amitbatajoo,
SDK allows you to create shared link to a folder.
You can find documentation here [Create Shared Link to a folder](https://github.com/box/box-java-sdk/blob/main/doc/folders.md#create-a-shared-link). You can find there also other operations that you can do with SharedLinks. 

Java SDK will not sent emails with shared links. 

Users cannot use shared links to upload files. You will have to add them as collaborators to a folder.
You can read about adding collaborators [here](https://github.com/box/box-java-sdk/blob/main/doc/collaborations.md). When you add a collaborator they will receive email with information that they were added as collaborator.

**Comment by antusus** [comment]
Hello @amitbatajoo,
The API to manage FileRequests is available. API allows you to copy existing template to a folder. You will need to create template following instructions [here](https://developer.box.com/guides/file-requests/).

You can read about SDK usage [here](https://github.com/box/box-java-sdk/blob/v3.0.0/doc/file_requests.md).

```
// this is the ID of the request that you have created
var fileRequestRemplate = "request_template_id";
var fileRequest = new BoxFileRequest(api, fileRequestRemplate);

// this is the ID of the folder you want to copy template to
// after copying you will be able to get URL that can be used by others to upload files
// they will not need to have Box account
var folderToShareId = "id_of_the_folder_you_want_to_share";
BoxFileRequest.Info newFileRequestInfo = fileRequest.new Info();
newFileRequestInfo.setDescription("I'm sharing a folder with you");
newFileRequestInfo.setIsDescriptionRequired(true);
newFileRequestInfo.setStatus(BoxFileRequest.Status.ACTIVE);
newFileRequestInfo = fileRequest.copyInfo(newFileRequestInfo, folderToShareId);
// others can use this URL to upload files
var shareUrl = newFileRequestInfo.getUrl().toString();
```
Java SDK will not sent an email with the link. You will have to do that yourself.
