### ISSUE TITLE
Collaboration: Get Accessible By Type not available in Java

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/box-java-sdk#807]
- [X ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.

### Description of the Issue
In Java when you get a folder's collaborations and you iterate over them, there isn't a method to give you the accessible by type e.g. user or group as per the JSON response. 

Sample 

`Collection<BoxCollaboration.Info> collaborations = folder.getCollaborations();
collaborations.forEach(info -> {
BoxCollaborator.Info collaborationInfoAccessibleBy = info.getAccessibleBy();
// There is no method like collaborationInfoAccessibleBy.getType();
}`

JSON Response in CLI, under accessible by the type is listed

```
box collaborations:get 24215463XXX --json
{
    "type": "collaboration",
    "id": "24215463XXX",
    "created_by": null,
    "created_at": "2020-05-18T06:11:03-07:00",
    "modified_at": "2020-05-18T06:11:03-07:00",
    "expires_at": null,
    "status": "accepted",
    "accessible_by": {
        "type": "group",
        "id": "4877585681",
        "name": "Payslip Owners Group",
        "group_type": "managed_group"
    },
    "invite_email": null,
    "role": "editor",
    "acknowledged_at": "2020-05-18T06:11:03-07:00",
    "item": {
        "type": "folder",
        "id": "105527002859",
        "sequence_id": "0",
        "etag": "0",
        "name": "Payslips 1970"
    }
}
```

At the moment the work around is to check
`info.getAccessibleBy().getResource() instanceof BoxUser` which is cumbersome.

### Versions Used
2.46

### Steps to Reproduce
Run code above

### Error Message, Including Stack Trace
Not applicable
[sdk-docs]: **https://opensource.box.com/box-java-sdk/javadoc/com/box/sdk/BoxCollaborator.Info.html**

**Comment by PJSimon** [comment]
Hi @jacquesvandermerwe ,

Thanks for submitting this Issue! We will take a look and get back to you ASAP!

@PJSimon

**Comment by jacquesvandermerwe** [comment]
Thank you for your response

Regards,

Jacques van der Merwe
Mobile: +44 79 839 839 29
