### ISSUE TITLE
Unable to get root folder id and name

### ISSUE THREAD

**Issue by amitbatajoo** [box/box-java-sdk#812]
![outputscreen](https://user-images.githubusercontent.com/6213118/82978411-770d1d80-a01f-11ea-9669-46052d8b4b18.PNG)
- [ X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ X] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
How can we access the root folder using ENTERPRISE as user and creating app.??

        

 BoxDeveloperEditionAPIConnection api = new 
           BoxDeveloperEditionAPIConnection(Enterprise_USER_ID,DeveloperEditionEntityType.ENTERPRISE, boxConfig, accessTokenCache);        
BoxUser.Info userInfo = BoxUser.getCurrentUser(api).getInfo();
System.out.format("Welcome, %s!\n\n", userInfo.getName())       
BoxFolder rootFolder = BoxFolder.getRootFolder(api);
System.out.format("BOX Name:, %s!\n\n", rootFolder.getInfo().getID());
listFolder(rootFolder, 0);
    
Please suggest me the method for souliton
Thank you in advanace.
### Versions Used
Java SDK:2.47
Java: open jdk 1.8
[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by PJSimon** [comment]
Hi @amitbatajoo ,

Thanks for submitting this Issue! We will take a look and get back to you ASAP!

@PJSimon

**Comment by sujaygarlanka** [comment]
@amitbatajoo Is this still an issue?

**Comment by sujaygarlanka** [comment]
@amitbatajoo Documentation on how to get a folder for a user in an enterprise can be found [here](https://github.com/box/box-java-sdk/blob/master/doc/authentication.md#as-user). This should solve your issue. If continue to have problems, feel free to re-open this issue.

**Comment by amitbatajoo** [comment]
@sujaygarlanka Thank you!
