### ISSUE TITLE
Get Response in case file delete is failed [box java api]

### ISSUE THREAD

**Issue by amitbatajoo** [box/box-java-sdk#816]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Any suggestion, how to get the response using java API, in the case of file delete in box system on request gets failed.
I want to handle the file delete failure in the case of some network or internet problem when we try to delete file using box java api.

Thank you in advance.

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by sujaygarlanka** [comment]
@amitbatajoo Wrap the SDK call in a try, catch like below. apiException in the catch below will contain the response and other values. The class definition for BoxAPIException is [here](https://github.com/box/box-java-sdk/blob/69b2d57239ff41abcab895f5e0d30247ec39361b/src/main/java/com/box/sdk/BoxAPIException.java)
```
try {
	// SDK calls here
} catch (BoxAPIException apiException) {
	// apiException will contain the response
}
```
Hope this helps! Feel free to re-open this question if you have any follow-up questions.

**Comment by amitbatajoo** [comment]
@sujaygarlanka  Thank you for help!
