### ISSUE TITLE
Auto renewal of tokens not happening when the system unused for few hours (expired)

### ISSUE THREAD

**Issue by tcharles79** [box/box-java-sdk#82]
Found that the SDK is not renewing the tokens automatically when the system was unused for few hours. API is responding with 401 error, but new SDK is not handling that to renew it.

However old SDK is renewing the token if it identifies the 401 error for the above scenario.

New SDK does renew the token if it is expiring in near feature. But if it was expired, it is not renewing.

**Comment by gcurtis** [comment]
The SDK should be refreshing if the token has expired. What version/commit hash of the SDK are you using? Also, is this happening when restoring the session by constructing a new BoxAPIConnection using saved tokens (for example, after your program quits and is relaunched)?

**Comment by tcharles79** [comment]
Greg - Not sure which commit, but i downloaded the code on Feb 5 2015. Yes it is happening when i initiate a new connection (new BoxAPIConnection) with the token from database.

**Comment by gcurtis** [comment]
I think this might be a bug related to having an expires timestamp of 0. As a workaround, try calling [`setExpires(long)`](http://opensource.box.com/box-java-sdk/javadoc/com/box/sdk/BoxAPIConnection.html#setExpires(long)) after constructing the API connection.

Using the actual expires time from the last session would be ideal, but setting it to any value greater than 0 should fix your issue.

**Comment by gcurtis** [comment]
Hey Charles - there should be a fix for this in place now. Can you let me know if setting the expires timestamp fixed this issue for you? Thanks!

**Comment by tcharles79** [comment]
Hey Greg, I've downloaded the code today and tested this.

When i tested with expired token, the new token pair have been generated. But found that whenever we go for a new BoxAPIConnection, the code is refreshing the tokens even if the token is still valid.

**Comment by gcurtis** [comment]
This is expected if you don't set an expires timestamp. When you create a new API connection with:

```java
BoxAPIConnection api = new BoxAPIConnection(clientID, clientSecret, accessToken,
    refreshToken);
```

the connection has no way of knowing when the access token will expire. To be safe, it will refresh before making the first request in case it has expired. After refreshing, it will remember the new expiration time and only refresh again if your token is about to expire.

If you want to avoid the initial refresh, you can store the expires timestamp along with your tokens, and then set it when you restore the connection:

```java
BoxAPIConnection api = new BoxAPIConnection(clientID, clientSecret, accessToken,
    refreshToken);
api.setExpires(storedExpirationInMilliseconds);
```

**Comment by mikebell90** [comment]
Why can't it just try refreshing on a 401? Why does it even need a clue as to the expiration time (which may be wrong, outdated, etc)

**Comment by gcurtis** [comment]
The problem with refreshing on a 401 is that it can cause unnecessary requests. For example, a user might go to upload a large file, get a 401, refresh, and then have to upload it all over again.

The problem that @tcharles79 is having is that the last refresh time isn't being stored (and there's no way to get/set it) so the connection refreshes right away.

I think that the process of saving/restoring a connection is too complicated and error-prone right now. I've proposed a solution to fix this in #104. I'd appreciate any thoughts or opinions you guys might have on it.

**Comment by mikebell90** [comment]
"The problem with refreshing on a 401 is that it can cause unnecessary requests. For example, a user might go to upload a large file, get a 401, refresh, and then have to upload it all over again."

It clearly wasn't unnecessary if they got a 401, right?

**Comment by gcurtis** [comment]
The goal is to avoid the request where a 401 is returned. Many users have run into issues where they spend minutes uploading a file, only to get a 401 back because the token expired. 

By checking the expiration time we can preemptively refresh the token before making the request and avoid the 401.

**Comment by mikebell90** [comment]
But that can NEVER be guaranteed. It seems to me that is a losing battle.  Besides, that's all fine and good. People will still get a 401 sometimes. Does the current SDK make them catch it (is it explicitly thrown clearly as a speciifc exception?), and manually call refresh method?

**Comment by gcurtis** [comment]
If a 401 is returned by the API, then it will be thrown as a `BoxAPIException` along with the relevant status code and error description.

There shouldn't be a situation where checking the expiration time doesn't work. If the token has expired before the expiration timestamp, then it's a bug with the API's OAuth implementation.

The issue here isn't that checking the expiration timestamp doesn't work - it's that storing and restoring the connection state is difficult/buggy.
