### ISSUE TITLE
BoxSharedLink it not correctly setting the "unshareAt" field

### ISSUE THREAD

**Issue by mmarmol** [box/box-java-sdk#820]
- [yes] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [yes] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [yes] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [yes] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
BoxSharedLink it not correctly setting the "unshareAt" field, is using the Date class toString instead of BoxDateFormat  as it should.

### Steps to Reproduce
1. Try to create set a BoxSharedLink to a file or folder setting the unshareAt field with a Date in the future.
2. Api returns a 400 showing that the unshareAt is incorrect.

### Expected Behavior
It should work but it is impossible at this point to create a sharedlink with an unshareAt date.

### Error Message, Including Stack Trace
FINE: Request
PUT https://api.box.com/2.0/files/683270578442
Accept-Charset: utf-8
X-Box-UA: agent=box-java-sdk/2.48.0; env=Java/14.0.1
User-Agent: Box Java SDK v2.48.0 (Java 14.0.1)
Accept-Encoding: gzip
Content-Type: application/json

{"shared_link":{"access":"open","unshared_at":"Sat Jun 27 14:37:58 ART 2020","password":"test","permissions":{"can_preview":true,"can_download":false}}}
Jun 26, 2020 2:37:59 PM sun.net.www.protocol.http.HttpURLConnection getInputStream0
FINE: sun.net.www.MessageHeader@5513b7e68 pairs: {null: HTTP/1.1 400 Bad Request}{Date: Fri, 26 Jun 2020 17:37:59 GMT}{Content-Type: application/json}{Transfer-Encoding: chunked}{Connection: keep-alive}{Strict-Transport-Security: max-age=31536000}{Cache-Control: no-cache, no-store}{BOX-REQUEST-ID: 0b271817b3226140e8c1cfa335eaf5306}
Jun 26, 2020 2:37:59 PM com.box.sdk.BoxAPIResponse logResponse
FINE: Response
PUT https://api.box.com/2.0/files/683270578442
HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Strict-Transport-Security: max-age=31536000
Cache-Control: no-cache, no-store
Connection: keep-alive
BOX-REQUEST-ID: 0b271817b3226140e8c1cfa335eaf5306
Date: Fri, 26 Jun 2020 17:37:59 GMT
Content-Type: application/json

{"type":"error","status":400,"code":"bad_request","context_info":{"errors":[{"reason":"invalid_parameter","name":"unshared_at","message":"Invalid data type: 'false'"}]},"help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"Bad Request","request_id":"1imhkagg67pfwym0"}

### Versions Used
Java SDK: 2.48.0 but it's also present in older versions.
Java: 14

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by mmarmol** [comment]
I created this pullrequest yesterday.

https://github.com/box/box-java-sdk/pull/819

**Comment by PJSimon** [comment]
Hi @mmarmol ,

Thanks for submitting this Issue! We will take a look and get back to you ASAP!

@PJSimon

**Comment by sujaygarlanka** [comment]
PR #819 merged that fixes this issue.
