### ISSUE TITLE
BoxTrash does not support  pagination

### ISSUE THREAD

**Issue by Deverlain** [box/box-java-sdk#838]
### Description of the Issue
There is now way to make pagination from trash folder by using BoxTrash (as we can do in BoxFolder). 

### Expected Behavior
expand BoxTrash class functional and make it close to BoxFolder

### Versions Used
Java SDK: <2.32.0.
Java: <1.8.0_191>

**Comment by sujaygarlanka** [comment]
@Deverlain `BoxTrash` does support pagination. The docs are [here](https://github.com/box/box-java-sdk/blob/master/doc/trash.md#get-trashed-items) to get all the items in Trash. Please feel free to re-open if you have any follow-up questions regarding this issue.
