### ISSUE TITLE
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by slavag** [box/box-java-sdk#842]
- [X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Well, I have really strange issue.
We're running on java 8 update 161. In general there's no issue with all our customers with Box (many), except one customer 
that when our production servers (random) are trying to download file we're getting error : "unable to find valid certification path to requested target". Now, the production server is multithreaded process that in addition to Bax runs other HTTPS connections, to Google, Microsoft and other. While in the same time when we're getting this error on Box, all other connections are working just fine. So on this customer (only 3 accounts of it) we're constantly see this error. 

I digged a bit in the sniffed network data and I see TLS 1.2 initiation with box server 
nlb-box-c7-0-2caff61596e8a29b.elb.eu-west-2.amazonaws.com wich reposne with 3 certificates

1. id-at-commonName=zones-traffic-manager00045.eu-west-2.aws.prod issued by id-at-commonName=Production Web Services Authority.
2. id-at-commonName=Production Web Services Authority issued by id-at-commonName=Production Intermediate Authority 

3. id-at-commonName=Production Intermediate Authority issued by id-at-commonName=Production Root Authority.

So it seems that BOX have traffic manager servers without properly signed certificates.
In the case SDK goes to **nlb-box-c7-0-2caff61596e8a29b.elb.eu-west-2.amazonaws.com** (**18.130.91.90**) it's working file and certificate is valid : **id-at-commonName=*.boxcloud.com** which is signed by i**d-at-commonName=GeoTrust RSA CA 2018**

 but in some cases it goes to **nlb-box-c7-0-2caff61596e8a29b.elb.eu-west-2.amazonaws.com** (**18.130.91.91**) we got certificate : **id-at-commonName=zones-traffic-manager00045.eu-west-2.aws.prod.**  which is signed by **id-at-commonName=Production Web Services Authority**
That's not valid.

Any help is highly appreciated. 
Thanks !!! 

### Error Message, Including Stack Trace
"PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"
Stack, I have only from the production server via dump so it's a screenshot of VisualVM:
![image](https://user-images.githubusercontent.com/511540/94128700-212c7300-fe63-11ea-8d36-dae8f2c4943c.png)

### Versions Used
Java SDK: 2.32.0
Java: 8 Update 161
[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by slavag** [comment]
Update : 
Seems that during file downloading we got redirected to zones-traffic-manager00025.eu-west-2.aws.prod.box.net.
While accessing this in the browser, the host name seems not much CN in the certificate, which is wildcard for *.box.com. But anyway browser says it's an invalid name. In the exception in Java of SunCertPathBuilderException we see in the AdjacencyList next chain of certificate verification which is somehow broken :
1) cn in certificate : **zones-traffic-manager00025.eu-west-2.aws.prod.box.net** Issued by : **cn=production web services authority**
2) **cn=production web services authority** issued by **cn=production intermediate authority**
3) **cn=production intermediate authority** issued by **cn=production root authority**

And cn=production root authority is not verified.

Please advise

**Comment by slavag** [comment]
**Update 2**: 
I digged a bit in the sniffed network data and I see TLS 1.2 initiation with box server 
nlb-box-c7-0-2caff61596e8a29b.elb.eu-west-2.amazonaws.com wich reposne with 3 certificates

1. id-at-commonName=zones-traffic-manager00045.eu-west-2.aws.prod issued by id-at-commonName=Production Web Services Authority.
2. id-at-commonName=Production Web Services Authority issued by id-at-commonName=Production Intermediate Authority 

3. id-at-commonName=Production Intermediate Authority issued by id-at-commonName=Production Root Authority.

So it seems that BOX have traffic manager servers without properly signed certificates.
In the case SDK goes to **nlb-box-c7-0-2caff61596e8a29b.elb.eu-west-2.amazonaws.com** (**18.130.91.90**) it's working file and certificate is valid : **id-at-commonName=*.boxcloud.com** which is signed by i**d-at-commonName=GeoTrust RSA CA 2018**

 but in some cases it goes to **nlb-box-c7-0-2caff61596e8a29b.elb.eu-west-2.amazonaws.com** (**18.130.91.91**) we got certificate : **id-at-commonName=zones-traffic-manager00045.eu-west-2.aws.prod.**  which is signed by **id-at-commonName=Production Web Services Authority**
That's not valid.

Thanks

**Comment by sujaygarlanka** [comment]
@slavag Thank you for the question. We will get back to you ASAP.

**Comment by slavag** [comment]
@sujaygarlanka Hi, is there any update ? Thanks

**Comment by sujaygarlanka** [comment]
@slavag Is this still occurring?

**Comment by slavag** [comment]
@sujaygarlanka Yes, we got an reply from box support that issue is related to https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8181791.

**Comment by tnfan** [comment]
Hi @slavag , @sujaygarlanka is using java 8u161 which is higher than 8u141-resolved issue
I am using 8u292 also facing this issue

@sujaygarlanka do it work for you now? Can you update any thing?

**Comment by antusus** [comment]
Hello @slavag, @thainguyenfan ,
I'm afraid that SDK team will not be able to help with that. If there is a problem with certificate and routing customers to server with invalid certificate we can't help even with retrying failed requests.
I suggest you folks open [support ticket](https://support.box.com/hc/en-us/requests/new) and work directly with the teams responsible for networking.
