### ISSUE TITLE
Box Java SDK , events log is empty !!!

### ISSUE THREAD

**Issue by slavag** [box/box-java-sdk#849]
- [X] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [X] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [X] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [X] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Suddenly, all enterprise events are empty when code is trying to get them (filtered by dates), if we don't filter, last event is on October 16 2020, while new files were uploaded since then.
All was working, until few days we noticed that enterprise events log is empty, and we know fo 100% that there's a new data.
We set "As-User" if this is done on behalf of another user (by admin)

### Expected Behavior
Enterprise events log should not be empty if there's a new data. 

### Error Message, Including Stack Trace
No error, no exception no stack trace.

### Versions Used
Java SDK: 2.32
Java: 8 update 60

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

Please advise, this is urgent as hurts production system.
Thanks

**Comment by sujaygarlanka** [comment]
@slavag If you did not make any upgrades or changes to the SDK, then it must be an API issue. I recommend filing a support ticket https://support.box.com/hc/en-us/requests/new.

**Comment by slavag** [comment]
Thanks, we didn't change anything, seems that there's an issue with BOX API

**Comment by sujaygarlanka** [comment]
@slavag I am going to close this for now since it is an API issue and there is nothing on the SDK end we can do for now. However, if anything changes the SDKs are involved or you have any follow-up questions regarding this issue, feel free to re-open this.
