### ISSUE TITLE
Update of Tracking Codes is throwing Exception 400

### ISSUE THREAD

**Issue by rjainrohit** [box/box-java-sdk#853]
_Originally posted by @sujaygarlanka in https://github.com/box/box-java-sdk/issues/752#issuecomment-631563587_

@sujaygarlanka @PJSimon I started implementing this today on top of box java sdk 2.50.0 and its failing. The tracking codes request JSON in the JAVA SDK does not match the JSON as per the API documentation is not correct. Currently its sending below in the request:
{"tracking_codes":{"USDA eAuth ID":"999999999999","Workspace ID":"12345"}}

where as it should be like this

{
"tracking_codes": [
{
"type": "tracking_code",
"name": "USDA eAuth ID",
"value": "ABCDDE"
}
]
}

See the error below:

com.box.sdk.BoxAPIResponseException: The API returned an error code [400 | dpatz9gk7vrrmc7p.0c67d859273023ba0e8d41be7d01dd037] invalid_request_parameters - Invalid input parameters in request at com.box.sdk.BoxAPIResponse.(BoxAPIResponse.java:92) at com.box.sdk.BoxJSONResponse.(BoxJSONResponse.java:32) at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:680) at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:382) at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:349) at com.box.sdk.BoxUser.updateInfo(BoxUser.java:537)

**Comment by sujaygarlanka** [comment]
@rjainrohit Thanks for reporting the error. We are taking a look at this issue and will get back to you ASAP.

**Comment by sujaygarlanka** [comment]
@rjainrohit We have a fix for this issue and are going to try and merge and release it before Thanksgiving.
