### ISSUE TITLE
 JWT authentication to access the Box API, 401 returned.

### ISSUE THREAD

**Issue by himeyon** [box/box-java-sdk#854]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue

I used JWT authentication to access the Box API, but the
401 will be returned.

> com.box.sdk.BoxAPIResponseException: The API returned an error code [401 | .0f59ac9ffb7dbcd614c3b6a071320e0c1]
> 	at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:92) ~[box-java-sdk-2.51.0.jar:na]
> 	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:678) ~[box-java-sdk-2.51.0.jar:na]
> 	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:382) ~[box-java-sdk-2.51.0.jar:na]
> 	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:349) ~[box-java-sdk-2.51.0.jar:na]
> 	at com.box.sdk.JSONIterator.loadNextPage(JSONIterator.java:75) ~[box-java-sdk-2.51.0.jar:na]
> 	at com.box.sdk.JSONIterator.loadNextJsonObject(JSONIterator.java:97) ~[box-java-sdk-2.51.0.jar:na]
> 	at com.box.sdk.JSONIterator.hasNext(JSONIterator.java:32) ~[box-java-sdk-2.51.0.jar:na]
> 	at com.box.sdk.BoxItemIterator.hasNext(BoxItemIterator.java:28) ~[box-java-sdk-2.51.0.jar:na]

The license you are currently using is Individual plan.
Is this relevant?
I looked for the documentation, but I couldn't find it.

We plan to purchase a paid license in the future.

The implementation is as follows.

```
var reader = new FileReader("/path/config.json");
var config = BoxConfig.readFrom(reader);
var api      = new BoxAPIConnection(config);

var rootFolder = BoxFolder.getRootFolder(api);
var rootInfo = new BoxFolder(api, rootFolder.getID());

for (BoxItem.Info itemInfo : rootInfo) { // This is where it happens.
```

**Comment by cbetta** [comment]
Hi @himeyon have you gone through the process to get the JWT app approved? A JWT app needs admin approval before it will work.

https://developer.box.com/guides/applications/custom-apps/app-approval/

**Comment by himeyon** [comment]
@cbetta 
Thanks for the quick comment.
Yes, it has already been approved.

![image](https://user-images.githubusercontent.com/4468822/98095403-dffd9900-1ecd-11eb-883d-202ad4796ce0.png)

**Comment by sujaygarlanka** [comment]
@himeyon I would look at the docs [here](https://github.com/box/box-java-sdk/blob/master/doc/authentication.md#server-authentication-with-jwt) for JWT. You should use this `BoxDeveloperEditionAPIConnection api = BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(boxConfig);` to get your API connection. Also, you don't need `rootInfo`. You can use `rootFolder` directly like so 
```
var rootFolder = BoxFolder.getRootFolder(api);
var rootFolder = BoxFolder.getRootFolder(api);
for (BoxItem.Info itemInfo : rootInfo) { // This is where it happens.
```
I hope this helps!

**Comment by himeyon** [comment]
@sujaygarlanka 

Thanks.
Thanks for telling me about the problems with the code, too.

I tried this implementation as well, but it threw an UnknownHostException after the following warning was output.
I've also implemented the proxy settings, but I couldn't find the cause of the problem.

> 2020-11-06 11:53:48.820  WARN 22408 --- [  restartedMain] com.box.sdk.BoxAPIRequest                : Retrying authentication request due to transient error status=0 body=null
> 2020-11-06 11:53:48.821  WARN 22408 --- [  restartedMain] com.box.sdk.BackoffCounter               : Backing off for 1 seconds before retrying 5 more times.

> Caused by: java.net.UnknownHostException: api.box.com

I implemented the following and it works.

```
IAccessTokenCache accessTokenCache = new InMemoryLRUAccessTokenCache(100);
BoxDeveloperEditionAPIConnection api = new BoxDeveloperEditionAPIConnection("12345678", DeveloperEditionEntityType.USER, config, accessTokenCache);
```

**Comment by sujaygarlanka** [comment]
@himeyon Glad it works now. Having a proxy can cause some issues. If you have any follow-up questions, feel free to re-open this issue.
