### ISSUE TITLE
Embed url from box is not rendering word docx with the right format

### ISSUE THREAD

**Issue by martinmendez1994** [box/box-java-sdk#864]
### Description of the Issue
Hi.
Maybe this is not the right place to report this. We are having a issue with word documents that are not respecting the alignment in numbered lists

### Steps to Reproduce
1 - Upload Word doc with numbered list
2 - Request Box for embed url
3 - Navigate to url

### Expected Behavior
**Doc should look like this:**
![image](https://user-images.githubusercontent.com/32559563/105508964-c3425780-5cab-11eb-8550-57c9f082296a.png)

**Actually looks like this in Box**
![image](https://user-images.githubusercontent.com/32559563/105509124-f684e680-5cab-11eb-9ace-30902011f7d0.png)

**Comment by sujaygarlanka** [comment]
Hello @martinmendez1994, Sorry for the delayed response. The best place to report and get help for this is here https://support.box.com/hc/en-us. Thanks!
