### ISSUE TITLE
Missing File Permission Enums

### ISSUE THREAD

**Issue by rjainrohit** [box/box-java-sdk#865]
### Is your feature request related to a problem? Please describe.
I am unable to access can_invite_collaborator permission on a file as there is no Enum defined. 

### Describe the solution you'd like
Add the new permissions in the Permission Enumset in BoxFile.java. The API today returns the following permissions on a file. If all missing ones can be added that will be great.

"permissions": {
        "can_download": true,
        "can_preview": true,
        "can_upload": true,
        "can_comment": false,
        "can_rename": true,
        "can_delete": true,
        "can_share": true,
        "can_set_share_access": true,
        "can_invite_collaborator": false,
        "can_annotate": false,
        "can_view_annotations_all": true,
        "can_view_annotations_self": true
    },

### Describe alternatives you've considered
REST API

**Comment by sujaygarlanka** [comment]
@rjainrohit Thank you for the feedback. We will add this to our backlog. If you are interested have this added soon, feel free to submit a PR and we can get it reviewed and merged.
