### ISSUE TITLE
Long polling missing events

### ISSUE THREAD

**Issue by Roshni661** [box/box-java-sdk#867]
- [ Yes ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ Yes ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ Yes ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ Yes ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
I am using Box long polling functionality to poll for real-time events from Box. When I tried deleting or uploading a folder with many subfolders and files, some events are arriving too late or even getting missed. Is there anything that can be done here to make sure that I am not missing any events from Box and I can getting those event immediately? Please let me know. I am using Java SDK and below is my code

```
          public void onEvent(final BoxEvent event) {
                // Handle the event.
                }
            }

            @Override
            public void onNextPosition(final long nextPosition) {
               // Keeping track of next position
            }

            @Override
            public boolean onException(final Throwable throwable) {

            }

```

**Comment by swfree** [comment]
Hi @Roshni661, thanks for filing this issue. There are some caveats to the events API -- for example, events can come in out of order (you can refer to the documentation here: https://developer.box.com/guides/events/for-user/#limitations). Typically how long is the delay you're experiencing?

**Comment by Roshni661** [comment]
Thanks for the documentation. The delay I am experiencing is around 15-20 minutes. Suppose I delete a folder with 7 files, I get a trash event for the folder and 6 files. For one of the files the event is coming after 15-20 minutes.

**Comment by sujaygarlanka** [comment]
Hello @Roshni661, This is an enhancement or bug on the API side and not much we can do on the SDK side. If you would like to file a ticket or get help, I recommend going to our support site [here](https://support.box.com/hc/en-us). Hope this helps! Feel free to re-open this issue if you have any follow-up questions.
