### ISSUE TITLE
Need ability to update Legal Hold Policy

### ISSUE THREAD

**Issue by rjainrohit** [box/box-java-sdk#868]
### Is your feature request related to a problem? Please describe.
We have a need to update all our legal hold policy names and since they are in 1000's we would like to do this via the API. 
We want to update policy name and policy description and release notes.

### Describe the solution you'd like
-Add setters as follows to BoxLegalHoldPolicy.Info class
setPolicyName(String)
setDescription(String)
setReleaseNotes(String)

- Change the return type of getResource method of the info class from BoxResource to BoxLegalHoldPolicy

### Describe alternatives you've considered
NA

### Additional context
We already have code changes ready to go and willing submit a PR.

**Comment by swfree** [comment]
Hi @rjainrohit, thanks for filing this issue. Have you tried following the example in the documentation for updating a legal hold policy? https://github.com/box/box-java-sdk/blob/master/doc/legal_holds.md#update-existing-legal-hold-policy. You should be able to use it for updating all three of those fields - policy name, description, and release notes. For example:

```
BoxLegalHoldPolicy policy = new BoxLegalHoldPolicy(api, id);
BoxLegalHoldPolicy.Info policyInfo = policy.new Info();
info.addPendingChange("description", "new description");
info.addPendingChange("policy_name", "new policy name");
info.addPendingChange("release_notes", "new release notes");
policy.updateInfo(info);
```

**Comment by rjainrohit** [comment]
Thank You didn't realized that, will go that route.

**Comment by rjainrohit** [comment]
@swfree Re-Opening this issue because addPendingChange method has no modifiers which makes it not visible to packages other than com.box.sdk. Please provide a solution to this problem.

**Comment by sujaygarlanka** [comment]
@rjainrohit Sorry, I don't understand the issue. The method should be publicly exposed. You can see how to use it as we have in one of our tests here https://github.com/box/box-java-sdk/blob/main/src/test/java/com/box/sdk/BoxLegalHoldPolicyTest.java#L216.

**Comment by rjainrohit** [comment]
@sujaygarlanka the method addPendingChange in BoxJSONObject class has no modifier which makes it package-private. Only visible to classes in package com.box.sdk, in the example that you shared the test class belongs to the same package as the rest of the core classes and thus they compile fine. Usually as a best practice its always good to keep test classes in a different package than the classes that one is testing. 

For information on how JAVA access control works please refer to https://docs.oracle.com/javase/tutorial/java/javaOO/accesscontrol.html. Here is a statement from the page that clears the ask further: " ..... A class may be declared with the modifier public, in which case that class is visible to all classes everywhere. If a class has no modifier (the default, also known as package-private), it is visible only within its own package...".

**Comment by rjainrohit** [comment]
@sujaygarlanka is there any update?

**Comment by swfree** [comment]
Hi @rjainrohit, thank you for calling this out! I've filed a ticket for us to address this and add the setters like you mentioned in your first comment. You also originally mentioned that you have code changes ready to go, so if you would like to you're welcome to submit a PR and we'll take a look ASAP. Thanks!
