### ISSUE TITLE
API to get information of account which is collaborating folders

### ISSUE THREAD

**Issue by Roshni661** [box/box-java-sdk#877]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
There is an account A which is collaborating folder 1 with my account
There is an account B which is collaborating folder 2 with my account
I am able to see folder 1 and folder 2 in my account. Is there a way to differentiate which account the folder is being collaborated from using any of the API's? 

In this case, account A and account B. These 2 accounts may _not_ be owners of the folder in their account but they are the ones who added my account as a collaborator. So I want to know if the folders in my account is collaborated by account A or account B.

**Comment by sujaygarlanka** [comment]
@Roshni661 One option is to get the collaborations on a folder using this [endpoint](https://developer.box.com/reference/get-folders-id-collaborations/). This can be done in the Java SDK by using this [method](https://github.com/box/box-java-sdk/blob/master/doc/collaborations.md#get-the-collaborations-on-a-folder). Once you do that, you get back a `BoxCollaboration` object that has who created it. Hope this help!

**Comment by antusus** [comment]
Hello @Roshni661,
I do not think there is a way to know which account is sharing a folder with you at least API is not providing us with this information. You can get email of the collaborator. Maybe this could give you some indication what account is that:
```
var api = new BoxAPIConnection(accessToken);
var sharedFolder = new BoxFolder(api, "146717789360");
sharedFolder.getCollaborations().stream()
        .map(BoxCollaboration.Info::getCreatedBy)
        .map(BoxUser.Info::getJson)
        .forEach(System.out::println);
```
Response will be like this: `{"type":"user","id":"some_id","name":"Name or email","login":"email"}`
If you need to get Account information I'm suggesting raising this idea with Support: https://support.box.com/hc/en-us/requests/new maybe they can add this to their roadmap.
