### ISSUE TITLE
BoxItem class does not have getExtension() method

### ISSUE THREAD

**Issue by roshni06** [box/box-java-sdk#880]
I have a use-case where i need to get the extension of boxItems but the method is not implemented here - https://github.com/box/box-java-sdk/blob/master/src/main/java/com/box/sdk/BoxItem.java

I would really appreciate if that method can be implemented

**Comment by sujaygarlanka** [comment]
@roshni06 Cast the item to the appropriate object, then you get its extension. Getting items and casting them is shown in the docs [here](https://github.com/box/box-java-sdk/blob/master/doc/folders.md#get-a-folders-items). Hope this helps!

**Comment by sujaygarlanka** [comment]
@roshni06 We do not plan to add a `getExtension()` method to `BoxItem` because it can be a file, folder or weblink and only files and folders have extensions. We believe `BoxItem` should only have methods that are relevant to all items. Hope this helps! Thank you for the feedback.
