### ISSUE TITLE
Want to set "is_external_collab_restricted" when creating enterprise user

### ISSUE THREAD

**Issue by atsunori-sakai** [box/box-java-sdk#883]
### Is your feature request related to a problem? Please describe.
Want to set the PropertyName "is_external_collab_restricted" when creating enterprise user.

### Describe the solution you'd like
Looks like it would just need the below added to "createEnterpriseUser()" method of BoxUser.java.

requestJSON.add("is_external_collab_restricted", params.getIsExternalCollbRestricted());

### Describe alternatives you've considered
N/A

### Additional context
N/A

**Comment by PJSimon** [comment]
Hi @atsunori-sakai ,

Thanks for submitting this Issue! It appears to be missing from other Box SDKs, as well.  I created a ticket for it (SDK-1645) and we'll start working on it in an up-coming sprint.  We'll start with the Java SDK, first!

@PJSimon
