### ISSUE TITLE
I received an inquiry from Box regarding JWT authentication, but I don't think it will affect us as long as we use the SDK.

### ISSUE THREAD

**Issue by himeyon** [box/box-java-sdk#892]
I received an inquiry from Box about JWT certification.

I understand that the length of the token returned upon authentication will be changed, but as long as we are using the SDK, there will be no effect of the change in token length, is that correct understanding?

When using the SDK, I believe that the token dispensed during authentication will be retained by the SDK instance and used during API access.
I understand that the implementation is not dependent on the number of digits.

### Email from Box(Masking the token part.)

-----
Dear Box Admin,

Per our records, you are using the Box Server-server JWT Token Authentication method. This method involves an access token. 

This notification only applies to Server-server JWT tokens. If you are using Client-side OAuth 2.0, Server-side App tokens or Developer tokens, there is no impact to you. You can find an overview of these 4 different authentication methods here.

The documentation for the token says that we will return a token as a string. This continues to hold true. However, Box is changing the format of this token. Today, the token might look like this: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

We are changing the format so that the token might look like the string below. The new token format is longer and has special characters.

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

Please note that this is not a new format. This is the same format we use for 

downscoping tokens. This new format will help Box scale this authorization service and as a result your API calls will be faster.

We will start deploying this change on August 4, 2021. In the meantime, we encourage you to validate that your applications can handle the new token format. The new tokens are in the same format as those used for downscoping Box tokens. You can create a new access token and then downscope it. If you are able to store the downscoped tokens successfully, you will also be able to store the new JWT token format and this means no changes are required from your end.

If you need any assistance in this, please reach out to jwt-set-rollout@box.com and we will be happy to help.

-----

### Versions Used
Java SDK: 2.52.0
Java: Amazon Corretto 11

**Comment by sujaygarlanka** [comment]
@himeyon If you only interact with the token through the SDK, then there will be no impact to you. The SDK handles this new token. Hope this helps!
