### ISSUE TITLE
java.lang.StackOverflowError in BoxTermsOfServiceUserStatus info method

### ISSUE THREAD

**Issue by samrajcse** [box/box-java-sdk#893]
Following method throws java.lang.StackOverflowError error.

Classname: BoxTermsOfServiceUserStatus
public static List<BoxTermsOfServiceUserStatus.Info> getInfo(final BoxAPIConnection api, String termsOfServiceID) {
        return getInfo(api, termsOfServiceID);
    }

I want to get all the users Custom terms of service accepted status.

**Comment by sujaygarlanka** [comment]
@samrajcse Could you share your code so we can understand why the issue may be occurring? Thanks!

**Comment by samrajcse** [comment]
Hi @sujaygarlanka ,

Ignore the code we use, please check the above block, in that return statement, it is calling the same method. So it lead to infinite loop.

**Comment by carycheng** [comment]
This is might fault, apologies @samrajcse, @sujaygarlanka - Looks like the intended purpose was to have the getInfo overloaded. 

```getInfo(final BoxAPIConnection api, String termsOfServiceID)``` would call into `getInfo(final BoxAPIConnection api,
                                     String termsOfServiceID, String userID)`
                                     
However, I should have called the correct method like so: ```getInfo(api, termsOfServiceID, null)```,

In the meantime @samrajcse to unblock you, you can call getInfo with the overloaded method for userID and pass in null like mentioned above as the logic [already checks](https://github.com/box/box-java-sdk/blame/5e3a96c903fffa198c97e981ce75765a69bd6cb6/src/main/java/com/box/sdk/BoxTermsOfServiceUserStatus.java#L103) to make sure if userID is null then don't attach that to the request.

Something like ```getInfo(api, termsOfServiceID, null)``` should do the trick. Again, apologies for any inconvenience

**Comment by samrajcse** [comment]
Hi All,

Please find the code. It is not fetching all the users who are associated
with the TOS enabled and their status.

*Code:*

JWTEncryptionPreferences encryptionPref = new JWTEncryptionPreferences();
encryptionPref.setPublicKeyID(PUBLIC_KEY_ID);
encryptionPref.setPrivateKey(privateKey);
encryptionPref.setPrivateKeyPassword(PRIVATE_KEY_PASSWORD);
encryptionPref.setEncryptionAlgorithm(EncryptionAlgorithm.RSA_SHA_256);

IAccessTokenCache accessTokenCache = new
InMemoryLRUAccessTokenCache(MAX_CACHE_ENTRIES);
BoxDeveloperEditionAPIConnection api =
BoxDeveloperEditionAPIConnection.getAppUserConnection(USER_ID, CLIENT_ID,
CLIENT_SECRET, encryptionPref, accessTokenCache);

List<BoxTermsOfService.Info> termsOfServices =
BoxTermsOfService.getAllTermsOfServices(api);

for (BoxTermsOfService.Info termsOfServiceInfo : termsOfServices) {
String tosId = termsOfServiceInfo.getID();
System.out.println("Tos id:" + tosId + " status:" +
termsOfServiceInfo.getStatus() + " task type:" +
termsOfServiceInfo.getTosType());

List<BoxTermsOfServiceUserStatus.Info> termsOfServicesUserstatusList =
BoxTermsOfServiceUserStatus.getInfo(api, tosId, null);

for (BoxTermsOfServiceUserStatus.Info termsOfServicesUserstatus :
termsOfServicesUserstatusList) {
System.out.println("Tosuser status id:" + termsOfServicesUserstatus.getID()
+ " Is accepted:" + termsOfServicesUserstatus.getIsAccepted());

}
}
Regards,
*SAMRAJ.K*
