### ISSUE TITLE
when public BoxAPIConnection(String clientID, String clientSecret) is used?

### ISSUE THREAD

**Issue by shikida** [box/box-java-sdk#900]
Authentication method is oauth2 with client credentials grant (server authentication)
I have client credentials
App access level is app access only

App works fine using developer token

I've noticed there's a constructor public BoxAPIConnection(String clientID, String clientSecret)

But when I try to use it, I get "The API returned an error code [401"

I could not find an example using that.

The examples I've found rely on a config file (json) but there's no option in my app to download such a file.

Is there any simple example on how to use client credentials grant using this API constructor?

**Comment by mwwoda** [comment]
Hi @shikida 

We are currently not supporting server authentication with client credentials grant in the Java SDK. We have it in our backlog (SDK-1567). In the meantime, you can use other authentication methods mentioned [here](https://github.com/box/box-java-sdk/blob/main/doc/authentication.md) or implement it yourself basing on [this doc](https://developer.box.com/guides/authentication/jwt/without-sdk/).

Thanks,
@mwwoda
