### ISSUE TITLE
BoxUser.Info.getRole() isn't working

### ISSUE THREAD

**Issue by adam801** [box/box-java-sdk#901]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
Whenever I try to get the role of a user, it gives an error without any sort of description. I contacted the Box team and they cannot find anything in their side and suggested it's a problem with the SDK.

### Steps to Reproduce
Get a Box user: BoxUser user  = new BoxUser(api, ID);
Get the info: BoxUser.Info userInfo = user.getInfo();
Get the role: BoxUser.Role role = userInfo.getRole();

### Expected Behavior
I expected the function to return the role of the user ("user", "admin", "coadmin").

### Error Message, Including Stack Trace
Exception in thread "main" java.lang.NullPointerException
	at boxusers.deleteBoxUsers.lookupUsers(deleteBoxUsers.java:172)
	at boxusers.deleteBoxUsers.main(deleteBoxUsers.java:302)

### Screenshots
![image](https://user-images.githubusercontent.com/52717894/124042086-61f28300-d9c5-11eb-9fdc-2028b414b9ad.png)

### Versions Used
Java SDK: box-java-sdk-2.48.0.jar
Java: jre1.8.0_291

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by mwwoda** [comment]
Hi @adam801 

The role is not returned by default from the API that's why it's NULL everytime in your case. You need to specify role in **fields** parameter in **getInfo** method alongside any other field you want to be returned from the API. Full code should look like this
```
BoxUser user = new BoxUser(api, userID);
BoxUser.Info userInfo = user.getInfo("role");
BoxUser.Role role = userInfo.getRole();
String userRole = userInfo.getRole().name();
```
Hope that helps!

Thanks,
@mwwoda

**Comment by adam801** [comment]
Thank you Mateusz. And thanks for editing the code. Previously there was an additional line that wasn't needed.

You can close this ticket.
