### ISSUE TITLE
BoxAPIConnection from Box SDK cause most threads in STUCK mode

### ISSUE THREAD

**Issue by shuangli** [box/box-java-sdk#911]
- [ x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
we are using Box SDK for our Box integration for a while, our business noticed sometime they could not do any activity and it impact our business. After some research, we found all threads are stuck and it is caused by Box SDK api.
We filed the support ticket and here is the case number: 2460061

If you look at the thread dump we sent below, it happens when we try to interact with Box following actions:
Upload
Generate download url
Generate preview url
 
And it happens when Box Java SDK tries to refresh access token, and thread was locked, but never released. It happens very often. Thread count stuck and increases from 8:00AM.
The pod has filled up with stuck thread until we killed, or out of memory and won’t receive anymore request.
 
It’s one of the example. We have killed many stuck pods past months with the thread lock. 
 
Here are what we found out after researching on Box SDK code:
After we looked at code, I think this could be potential problem:
https://github.com/box/box-java-sdk/blob/v2.16.1/src/main/java/com/box/sdk/BoxAPIConnection.java#L545-L553
 
Line 545 & line 551 could throw Throwable, if an exception is thrown, then refreshLock is remains locked. All threads trying to access Box become blocked on that lock.
​
This portion of code should inside a try - finally statement and unlock should be inside of finally . so it would be unlocked.

Line 540 could also cause this problem as well. you would need to swap Line 540 and Line 541.
 
I looked at same class code from 2.55.1 and it would have same problem.
 
Please let us know if there could give you any clue of issue.
 
### Steps to Reproduce
It is random and hard to reproduce it. Once it happen it would cause the server doesn't response as all threads are stuck

### Expected Behavior
it should not stuck any thread for this case.

### Error Message, Including Stack Trace
The thread dump is attached

### Screenshots
Please check the attachment
[threaddump-xr52v-prod-202108230813.txt](https://github.com/box/box-java-sdk/files/7040885/threaddump-xr52v-prod-202108230813.txt)
<img width="847" alt="image001_thread" src="https://user-images.githubusercontent.com/940782/130660526-abe783f0-3746-42d8-aa1b-5871f25f1d16.png">

### Versions Used
Java SDK: 2.16.1 & 2.55.1
Java: JDK 8

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by shuangli** [comment]
Would you please let me know when you are going to create a new version of Box SDK. Our team is waiting for it and we are going to build our service based on this new version and test it out & push it to prod if everything works as expected.

**Comment by mhagmajer** [comment]
@shuangli did you have a chance to test the fix we released last https://github.com/box/box-java-sdk/releases/tag/v2.56.0

**Comment by shuangli** [comment]
@mhagmajer yes. we did. so far so good. haven't seen any issue yet. we also enhanced our code to have a separate BoxAPIConnection instance for different thread. so it would not stuck other thread when this happen

**Comment by PJSimon** [comment]
Hi @shuangli ,
It sounds like your issues have been resolved, so I'm closing this issue.  Please feel free to re-open if you are still having a problem.
Thanks!
PJSimon
