### ISSUE TITLE
JWT 404  Not Found ??

### ISSUE THREAD

**Issue by zhaojiaoyang-itec** [box/box-java-sdk#915]
```
Reader reader = new FileReader("D:\\config.json"); 
BoxConfig config = BoxConfig.readFrom(reader); 
BoxDeveloperEditionAPIConnection api= BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(config); 
BoxFile file = new BoxFile(api, "854685679395");``
```

The API returned an error code [404 | z3s63bgu2g25ans1.0e4830fa3a27620edff9b15bd31497ef7] not_found - Not Found

**Comment by PJSimon** [comment]
Thanks for submitting this Issue.  Unfortunately, it is missing the required checkbox fields that were provided in the template when you initially created the Issue:

- [ ] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

Please perform each step above to research your Issue before submitting it to our team.  If you are still unable to resolve it, please re-create this Issue and check off those boxes when you submit it!  Thanks for helping to streamline our process!

[sdk-docs]: ../tree/master/docs
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-windows-sdk-v2/search?type=Issues

**Comment by PJSimon** [comment]
You may want to review https://developer.box.com/guides/api-calls/permissions-and-errors/common-errors/#404-not-found
