### ISSUE TITLE
Need the ability to find if folder is empty or not.

### ISSUE THREAD

**Issue by rjainrohit** [box/box-java-sdk#917]
### Is your feature request related to a problem? Please describe.
Need a way to find if the folder is empty or not. The nearest field that can provide me that information is item_collection and reduce the number of API calls. The most ideal way to do this would have been if the REST API https://{{api.box.com}}/2.0/folders/:folder_id/items?fields=name,owned_by,item_collection would have returned the item_collection but unfortunately it does not. So the next best way to do this to individually do getInfo on each sub folder under a folder, but the BoxFolder class is missing the getter for item_collection.  

### Describe the solution you'd like
Enhance the REST API https://{{api.box.com}}/2.0/folders/:folder_id/items?fields=name,owned_by,item_collection to return item_collection or 
BoxFolder.Info.parseJSONMember add the ability to parse item_collection and provide the getter for item_collection.

### Describe alternatives you've considered
Iterate through each sub folder to get its items.

**Comment by antusus** [comment]
Hello @rjainrohit,
if you want to get this information without additional API call then I would suggest reaching out to support with https://developer.box.com/support/
I think the [Developer forum](https://support.box.com/hc/en-us/community/topics/360001932973-Platform-and-Developer-Forum) is the best way to ask about changes in the API as then you can engage in discussion with API developers directly.
