### ISSUE TITLE
DOCUMENTATION: SharedLink Example uses Deprecated Method

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/box-java-sdk#929]
### Is your feature request related to a problem? Please describe.
The current docs shows the deprecated method for setting a Sharedlink. https://github.com/box/box-java-sdk/blob/main/doc/folders.md#create-a-shared-link

The new method is using the BoxSharedLinkRequest.

### Describe the solution you'd like
Updated documentation examples for setting shared link for files and folder. 

### Describe alternatives you've considered
N/A

**Comment by arjankowski** [comment]
Hi @jacquesvandermerwe,

Thank you for pointing it out! We will update the documentation examples ASAP!

@arjankowski
