### ISSUE TITLE
Deprecated enums still being used

### ISSUE THREAD

**Issue by mittal-umang** [box/box-java-sdk#931]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
The current version of BoxSDK has deprecated Type in BoxEvent.java but it is atleast being used in EventLog.java.

### Versions Used
Java SDK: 2.57.0
Java: 11

**Comment by antusus** [comment]
Fixed with the release of [2.58.0](https://github.com/box/box-java-sdk/releases/tag/v2.58.0)
