### ISSUE TITLE
Provide options to get all users in an enterprise

### ISSUE THREAD

**Issue by tcharles79** [box/box-java-sdk#94]
In the old SDK, we can get all enterprise users using below code
         
       BoxDefaultRequestObject b1 = new BoxDefaultRequestObject();
	 b1.getRequestExtras().addQueryParam("limit", limit);
	 b1.getRequestExtras().addQueryParam("offset", offset);
        client.getUsersManager().getAllEnterpriseUser(b1, null);

But i don't see the replacement in new SDK for the above use case. 

Please provide. Thanks.

**Comment by sohtsuka** [comment]
Hi @gcurtis,

Do you have any plans to implement this? My app needs this so I think I can do it. Interfaces added to the BoxUser class would be:

```
public static Iterable<BoxUser.Info> getAllUsersInEnterprise(final BoxAPIConnection api)
public static Iterable<BoxUser.Info> getAllUsersInEnterprise(final BoxAPIConnection api, String filterTerm, String... fields)
public static PartialCollection<BoxUser.Info> getAllUsersInEnterpriseRange(final BoxAPIConnection api, long offset, long limit)
public static PartialCollection<BoxUser.Info> getAllUsersInEnterpriseRange(final BoxAPIConnection api, long offset, long limit, String filterTerm, String... fields)
```

**Comment by gcurtis** [comment]
Hey, @sohtsuka - that'd be awesome! I'd definitely appreciate help with implementing this.

Those interfaces look good. I just have a couple of suggestions/questions:

1. Can we call the method `getAllEnterpriseUsers` instead? I feel it's a little more succinct.
2. Do you have a need for the `getAllUsersInEnterpriseRange` methods? I'd prefer to hold off on adding those (in the name of simplicity) unless there are users that have a use-case for them.

Thanks again for offering to implement these.

**Comment by sohtsuka** [comment]
Thanks for the response.

1. That makes sense. We can adopt `getAllEnterpriseUsers`.
2. Actually, I don't have any use cases. They are simply added referring to `BoxFolder.getChildrenRange`. I will omit them.

**Comment by tcharles79** [comment]
Is it possible to add limit and offset into the method call?

       public static Iterable<BoxUser.Info> getAllEnterpriseUsers(final BoxAPIConnection api, final String filterTerm,  final String offset, final String limit, final String... fields) {

**Comment by gcurtis** [comment]
The interface we have right now returns an Iterable which will automatically page through all of the users - which should be easier than needing to manually specify an offset and limit for paging.

Do you have a requirement for retrieving a specific subset of users using an offset and limit?
