### ISSUE TITLE
File Versions: Unable to get "version_number" for versions

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/box-java-sdk#946]
### Is your feature request related to a problem? Please describe.
A the moment we can get the versions of a file using the following snippet. 
```
BoxFile file = new BoxFile(api, "id");
Collection<BoxFileVersion> versions = file.getVersions();
for (BoxFileVersion version : versions) {
    System.out.format("SHA1 of \"%s\": %s\n", item.getName(), version.getSha1());
}
```

The issue is that the BoxFileVersion object doesn't have the version number of that particular version. In order to get it we need to send the fields parameter just like we do with getInfo(fields) but that is not available. At the moment to get that information I have to create a call like this:
```
            URL url = new URL(String.format("https://api.box.com/2.0/files/%s/versions/%s?fields=id,type,name,created_at,version_number,ext",objectID,version.getVersionID()));
            BoxAPIRequest request = new BoxAPIRequest(localApi, url, "GET");
            BoxJSONResponse response = (BoxJSONResponse) request.send();
            String json = response.getJSON();
```

As you can see 'version_number' is one of the fields requested

### Describe the solution you'd like
It would be good to have a fields option with the 
`file.getVersions()` ie. `file.getVersions(fields)` where we can then define the fields to be returned.

### Describe alternatives you've considered
The pure REST call as described above.

**Comment by antusus** [comment]
Hi @jacquesvandermerwe,

I think that we will add `file.getVersions(fields...)` just like we have when fetching for example `file.getInfo(fields...)`
If we will have more user requests that "version_number" is required we might add it to file.getVersions() in the future.
Thank you for reporting that.
