### ISSUE TITLE
Add support for Collections

### ISSUE THREAD

**Issue by TLuthra** [box/box-java-sdk#96]
Apps that want to interact with the collections endpoint should be supported

https://developers.box.com/docs/#collections

**Comment by gcurtis** [comment]
Cool, this sounds good! Some questions about this:

* Is the beta available to all users? 
* How do we know what the ID of the user's "Favorites" collection is? The docs explain that we must access it by ID, but I don't see how to figure out what the ID is.
* The docs show that a "collections" field has been added to files and folders. Is this field also retrievable? Do we need to add getters for it?
* Are weblinks supported with collections?

**Comment by TLuthra** [comment]
Cool, this sounds good! Some questions about this:

* Yea, Box Favorites are available to everybody, and I think this is an open public beta.
* Hmm, that seems really weird.  I have no idea how that works, I thought with the "favorites" as the collection_type that would be all we need.  I'll try to follow up on this and see what the situation is. 
* I couldn't see a collections field added to files and folders.  They have the original ```path_collection``` and ```item_collection``` but I'm not sure if there is a way given a folder to see if it is in a collection yet.
* Yea, you can add a weblink to a collection

Overall, I think we should probably wait a bit until the collections API gets a little more robust and the rest of our concerns are ironed out.

**Comment by jdgiotta** [comment]
I can see a collection could be an enterprise re-organization of content that is spread out over many categorized folders.

For example, Sales or Marketing in a company can be executing a campaign that pushes specific products, but these product documents are categorized into other subsets of folders.
