### ISSUE TITLE
Event Type EMAIL_ALIAS_ADD_UNCONFIRMED: Show in results as 'UNKNOWN'

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/box-java-sdk#968]
- [ x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
When requesting events from the Box Event Stream, I noticed that we had 'UNKNOWN' events. When querying those events via CLI it returns an event `EMAIL_ALIAS_ADD_UNCONFIRMED`. That event is not listed against the known event types in the SDK. See the Event JSON below:

`[
    {
        "source": {
            "type": "user",
            "id": "76xxxxx485",
            "name": "Managed User 3",
            "login": "jvaxxxx@xxxxxx.com"
        },
        "created_by": {
            "type": "user",
            "id": "33xxxxxx3",
            "name": "Postmaster (Vertium)",
            "login": "postmaster@xxxxx.com"
        },
        "action_by": null,
        "created_at": "2021-11-29T09:55:40+00:00",
        "event_id": "99ccef60-da75-47cb-a421-ed4a769be1da",
        "event_type": "EMAIL_ALIAS_ADD_UNCONFIRMED",
        "ip_address": "Unknown IP",
        "type": "event",
        "session_id": null,
        "additional_details": {
            "service_id": "5xxx6",
            "service_name": "Box CLI - xxx"
        }
    }
]`

### Expected Behavior
Event name should be listed

### Versions Used
Java SDK: 2.58.0
Java: 11.0.1

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by jacquesvandermerwe** [comment]
Morning, I think I have found another event that is not in the event types enums `SHARED_LINK_REDIRECT_OUT_OF_SHARED_CONTEXT`

**Comment by arjankowski** [comment]
Hi @jacquesvandermerwe,

Yes, it looks like we are missing some of them.
We will add them as soon as possible to this, as well to other SDKs and let you know.

Thanks!
